### ISSUE TITLE
Error when two relation fields defined in form behavior

### ISSUE THREAD

**Issue by masnug** [octobercms/october#1024]
I have photo model that related to property and albums.
```php
class Photo extends File
{
    use \Illuminate\Database\Eloquent\SoftDeletes;

    protected $dates = ['created_at', 'updated_at', 'deleted_at'];

    public $belongsToMany = [
        'albums' => [
            'Empu\LarisCatalog\Models\Album',
            'table' => 'empu_lariscatalog_album_photos',
            'key' => 'file_id',
            'otherKey' => 'album_id'
        ]
    ];

    public $hasOne = [
        'property' => [
            'Empu\LarisCatalog\Models\PhotoProperty',
            'key' => 'file_id'
        ]
    ];
//...
```
Relation behavior config under photo controller:
```yaml
property:
    label: Property
    list: ~/plugins/empu/lariscatalog/models/photoproperty/columns.yaml
    form: ~/plugins/empu/lariscatalog/models/photoproperty/fields.yaml
    view:
        toolbarButtons: update

albums:
    label: Albums
    list: ~/plugins/empu/lariscatalog/models/album/relation_columns.yaml
    form: ~/plugins/empu/lariscatalog/models/album/fields.yaml
    manage:
        recordsPerPage: 10
        showSearch: true
```
And the photo fields.yaml
```yaml
fields:
    title:
        label: Title
    property@update:
        type: partial
        path: ~/plugins/empu/lariscatalog/controllers/photos/_relation_property.htm
        view:
            toolbarButtons: update
    albums:
        tab: Linked Albums
        type: partial
        path: ~/plugins/empu/lariscatalog/controllers/photos/_relation_albums.htm
```
The problem is I get an exception when both of relations property and albums defined in configuration.

> Undefined property: October\Rain\Database\TreeCollection::$exists
> /.../modules/backend/widgets/Form.php line 770

But, when one (or both) of these relations is removed form run well.
