### ISSUE TITLE
Can't render create form on popup

### ISSUE THREAD

**Issue by IcedLime** [octobercms/october#1149]
Hi,
I Creating a backend "Bookmark" plugin to add stared link.

BookMark : belongsToMany Tag
Tag : belongsToMany Bookmark

When I passe from the create page, and I click on "Ad Tags", I can Add tags and create the Bookmark.
But, I try to render the create model Form on a popup. It's failed : 

![Image of Yaktocat](http://img11.hostingpics.net/pics/715430Capture.png) 
![Image of Yaktocat](http://img11.hostingpics.net/pics/890231Capture.png) 

So...

- Button to fire the modal in index.htm : 

```
<a
   data-control="popup"
   data-size="huge"
   data-handler="onPopupCreate"
   href="javascript:;"
   class="btn btn-sm btn-primary oc-icon-plus pull-right">
   <?= e(trans('backend::lang.relation.add_name', ['name'=>trans('bookmark')])) ?>
</a>
```

- Action Controller : 

```
public function onPopupCreate() {
        $model = $this->formCreateModelObject();
        $this->initForm($model);
        return $this->makePartial('popup_create', []);
}
```

- fields.yaml : 
```
fields:

    link:
        label: Link
    title:
        label: Title

tabs:
    stretch: true
    fields:
        tags:
            stretch: true
            type: partial
            tab: Tags
            path: field_tags

```
- the config_relation.yaml : 
```
tags:
    label: Tag
    view:
        list: $/synapse/bookmark/models/tags/columns.yaml
        toolbarButtons: create|add|remove
    manage:
        showSearch: true
        recordsPerPage: 10
        list: $/synapse/bookmark/models/tags/columns.yaml
        form: $/synapse/bookmark/models/tags/fields.yaml
```
