### ISSUE TITLE
Can not use Repeater widget in theme data.

### ISSUE THREAD

**Issue by krisawzm** [octobercms/october#1194]
When adding a Repeater widget to the `form` section in the `theme.yaml` file, an exception is thrown when trying to save the form:

    "Unexpected type of array, should attribute "social_buttons" be jsonable?" on line 1064 of /path/to/october/vendor/october/rain/src/Database/Model.php

### Steps to reproduce:

- Set up a `theme.yaml` file with a repeater form field defined:

```
name: foo
author: bar

form:
    fields:
        something:
            type: repeater
            form:
                fields:
                    somefield:
                        label: I do not work
```

- In the backend, go to CMS > Front-end theme > Customize
- Save the form
