### ISSUE TITLE
RecordFinder add support for "disabled" option

### ISSUE THREAD

**Issue by that0n3guy** [octobercms/october#1199]
I have a recordfinder added to a backend form like so:

```
    submission:
        label: Submission
        type: recordfinder
        list: $/oca/webforms/models/submission/columns.yaml
        prompt: Click the %s button to find a submission
        nameFrom: id
```

I have it hidden or disabled via the models `filterFields()` method.  

Bugs:
- When I hide it, I get an error b/c it submits a blank relation id. 
- when I disable it, its still editable
