### ISSUE TITLE
How use form widget repeater in frontend ?

### ISSUE THREAD

**Issue by IcedLime** [octobercms/october#1303]
Hi,
I use form field in frontend like this : https://medium.com/@matissjanis/octobercms-using-backend-forms-in-frontend-component-fe6c86f9296b

But I would like to add repeater too.
I try to use Backend Class in onRun and add js but it's not working.

The dev has create Upload File Backend in frontend, so I think it's possible.

Thank.

**Comment by daviskoko** [comment]
Ensure you have the trailing slash in the addJs directory else it won't work. 
    Eg: $this->addJs('/plugins/acme/posts/assets/javascript/form-control.js');

Can you share your repeater? Its possible that the issue is coming from there as well.

**Comment by IcedLime** [comment]
Hi !

I'm not sur it's a javascript error.

My fields_front_manage_formation.yaml : 
```
fields:
    formation_name:
        label: Intitulé de la formation
        type: text
        required: true
    session:
        type: repeater
        form:
            fields:
                datetime_start:
                    label: Date de début
                    type: text
```

My config_form_front_manage_formation.yaml : 
```
# Model Form Field configuration
form: $/crosbn/formation/models/formation/fields_front_manage_formation.yaml

# Model Class name
modelClass: Crosbn\Formation\Models\Formation
```

My FormationManage.php (component) : 
```
public function onRun()
    {
        // form's assets loading
        $this->addJs('/modules/system/assets/js/framework.extras.js', 'core');
        $this->addJs('/modules/backend/assets/js/october-min.js', 'core');
        $this->addCss('/modules/backend/assets/css/october.css', 'core');
        $this->addCss('/modules/backend/assets/css/controls.css', 'core');

        $formController = new FormationManageCtrl('config_form_front_manage_formation.yaml');
        $formController->create('frontend');

        $this->page['form'] = $formController;
        foreach ($formController->getAssetPaths() as $type => $assets) {
            foreach ($assets as $asset){
                $this->{'add' . ucfirst($type)}($asset);
            }
        }
    }
```

and in the view : 
```
{{ form.formRender()|raw }}
```

The form is corectly render in view but when I click to "Add new Item" (Session). A popup display with this error : "AJAX handler 'formSession::onAddItem' was not found"

I not have formSession Component or Controller... for me, 'onAddItem' is the backend Form method. I just want use it but not create.

I hope it's clear, I'm french
