### ISSUE TITLE
Add comment support for import columns

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#1311]
Having a list of columns for import is great, however occasionally the end user needs a bit more information on what kind of data their CSV should contain. I suggest adding comment support so the import page will look like the following:
![](https://i.imgur.com/43NWYUz.png)

Possible YAML markup:
```yaml
# ===================================
#  Column Definitions
# ===================================

columns:

  ....

  to_url:
    label: To URL

  match_type:
    label: Match Type
    comment: exact, starts_with or ends_with

  ...
```

By default you suggest using a models `columns.yaml` (used by `ListController`) [in the docs](https://github.com/octobercms/docs/blame/master/backend-import-export.md#L39), however I would suggest instead advising users copy their `columns.yaml` to `import_columns.yaml` where we can add import-specific directives such as this new `comment` line without interfering with ListController.
