### ISSUE TITLE
Pivot data support in deferred binding

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#1409]
Is there any way to create relation manager which has some pivot data and works with deffered binding?

Are there any chances for October to support this anytime soon?

**Comment by bombozama** [comment]
I have the same need, but went around it by disabling the field on create (adding a placeholder message that encourages the user to save "soon") and enabling the relation manager on update only.

In the form declaration, it looks something like this:
```yaml
fieldName@create:
    label: Field Name
    placeholder: Please save the record first (Ctrl+s)
    disabled: true
fieldName@update:
    label: Field Name
    type: partial
    path: field_fieldname
```
It's not perfect, but this way you can prevent the user generated error.
