### ISSUE TITLE
Repeater type does not validate field type

### ISSUE THREAD

**Issue by BOOMER74** [octobercms/october#1578]
I have this fields in plugin:
```yaml
products:
    type: repeater
    prompt: Add new product
    form:
        fields:
            product:
                span: left
                label: Product
                type: dropdown
            quantity:
                span: right
                label: Quantity
                type: number
```
**quantity** has rendered as number (right aligned), but not validate on create/save. I know validator in model cannot catch this, because it json, but maybe need add JS validator for this? And if set **default: 1** this work only on create new item, when reopen item and chage **quantity** has empty value.
