### ISSUE TITLE
Bug: Fileupload does not support in repeater

### ISSUE THREAD

**Issue by prhost** [octobercms/october#1637]
When I use fileupload the repeater, he repeats the same image selected an item for all items when saving.

Another discussion about the same thing.
https://octobercms.com/forum/post/form-widgets-repeater?page=1

**Comment by estudiogenius** [comment]
I have the same problem...

**Comment by seanthepottingshed** [comment]
Same here

**Comment by daftspunk** [comment]
File upload depends on a relationship definition so the support is difficult. A suggestion would be to use the `mediafinder` form field instead. We should add to the documentation that form fields that depend on relations are not supported.

**Comment by lilessam** [comment]
I get an error every time I use 'fileupload' in a repeater in my theme.yaml
Would any body know how to resolve this problem? Or it's just not supported yet?

**Comment by daftspunk** [comment]
This was added in a recent build. It is working for me over here:

```
tabs:
    fields:
        site_logo:
            label: Logo
            type: fileupload
            mode: image
            tab: Logo
            imageHeight: 150
```

**Comment by LukeTowers** [comment]
@daftspunk I get a plain 500 error with no other information when attempting to save a record where I use the fileupload field in a repeater with an attachMany or an attachOne relationship setup.
The repeater also includes itself for new items as shown in [this screenshot](https://www.dropbox.com/s/lpxu9t1oikfiqfr/Screenshot%202016-09-06%2015.18.22.png?dl=0)
```
options[powerpoint][slides]:
    label: 'look.coursemanager::lang.models.material.types.powerpoint.slides.label'
    prompt: 'look.coursemanager::lang.models.material.types.powerpoint.slides.add_new'
    span: full
    type: repeater
    tab: 'look.coursemanager::lang.controllers.tabs.options'
    form:
        fields:
            slide_image:
                label: 'look.coursemanager::lang.models.material.types.powerpoint.slides.image'
                span: full
                mode: image
                type: fileupload
                fileTypes: jpg,jpeg,png,gif
                useCaption: false
                
            slide_title:
                label: 'look.coursemanager::lang.models.material.types.powerpoint.slides.title'
                span: full
                type: text

            slide_content:
                label: 'look.coursemanager::lang.models.material.types.powerpoint.slides.content'
                span: full
                type: textarea
```
