### ISSUE TITLE
probleme with input.trigger.js for empty case with dropdown

### ISSUE THREAD

**Issue by odlex** [octobercms/october#1692]
# exemple:
**part of fields.yaml**
```yaml
    repeatable_date_end:
        label: Repetition date end
        type: datepicker
        mode: date
        trigger:
            action: disable|hide
            field: repeatable_frequency
            condition: value[]
   repeatable_frequency:
        label: Repetition frequency
        type: dropdown
        options: listRepeatFrequency
        dependsOn: date_end
        span: left
```
**array return in listRepeatFrequency**
```php
[
 '' => 'none',
 'daily' => 'Daily'
]
```

in the input.trigger.js l.28
```js
this.triggerConditionValue = (match) ? match : ""
```

don't match in the check l.74
```js
$.inArray(triggerValue, this.triggerConditionValue)
```

> **i think default value sould be**
> ```js
> this.triggerConditionValue = (match) ? match : [""]
> ```
> 
> to match with inArray:
> ```js
> $.inArray(triggerValue, this.triggerConditionValue)
> ```

Thank's
Alexandre
