### ISSUE TITLE
Backend dot/array-format field values appear as null

### ISSUE THREAD

**Issue by dshoreman** [octobercms/october#1734]
If you use dot notation to create an associative array of settings in a fields.yaml, for example `mail.sender_name`, the backend form will not display its value upon refresh.

Example code:

```yaml
# mysettings/fields.yaml
tabs:
    fields:
        first_setting:
            label: First Setting
            type: text
        sub.show_second_setting:
            label: Show second setting
            type: switch
        sub.second_setting:
            label: Second setting
            type: text
            trigger:
                action: show
                condition: checked
                field: sub.second_setting
```

To reproduce: Visit a backend settings page with fields as above. Turn on the switch and fill in the two text inputs. Save and refresh.

*Expected:* All fields visible, switch on and with saved data showing in the text inputs

*Actual:* Only the first text input remembers its value. The switch appears in its "off" state, and toggling it shows the second input is empty. **However** it *IS* possible to retrieve values with `MySettings::instance()->sub->second_setting` and `MySettings::instance()->sub->show_second_setting`, so the problem is restricted to backend forms displaying the data.
