### ISSUE TITLE
Title of modal "_manage_list" for toolbar button "link" has wrong title

### ISSUE THREAD

**Issue by philipptempel** [octobercms/october#1755]
**Bug summary:**
Title of the modal for toolbarButton "link" has wrong title

**Request location:**
n/a

**Reproduce steps:**
Given two models
    * Motionpattern hasMany Robots
    * Robot belongsTo Motionpattern
Controller "Robots" implements 'Backend.Behaviors.RelationController'

robots/fields.yaml:
```yaml
fields:
    title:
        label: Title
        type: text

    slug:
        preset: title
        label: Slug
        type: text

    motionpattern:
        label: Motionpattern
        type: partial
        path: field_motionpattern
```

config_relation.yaml:
```yaml
motionpattern:
    label: Motionpattern
    view:
        list:
            columns:
                title:
                    label: Title
                    searchable: true
                created_at:
                    label: Created at
                    type: timetense
        form:
            fields:
                title:
                    label: Title
                    type: text
        toolbarButtons: link|create
    manage:
        list: $/philipptempel/demo/models/motionpattern/columns.yaml
        form: $/philipptempel/demo/models/motionpattern/fields.yaml
        showSearch: true
        recordsPerPage: 10
```
Then clicking on the "Link Motionpattern" button creates a modal title "Add a new Motionpattern".

**Expected result:**
Title of modal should be matching the action i.e., should be "Link existing Motionpattern"

**Actual result:**
Clicking on the "Link Motionpattern" button (cf. first image) creates a modal title "Add a new Motionpattern" (cf. second image)

![screen shot 2016-02-05 at 11 35 21 am](https://cloud.githubusercontent.com/assets/1541337/12843933/a692a94a-cbfc-11e5-8fe8-78ed3e8d4d47.png)
![screen shot 2016-02-05 at 11 35 27 am](https://cloud.githubusercontent.com/assets/1541337/12843934/a6936330-cbfc-11e5-846b-c522e15bba25.png)
