### ISSUE TITLE
UnitTests with GitlabCI how to?

### ISSUE THREAD

**Issue by lgt** [octobercms/october#1764]
I try to run UnitTests using GitlabCI with runners, I have configured a runner using a docker image and services but not all the tests are passing. Actually all database tests are failing in my case

for Example:
```

25) SimpleTreeModelTest::testGetAllChildren
ErrorException: Trying to get property of non-object

/tests/unit/plugins/database/SimpleTreeModelTest.php:10
```
...

here I have my .gitlab-ci.yml

```
image: alexeymasolov/docker-octobercms-nginx-ssh

services:
  - mysql:latest

# Before Script
before_script:
  - composer self-update
  - composer install --prefer-source > /dev/null
  - cd plugins/vendor/my_plugin1 && composer install --prefer-source > /dev/null && cd pwd
  - cd plugins/vendor/my_plugin2 && composer install --prefer-source > /dev/null && cd pwd
  - cp .env.testing .env

stages:
  - build
  - test
  - deploy

# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: user
  MYSQL_PASSWORD: homestead
  MYSQL_DATABASE: october_test

test 1.1:
  image: alexeymasolov/docker-octobercms-nginx-ssh
  services:
        - mysql:latest
  script:
    - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"
    - dir
    - php -v
    - echo "Install OctoberCMS"
    - mkdir storage/cms/cache
    - mkdir storage/cms/combiner
    - mkdir storage/cms/assets
    - chmod -R 777 storage/
    - php artisan october:up
    - echo "Running PHPUnit Tests"
    - php vendor/bin/phpunit --colors --debug  --coverage-text
    - echo "Running PHPUnit Tests on Plugin"
    - cd plugins/vendor/my_plugin1
    - php vendor/bin/phpunit --colors --debug  --coverage-text
```

Under `config/testing `added `database.php` which on run is getting populated but when comes about testing fails
