### ISSUE TITLE
Possible conflict between filterfields and repeater field

### ISSUE THREAD

**Issue by oadslug** [octobercms/october#1792]
When a `repeater` field is used with a `filterfields` method defined, adding a new item to the repeater filed (or loading a repeater field with content already saved) throws an error:

```
dev.ERROR: exception 'ErrorException' with message 'Creating default object from empty value' in /october.dev/plugins/site/models/Page.php:73
```

From Model:

```
public function filterFields($fields, $context = null)
{
    $fields->field1->hidden = true; // line 73
}
```

**Comment by daftspunk** [comment]
Please provide replication instructions. How does someone reproduce this error? What are the form field definitions you are using?

**Comment by oadslug** [comment]
Easiest way to reproduce is using the october/test plugin. 

- Add `$fields->name->hidden = true;` to `filterfields` method on line 47 of /plugins/october/test/models/Country.php`. 
- On front-end, 'countries/create', click on the 'add new item' button of the repeater field on states tab (or load record with repeater field already set).

```
public function filterFields($fields, $context = null)
    {
        // *** add this line
        $fields->name->hidden = true;
        
        // Repeater field shares this logic
        if (!isset($fields->pages_section)) {
            return;
        }

        if (empty($this->pages)) {
            $fields->pages_section->hidden = false;
        }
        else {
            $fields->pages_section->hidden = true;
        }

        if ($this->is_active) {
            $fields->currency->hidden = true;
        }
    }
```

**Comment by oadslug** [comment]
Now that I'm looking at this again, I see that there is already a comment related to this issue, which I didn't notice or comprehend on first read. Although I must admit I'm still confused as to what we should be checking as `!isset`. Perhaps you can clarify. Thank you.

```
// Repeater field shares this logic
if (!isset($fields->pages_section)) {
    return;
}
```

**Comment by jBOKA** [comment]
Hi,

I'm getting this error in a context without a repeater.
The `filterFields` method looks like this:
```PHP
    public function filterFields($fields, $context = null)
    {
        if (true) {
            $fields->author->hidden = false;
        } else {
            $fields->author->hidden = true;
        }
    }
```
where `author` is a relation field. This error occurs (in the same controller) even when I switch from `author` to a text field.

This is what the `$fields` dump looks like:
```
{#476 ▼
  +"author": FormField {#425 ▼
    +fieldName: "author"
    +arrayName: "News"
    +idPrefix: "Form"
    +label: "Autor"
    +value: "1"
    +valueFrom: "author"
    +defaults: null
    +defaultFrom: null
    +tab: null
    +type: "widget"
    +options: null
    +span: "full"
    +size: "large"
    +context: null
    +required: false
    +disabled: false
    +hidden: false
    +stretch: false
    +comment: null
    +commentPosition: "below"
    +commentHtml: false
    +placeholder: null
    +attributes: null
    +cssClass: null
    +path: null
    +config: array:5 [▶]
    +dependsOn: null
    +trigger: null
    +preset: null
  }
  +"image": FormField {#432 ▶}
  +"heading_1": FormField {#435 ▶}
  +"active": FormField {#436 ▶}
  +"heading_2": FormField {#437 ▶}
  +"body": FormField {#438 ▶}
  +"start_date": FormField {#439 ▶}
  +"end_date": FormField {#444 ▶}
  +"add_images": FormField {#445 ▶}
}
```

Strangely on a different model I use
```PHP
    public function filterFields($fields, $context = null)
    {
        if ($fields->status->value === 'invited') {
            $fields->appointment_description->hidden = false;
        } else {
            $fields->appointment_description->hidden = true;
        }
    }
```
without any problems (`appointment_description` is a text field).

So I can't really say how to reproduce.

Any ideas?

**Comment by jBOKA** [comment]
Also here's the whole form `config.yaml`:
```
fields:
    author:
        label: Autor
        type: relation
        emptyOption: -- ich selbst --
        nameFrom: full_name
    image:
        label: Hauptbild
        type: mediafinder
        mode: image
        prompt: '%s Bitte ein Bild auswählen'
        span: right
    heading_1:
        label: Überschrift 1
        commentAbove: Große Überschrift
        type: text
        span: left
    active:
        label: Sichtbar
        commentAbove: Wenn nicht sichtbar, wird die Datumsautomatik obsolet
        type: switch
        default: 1
        span: right
    heading_2:
        label: Überschrift 2
        commentAbove: Kleine Überschrift
        type: text
        span: left
    body:
        label: Text
        type: richeditor
        size: large
        span: full
    start_date:
        label: Anzeigen ab
        type: datepicker
        mode: datetime
        span: left
    end_date:
        label: Anzeigen bis
        type: datepicker
        mode: datetime
        span: right
    add_images:
        label: Weitere Bilder
        type: repeater
        form:
            fields:
                file:
                    label: Bild
                    type: mediafinder
                    mode: image
                    span: left
```
