### ISSUE TITLE
Possible bug: using 'showTree:true' and 'related field' in column prints 'related model json object' instead of 'related model value'.

### ISSUE THREAD

**Issue by oadslug** [octobercms/october#1830]
When defining the list view columns in a controller, if the list is defined to `showTree:true` (in 'config_list.yaml'), and a column is defined as a related field (in 'columns.yaml'), the list will print the entire model as a json object in the column, instead of the field value.

In 'config_list.yaml'

```
title: 'Title'
modelClass: Owner\Plugin\Models\MyModel
list: ~/plugins/owner/plugin/models/mymodel/columns.yaml
recordUrl: 'owner/plugin/mymodel/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showTree: true
```

In 'columns.yaml'

```
columns:
    myrelation:
        label: Title
        type: text
        relation: myrelation
        select: title
```

In model

```
public $belongsTo = [
        'myrelation' => ['Owner\Plugin\Models\MyRelationModel', 'key' => 'myrelation_id'],
];
```

Printed in column when list is rendered:

```
{"id":1,"title":"Title","slug":"title","is_active":1,"updated_at":"2016-03-03 03:27:59","created_at":"2016-03-03 03:27:59"}
```
