### ISSUE TITLE
[FeatureRequest]: Allow recordfinder and relation form fields to be prepopulated

### ISSUE THREAD

**Issue by oadslug** [octobercms/october#1838]
It would be great if 'recordfinder' and 'relation' fields could be prepopulated in the same way as other field types. One way to do this might be to use the 'defaultFrom' field config option, and pass in either the id or the related model. For example:

In model:

```
public function getCurrentUserAttribute()
{
    return BackendAuth::getUser();
}
```

In 'fields.yaml':

```
fields:
    author:
        label: Author
        type: recordfinder
        nameFrom: login
        prompt: Choose
        title: Users
        list: $/author/plugin/models/page/user_columns.yaml
        defaultFrom: currentUser[id]
```

Note: This approach currently works fine for text fields.
