### ISSUE TITLE
Feature Request: allow Relation Manager to be defined without toolbar buttons

### ISSUE THREAD

**Issue by oadslug** [octobercms/october#1842]
It would be great if the Relation Manager could be defined without toolbar buttons so that it can be used as a 'read-only' relation list, or restricted to manage existing relations only. Not sure the best way to implement this, but I assume that you could specify 'false' or '0' for the 'toolbarbuttons' config option (or just pass an empty string "").

```
items:
    label: Invoice Line Item
    view:
        list: $/acme/pay/models/invoiceitem/columns.yaml
        toolbarButtons: false
    manage:
        form: $/acme/pay/models/invoiceitem/fields.yaml
        recordsPerPage: 10
```
