### ISSUE TITLE
Call to a member function hasRelation() on null

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#1868]
Hi @daftspunk 

I've extending a collection of models via a plugin boot method, to include a morphOne relationship to an Meta model for SEO purposes. 

I've added the relationship, the fillable and jsonable fields, however when I attempt to save I get the following error:

<img width="742" alt="screen shot 2016-03-22 at 22 23 06" src="https://cloud.githubusercontent.com/assets/12046965/13969843/057fbef8-f07d-11e5-9b3b-940c5a156b2e.png">

Here follows my code:

**Boot method in Plugin.php**

```php
public function boot()
    {
        if (!App::runningInBackend())
        {
            return;
        }

        $seoModels = Settings::get('seo_models');

        if(!empty($seoModels))
        {
            foreach ($seoModels as $seoModel)
            {
                $model = $seoModel['model_namespace'];

                if (class_exists($model)) {

                    $model::extend(function($model) {

                        $model->morphOne = [
                            'meta' => [
                                'ThePottingShed\Seo\Models\Meta',
                                'name' => 'meta_taggable'
                            ]
                        ];

                        $model->fillable($model->getFillable() + [
                            'meta_title',
                            'meta_description',
                            'meta_keywords',
                            'canonical_url',
                            'redirect_url',
                            'robot_index',
                            'robot_follow'
                        ]);

                        $model->jsonable(['meta']);

                        $model->bindEvent('model.beforeValidate', function() use ($model) {
                            $model->rules['meta_title']       = 'required';
                            $model->rules['meta_description'] = 'required';
                            $model->rules['meta_keywords']    = 'required';
                        });
                    });
                }
            }
        }

        Event::listen('backend.form.extendFields', function ($widget)
        {
            $seoModels = Settings::get('seo_models');

            if (!empty($seoModels))
            {
                foreach($seoModels as $seoModel)
                {
                    if(get_class($widget->model) == $seoModel['model_namespace']) {

                        $widget->addFields([
                            'meta[meta_title]' => [
                                'label' => 'thepottingshed.seo::lang.settings.fields.meta_title',
                                'placeholder' => 'thepottingshed.seo::lang.settings.fields.meta_title_description',
                                'type' => 'text',
                                'tab' => 'thepottingshed.seo::lang.settings.tabs.meta',
                                'required' => 1
                            ],
                            'meta[meta_description]' => [
                                'label' => 'thepottingshed.seo::lang.settings.fields.meta_description',
                                'placeholder' => 'thepottingshed.seo::lang.settings.fields.meta_description_placeholder',
                                'type' => 'charactercounttextarea',
                                'characterLimit' => 110,
                                'size' => 'tiny',
                                'tab' => 'thepottingshed.seo::lang.settings.tabs.meta',
                                'required' => 1
                            ],
                            'meta[meta_keywords]' => [
                                'label' => 'thepottingshed.seo::lang.settings.fields.meta_keywords',
                                'placeholder' => 'thepottingshed.seo::lang.settings.fields.meta_keywords_placeholder',
                                'type' => 'wordcounttextarea',
                                'wordLimit' => 12,
                                'size' => 'tiny',
                                'tab' => 'thepottingshed.seo::lang.settings.tabs.meta',
                                'required' => 1
                            ],
                            'meta[canonical_url]' => [
                                'label' => 'thepottingshed.seo::lang.settings.fields.canonical_url',
                                'placeholder' => 'thepottingshed.seo::lang.settings.fields.canonical_url_placeholder',
                                'type' => 'text',
                                'tab' => 'thepottingshed.seo::lang.settings.tabs.meta',
                                'span' => 'left'
                            ],
                            'meta[redirect_url]' => [
                                'label' => 'thepottingshed.seo::lang.settings.fields.redirect_url',
                                'placeholder' => 'thepottingshed.seo::lang.settings.fields.redirect_url_placeholder',
                                'type' => 'text',
                                'tab' => 'thepottingshed.seo::lang.settings.tabs.meta',
                                'span' => 'right'
                            ],
                            'meta[robot_index]' => [
                                'label' => 'thepottingshed.seo::lang.settings.fields.robot_index',
                                'type' => 'dropdown',
                                'tab' => 'thepottingshed.seo::lang.settings.tabs.meta',
                                'options' => $this->getIndexOptions(),
                                'default' => 'index',
                                'span' => 'left'
                            ],
                            'meta[robot_follow]' => [
                                'label' => 'thepottingshed.seo::lang.settings.fields.robot_follow',
                                'type' => 'dropdown',
                                'tab' => 'thepottingshed.seo::lang.settings.tabs.meta',
                                'options' => $this->getFollowOptions(),
                                'default' => 'follow',
                                'span' => 'right'
                            ],
                        ],
                        'primary');
                    }
                }
            }
        });
    }
```

**ThePottingShed\Seo\Models\Meta:**

```php
<?php namespace ThePottingShed\Seo\Models;

use Model;

class Meta extends Model
{
	/**
	 * @var string The database table used by the model.
	 */
	public $table = 'thepottingshed_seo_meta';

	public $morphTo = [
		'meta_taggable' => []
	];
}
```

Would you be able to shed any light on this matter?

**Comment by daftspunk** [comment]
MorphOne is not currently support, as far as I know. Feel free to submit a PR to the [test plugin](https://github.com/daftspunk/oc-test-plugin) for initial testing and moving us closer to implementation of this feature.

**Comment by seanthepottingshed** [comment]
Cheers @daftspunk

**Comment by seanthepottingshed** [comment]
Managed to fix the null error by amending the **FormModelSaver** Trait:

```php

protected function setModelAttributes($model, $saveData)
    {
        $this->modelsToSave[] = $model;

        if (!is_array($saveData)) {
            return;
        }

        $singularTypes = ['belongsTo', 'hasOne', 'morphOne'];
        $nestedAttributes = [];
        foreach ($saveData as $attribute => $value) {
            if(!in_array($attribute, $nestedAttributes)) {
                $isNested = $attribute == 'pivot' || (
                    $model->hasRelation($attribute) &&
                    in_array($model->getRelationType($attribute), $singularTypes)
                );
                if ($isNested && is_array($value)) {
                    foreach($value as $attribute => $value) {
                        $nestedAttributes[] = $attribute;
                    }
                    $this->setModelAttributes($model->{$attribute}, $value);
                }
                elseif ($value !== FormField::NO_SAVE_DATA) {
                    $model->{$attribute} = $value;
                }
            }
        }
    }
```

However now I have the following error in the **FormController**:

```"Call to a member function save() on null"```

**Comment by seanthepottingshed** [comment]
**ThePottingShed\Seo\Models**

```php
<?php namespace ThePottingShed\Seo\Models;

use Model;

class Meta extends Model
{
	/**
	 * @var string The database table used by the model.
	 */
	public $table = 'thepottingshed_seo_meta';

	public $timestamps = false;

	public $morphTo = [
		'metataggable' => []
	];

	public $fillable = [
		'meta_title',
		'meta_description',
		'meta_keywords',
		'canonical_url',
		'redirect_url',
		'robot_index',
		'robot_follow'
	];
}
```

**Comment by seanthepottingshed** [comment]
**ThePottingShed\Seo\Updates\CreateMetaTable**
```php
<?php namespace ThePottingShed\Seo\Updates;

use Schema;
use October\Rain\Database\Updates\Migration;

class CreateMetaTable extends Migration
{
	public function up()
	{
		Schema::create('thepottingshed_seo_meta', function($table)
		{
			$table->engine = 'InnoDB';
			$table->increments('id')->unsigned();
			$table->integer('metataggable_id')->unsigned()->index();
			$table->string('metataggable_type');
			$table->string('meta_title')->nullable();
			$table->string('meta_description')->nullable();
			$table->string('meta_keywords')->nullable();
			$table->string('canonical_url')->nullable();
			$table->string('redirect_url')->nullable();
			$table->string('robot_index')->nullable();
			$table->string('robot_follow')->nullable();
		});
	}

	public function down()
	{
		Schema::dropIfExists('thepottingshed_seo_meta');
	}
}
```

**Comment by seanthepottingshed** [comment]
**ThePottingShed\Projects\Models\Project**

```php
<?php namespace ThePottingShed\Projects\Models;

use Model;

/**
 * Model
 */
class Project extends Model
{
    use \October\Rain\Database\Traits\Validation;
    use \October\Rain\Database\Traits\Sortable;

    /**
     * @var string The database table used by the model.
     */
    public $table = 'thepottingshed_projects_project';

    /*
     * Validation
     */
    public $rules = [
        'heading'             => 'required',
        'sub_heading'         => 'required',
        'slug'                => 'required',
        'summary'             => 'required',
        'description'         => 'required',
        'hero_image'          => 'required',
        'images'              => 'required_if:is_video,0',
        'vimeo_id'            => 'required_if:is_video,1'
    ];

	/**
     * Custom validation messages for required_if.
     *
     * @var array
     */
    public $customMessages = [
        'hero_image.required_if' => 'Select Hero Image',
        'images.required_if'     => 'Select images',
        'vimeo_id.required_if'   => 'Enter Vimeo ID'
    ];

    /*
     * A given project has associated Meta Tags.
     */
    public $morphOne = [
        'meta' => [
            'ThePottingShed\Seo\Models\Meta',
            'name' => 'metataggable'
        ]
    ];

    /**
     * A given project has a hero image.
     *
     * @var array
     */
    public $attachOne = [
        'hero_image' => ['System\Models\File']
    ];

    /**
     * A given project has multiple images.
     *
     * @var array
     */
    public $attachMany = [
        'images' => ['System\Models\File']
    ];

    /**
     * Display on homepage.
     *
     * @param $query
     * @return mixed
     */
    public function scopeIsHeroProject($query)
    {
        return $query->whereDisplayOnHomepage(1)->whereIsPublic(1);
    }

	/**
     * Is Public.
     *
     * @param $query
     * @return mixed
     */
    public function scopeIsPublic($query)
    {
        return $query->whereIsPublic(1);
    }

	/**
     * Hero image for list.
     *
     * @return string
     */
    public function listExtendQuery($query)
    {
        $query->with('hero_image');
    }
}
```

**Comment by seanthepottingshed** [comment]
**Widget extend fields snippet from boot method**

```php

$widget->addFields([
			'meta[meta_title]' => [
				'label' => 'thepottingshed.seo::lang.settings.fields.meta_title',
				'placeholder' => 'thepottingshed.seo::lang.settings.fields.meta_title_description',
				'type' => 'text',
				'tab' => 'thepottingshed.seo::lang.settings.tabs.meta',
				'required' => 1
			],
			'meta[meta_description]' => [
				'label' => 'thepottingshed.seo::lang.settings.fields.meta_description',
				'placeholder' => 'thepottingshed.seo::lang.settings.fields.meta_description_placeholder',
				'type' => 'charactercounttextarea',
				'characterLimit' => 110,
				'size' => 'tiny',
				'tab' => 'thepottingshed.seo::lang.settings.tabs.meta',
				'required' => 1
			],
			'meta[meta_keywords]' => [
				'label' => 'thepottingshed.seo::lang.settings.fields.meta_keywords',
				'placeholder' => 'thepottingshed.seo::lang.settings.fields.meta_keywords_placeholder',
				'type' => 'wordcounttextarea',
				'wordLimit' => 12,
				'size' => 'tiny',
				'tab' => 'thepottingshed.seo::lang.settings.tabs.meta',
				'required' => 1
			],
			'meta[canonical_url]' => [
				'label' => 'thepottingshed.seo::lang.settings.fields.canonical_url',
				'placeholder' => 'thepottingshed.seo::lang.settings.fields.canonical_url_placeholder',
				'type' => 'text',
				'tab' => 'thepottingshed.seo::lang.settings.tabs.meta',
				'span' => 'left'
			],
			'meta[redirect_url]' => [
				'label' => 'thepottingshed.seo::lang.settings.fields.redirect_url',
				'placeholder' => 'thepottingshed.seo::lang.settings.fields.redirect_url_placeholder',
				'type' => 'text',
				'tab' => 'thepottingshed.seo::lang.settings.tabs.meta',
				'span' => 'right'
			],
			'meta[robot_index]' => [
				'label' => 'thepottingshed.seo::lang.settings.fields.robot_index',
				'type' => 'dropdown',
				'tab' => 'thepottingshed.seo::lang.settings.tabs.meta',
				'options' => $this->indexOptions,
				'default' => 'index',
				'span' => 'left'
			],
			'meta[robot_follow]' => [
				'label' => 'thepottingshed.seo::lang.settings.fields.robot_follow',
				'type' => 'dropdown',
				'tab' => 'thepottingshed.seo::lang.settings.tabs.meta',
				'options' => $this->followOptions,
				'default' => 'follow',
				'span' => 'right'
			]
		], 'primary');

```

**Comment by seanthepottingshed** [comment]
**ThePottingShed\Projects\Updates\CreateProjectsTable**

```php
<?php namespace ThePottingShed\Projects\Updates;

use Schema;
use October\Rain\Database\Updates\Migration;

class CreateProjectsTable extends Migration
{
    public function up()
    {
        Schema::create('thepottingshed_projects_project', function($table)
        {
            $table->engine = 'InnoDB';
            $table->increments('id')->unsigned();
            $table->string('heading');
            $table->string('sub_heading');
            $table->string('slug');
            $table->text('summary');
            $table->text('description');
            $table->boolean('display_on_homepage')->default(0);
            $table->boolean('is_public')->default(0);
            $table->boolean('is_video')->default(0);
            $table->string('vimeo_id')->nullable();
            $table->string('background_color', 7)->nullable();
            $table->text('quote')->nullable();
            $table->string('quote_author')->nullable();
            $table->timestamp('created_at');
            $table->timestamp('updated_at');
            $table->integer('sort_order')->unsigned();
        });
    }
    
    public function down()
    {
        Schema::dropIfExists('thepottingshed_projects_project');
    }
}
```

**Comment by daftspunk** [comment]
Are you using this trick to ensure the model always exists?

    public function formExtendModel($model)
    {
        if (!$model->meta) {
            $model->meta = new Meta;
        }

        return $model;
    }

**Comment by seanthepottingshed** [comment]
Yep, still fails

**Comment by seanthepottingshed** [comment]
**ThePottingShed\Projects\Models\Project\fields.yaml**

```yaml
tabs:
    fields:
        is_video:
            label: 'thepottingshed.projects::lang.project.is_video'
            span: auto
            type: switch
            tab: 'thepottingshed.projects::lang.project.content_tab'
        heading:
            label: 'thepottingshed.projects::lang.project.heading'
            span: left
            placeholder: 'thepottingshed.projects::lang.project.heading_placeholder'
            required: 1
            type: text
            tab: 'thepottingshed.projects::lang.project.content_tab'
        slug:
            label: 'thepottingshed.projects::lang.project.slug'
            span: right
            placeholder: 'thepottingshed.projects::lang.project.slug_placeholder'
            required: 1
            preset:
                field: heading
                type: slug
            type: text
            tab: 'thepottingshed.projects::lang.project.content_tab'
        sub_heading:
            label: 'thepottingshed.projects::lang.project.sub_heading'
            span: left
            placeholder: 'thepottingshed.projects::lang.project.sub_heading'
            type: text
            tab: 'thepottingshed.projects::lang.project.content_tab'
        hero_image:
            label: 'thepottingshed.projects::lang.project.hero_image'
            mode: image
            fileTypes: 'png,jpg'
            useCaption: 0
            thumbOptions:
                mode: exact
                extension: auto
            span: auto
            required: 1
            type: fileupload
            tab: 'thepottingshed.projects::lang.project.content_tab'
        summary:
            label: 'thepottingshed.projects::lang.project.summary'
            size: small
            span: left
            placeholder: 'thepottingshed.projects::lang.project.summary_placeholder'
            required: 1
            characterLimit: 150
            type: charactercounttextarea
            tab: 'thepottingshed.projects::lang.project.content_tab'
        description:
            label: 'thepottingshed.projects::lang.project.description'
            size: large
            span: left
            placeholder: 'thepottingshed.projects::lang.project.description_placeholder'
            required: 1
            type: charactercounttextarea
            characterLimit: 1000
            tab: 'thepottingshed.projects::lang.project.content_tab'
        quote:
            label: 'thepottingshed.projects::lang.project.quote'
            size: small
            span: left
            characterLimit: '150'
            type: charactercounttextarea
            tab: 'thepottingshed.projects::lang.project.content_tab'
        images:
            label: 'thepottingshed.projects::lang.project.images'
            mode: image
            fileTypes: 'png,jpg,jpeg'
            useCaption: 0
            thumbOptions:
                mode: exact
                extension: auto
            span: right
            required: 1
            trigger:
                action: hide
                field: is_video
                condition: checked
            type: fileupload
            tab: 'thepottingshed.projects::lang.project.content_tab'
        quote_author:
            label: 'thepottingshed.projects::lang.project.quote_author'
            span: left
            type: text
            tab: 'thepottingshed.projects::lang.project.content_tab'
        vimeo_id:
            label: 'thepottingshed.projects::lang.project.vimeo_id'
            span: left
            placeholder: 'thepottingshed.projects::lang.project.vimeo_id_placeholder'
            required: 1
            trigger:
                action: hide
                field: is_video
                condition: unchecked
            type: text
            tab: 'thepottingshed.projects::lang.project.content_tab'
        background_color:
            label: 'thepottingshed.projects::lang.project.background_color'
            span: left
            required: 0
            type: colorpicker
            tab: 'thepottingshed.projects::lang.project.content_tab'
        is_public:
            label: 'thepottingshed.projects::lang.project.is_public'
            span: left
            type: switch
            tab: 'thepottingshed.projects::lang.project.content_tab'
        display_on_homepage:
            label: 'thepottingshed.projects::lang.project.display_on_homepage'
            span: left
            type: switch
            tab: 'thepottingshed.projects::lang.project.content_tab'

        meta[meta_title]:
            label: 'Meta Title'
            span: left
            type: text
            tab: Meta
            required: 1
        meta[meta_keywords]:
            label: 'Meta Keywords'
            span: right
            type: text
            tab: Meta
            required: 1
        meta[meta_description]:
            label: 'Meta Description'
            span: full
            type: textarea
            size: tiny
            tab: Meta
            required: 1
        meta[canonical_url]:
            label: 'Canonical URL'
            span: left
            type: text
            tab: Meta
            required: 1
        meta[redirect_url]:
            label: 'Redirect URL'
            span: right
            type: text
            tab: Meta
            required: 1
        meta[robot_index]:
            label: 'Robot Index'
            span: left
            type: text
            tab: Meta
            required: 1
        meta[robot_follow]:
            label: 'Robot Follow'
            span: right
            type: text
            tab: Meta
            required: 1
```
