### ISSUE TITLE
dropdown options in repeater field doesn't update properly when depending on another field

### ISSUE THREAD

**Issue by fresswolf** [octobercms/october#1891]
Let's assume the following configuration
```yaml
fields:
    one:
        label: One
    another:
        label: Tickets
        type: repeater
        dependsOn: one
        form:
            fields:
                two:
                    label: Two
                    type: dropdown
                    dependsOn: one
```

and further some dropdown options depending on the first field

```php
public function getTwoOptions()
    {
        if ($this->one) {
            return ['my new option: ' . $this->one];
        }
        return ['nothing'];
    }
```

Now, when I add one item and then change the value in "one", the dropdown options for "two" are refreshed as expected. However, if I first edit "one" and then add an item in the repeater, the options inside the repeater have not been refreshed
