### ISSUE TITLE
[Build 319] attachMany relation not working

### ISSUE THREAD

**Issue by mahony0** [octobercms/october#1900]
it seems attachMany not working as expected for this build. I'm getting error:

> Model 'Mahony\Test\Models\Gallery' does not contain a definition for 'images'.

Tried same field with attachOne and it worked.

### Gallery model has:

```php
public $attachMany = [
    'images' => ['System\Models\File', 'order' => 'sort_order'],
];
```

### fields.yaml for Gallery model:
```yaml
fields:
  pagename:
    label: Page
    span: left
    type: dropdown

  images:
    label: Slide Images
    span: full
    type: fileupload
    mode: image
    imageHeight: 150
    imageWidth: 250
```
