### ISSUE TITLE
Partial updated in relationrender switches context

### ISSUE THREAD

**Issue by tschallacka** [octobercms/october#1912]
I have the following fields.yaml

```
fields:
    name: 
        label: Title
    textlines:
        context: [create]
        label: Text fields
        type: belongs_to_selector
        valueFrom: name
    add_new_line:
        context: [update]
        label: Text fields
        type: partial
        path: $/ExitControl/ExitTextSnippets/Controllers/TextContainer/_add_new_line.htm
        
    textlines_sortorder:
        dependsOn: add_new_line
        context: [create,update]
        label: Text fields
        type: partial
        path: $/ExitControl/ExitTextSnippets/Controllers/TextContainer/_textlines_sortorder.htm
```

when `add_new_line` changes the context changes from RelationManager to the main controller

before automatic update:

![image](https://cloud.githubusercontent.com/assets/8638425/14348930/cf68c91e-fcbf-11e5-9c4e-5f065db854f3.png)

After add_new_line changed

![image](https://cloud.githubusercontent.com/assets/8638425/14348944/ea5ba840-fcbf-11e5-832c-df7cc373f38d.png)

It would be nice if the context would stay the same even for the ajax refresh code.
