### ISSUE TITLE
Critical - Datepicker: minDate displayed/used as value when value < minDate

### ISSUE THREAD

**Issue by jfoliveira** [octobercms/october#1920]
If you have a date field in the database with a value that is older than the default `minDate` value, e.g. `1973-03-13,` it will be displayed as `2000-01-01`.
If you save the record **the field value will be replaced by the `minDate` value**.

This happens because the `datepicker` field is specified without a `minDate` value and therefore uses the default value defined on the `datepicker` widget `2000-01-01`:

```yaml
    birth_date:
        label: 'Birth date'
        mode: date
        type: datepicker
```

To workaround this a minDate < value must be specified:
```yaml
    birth_date:
        label: 'Birth date'
        minDate: '1900-01-01'
        mode: date
        type: datepicker
```

After adding the `minDate` the value `1973-03-13` will be displayed - as expected.
I'm not sure where to fix that so I haven't sent a pull request.
