### ISSUE TITLE
span: half support

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#2046]
I have forms with a lot of dynamically added and removed fields. It looks very strange when I have the following config and the middle field is removed:

```yaml
name:
    span: left

enabled:
    span: right

phone:
    span: left
```

I end up with two left span'd fields on separate lines instead of *phone* moving up to take the place of the removed *enabled* field. A `span: half` would simply shuffle its way up to occupy any whitespace directly proceeding it and would work well to compliment `span: full`
