### ISSUE TITLE
Components: Converting a checkbox value to bool deletes variable

### ISSUE THREAD

**Issue by codedge** [octobercms/october#2098]
When pulling a checkbox configuration value and transforming it into a boolean `boolval(Settings::get('key'))` it becomes an empty string when outputting it.

**Actual behaviour**

Create a settings field in your `fields.yaml`:

```yaml
reviews_summary:
        label: Test1
        span: left
        tab: General
        type: checkbox
```

In a components `init()` method:

```php

/**
 * @var bool
 */
public $ratingSummary;

...

public function init()
    {
        $this->ratingSummary = boolval(Settings::get('reviews_summary'));
    }
```

Outputting it in the template file via `{{ tsReview.ratingSummary }}` gives you an empty value back instead of `false`. 

_Note:_ This only happens it the value equals to `false` - for true you get back a `1`.

**Expected behaviour**
When casting a checkbox `0|1` to bool with `boolval` and outputting this into a template I want to see `false` or `true`.
