### ISSUE TITLE
Problem with mimeTypes validation on fileupload widget

### ISSUE THREAD

**Issue by hybridvision** [octobercms/october#2115]
**Expected Behaviour**

According to [the docs](https://octobercms.com/docs/backend/forms#widget-fileupload), we can set the accepted `mimeTypes` for the fileupload widget. Only these types should be accepted.

**Actual Behaviour**

Although I have set the mimeTypes to `image/jpeg, image/png, image/gif` it will not accept files of these types and I get the following error: 

![image](https://cloud.githubusercontent.com/assets/11492432/15991041/d1558292-30a6-11e6-86b1-a701ed92b8a1.png)

I've confirmed with another tool that the files I'm trying to upload are the expected MIME type. I've tried with both JPEG and PNG files and the network inspector seems to show that this is the data type that is being transmitted.

**Steps to reproduce**

1) In the fields.yaml file, add a field like this:

```
slides:
        label: Slides
        type: fileupload
        mimeTypes: image/jpeg, image/png, image/gif
        mode: image
```

2) Try to upload a valid JPG/PNG/GIF file and see the error message.

**OctoberCMS Build**

I have build 345 (latest) but I also am seeing this on a much older installation running build 282.

**Comment by gabsource** [comment]
Should be `jpeg`, `png` and `gif` as is uses Laravel validation : https://laravel.com/docs/5.1/validation#rule-mimes

Try with this :
```
slides:
        label: Slides
        type: fileupload
        mimeTypes: jpeg,png,gif
        mode: image
```
