### ISSUE TITLE
How to use a multidimensional array in fields.yaml?

### ISSUE THREAD

**Issue by reg2005** [octobercms/october#2195]
How to use a multidimensional array in fields.yaml? For example I have $jsonable = ['data']. I want to write so (in fields.yaml):

> fields:
> &nbsp;data[customization][colors][background]:
> &nbsp;&nbsp;label: Background
> &nbsp;&nbsp;type: colorpicker

The Repeater type doesn't approach, т.к it can create many identical fields.
Prompt as to solve it?

**Comment by Litvinenko** [comment]
@reg2005 e.g.:
```
data[extra]:
        label: 'extra'
        type: repeater
        form:
            fields:
                size:
                    label: 'size'
                    type: dropdown
                    options: getExtraSizeOptions
                    span: full
                comment:
                    label: 'comment'
                    type: markdown
                    size: small
                    span: full
                attachment[type]:
                    label: 'attachment type'
                    type: dropdown
                    span: full
                    options: getAttachmentTypeOptions
                attachment[image_url]:
                    label: 'image url'
                    type: mediafinder
                    mode: image
                    span: left
                    trigger:
                        action: show
                        field: attachment[type]
                        condition: value[image]
                attachment[is_circled]:
                    label: 'is circled'
                    type: checkbox
                    span: right
                    trigger:
                        action: show
                        field: attachment[type]
                        condition: value[image]
                attachment[video_code]:
                    label: 'video code'
                    type: textarea
                    size: small
                    span: full
                    trigger:
                        action: show
                        field: attachment[type]
                        condition: value[video]
```
