### ISSUE TITLE
Repeater & FileUpload logical error

### ISSUE THREAD

**Issue by reg2005** [octobercms/october#2196]
Hello! I made short [video of a bug](https://www.youtube.com/watch?v=zjb9Y1BiZkk). 
I use such code:

##### in model :
```php
public $attachOne = [
    'img' => 'System\Models\File',
];
```
##### in fields.yaml:
```yaml
config:
        oc.commentPosition: ''
        prompt: 'Добавить менеджера'
        span: left
        type: repeater
        form:
            fields:
                img:
                    label: Avatar
                    type: fileupload
                    span: left
                    mode: image
                    imageHeight: 240
                    imageWidth: 240
                name:
                    label: Name
                    span: right
                    type: text
                phone:
                    label: Phone
                    span: right
                    type: text
                text:
                    label: Text
                    span: right
                    type: textarea
                    size: small
```

How to make so that on each new copy in the repeater, the new picture was created?
Whether there is a method attach the file to a new copy of the repeater?
