### ISSUE TITLE
Taglist not working in repeater

### ISSUE THREAD

**Issue by Samuell1** [octobercms/october#2254]
hi, taglist have some issues with repeater. I getting this error after save and refresh 

```
       style_palettes:
            tab: Style palettes
            label: Style palettes
            type: repeater
            form:
                fields:
                    name:
                        label: Name
                        span: left1
                    class:
                        label: Class
                        span: left2
                    allowed_tags:
                        label: Allowed tags
                        type: taglist
                        span: right
                        options: true
```

```
exception 'ErrorException' with message 'explode() expects parameter 2 to be string, array given' in D:\laragon\www\myoctober\modules\backend\formwidgets\TagList.php:142
```
##### October build

351
##### Error log

http://pastebin.com/4r7K0EP4
