### ISSUE TITLE
Repeater - translation

### ISSUE THREAD

**Issue by mitjarobic** [octobercms/october#2300]
Hard coded value

https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/Repeater.php#L25

**Comment by mplodowski** [comment]
Prompt message can be changed in field definition.

```
extra_information:
    type: repeater
    prompt: YOUR PROMPT HERE
    form:
        fields:
            added_at:
                label: Date added
                type: datepicker
            details:
                label: Details
                type: textarea
```

http://octobercms.com/docs/backend/forms#widget-repeater
