### ISSUE TITLE
Export: using the form options

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#2302]
##### Expected behavior
as per the documentation http://octobercms.com/docs/backend/import-export#custom-options,
we should be able to add a form yaml option in the config_import_export.htm for the export scenario.

##### Actual behavior
when adding the form yaml options, the fields displays correctly in the export page, but when clik on 'export' we see a modal error showing the first field name defined the form yaml options

##### October build
build 349

**Comment by chrisvidal** [comment]
the content of my model/projectexport/options.yaml is
````yaml
# ===================================
#  Form Field Definitions
# ===================================
fields:
  export_options_comment:
    label: Help
    type: partial
    path: export_hint
  export_from_record:
    label: Export from record number
    type: number
    span: left
    default: 1
  export_until_record:
    label: Export until record number
    type: number
    span: right
    default: 5000
````
