### ISSUE TITLE
Set default value for list filter widget

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#2329]
I don't currently see a way to set default value for filter widget.

For example I have `switch` type filter and I want to set default value to 1. This will fire my first condition specified in configuration

Maybe we can add `default` field in filter configuration that will set default value for filter like so:

```
approved:
    label: Approved
    type: switch
    conditions:
        - is_approved <> true
        - is_approved = true
    default: 1
```
