### ISSUE TITLE
Backend Form Dropdown, Checkboxlist should have sort option

### ISSUE THREAD

**Issue by felagund18** [octobercms/october#2332]
##### Expected behavior
Values of FormDropdown or Checkboxlist are populated from database (by relations), but it does not have a sort option.
```
categories: 
        label: Ангилал
        type: relation
        nameFrom: name
        span: right
        sort: key asc #sort value desc
```
