### ISSUE TITLE
Button styling in ReportWidget wrong text color

### ISSUE THREAD

**Issue by jBOKA** [octobercms/october#2342]
##### Expected behavior

Backend-UI Button ("a" button with classes "btn btn-primary") within backend report widget ("div" with class "report-widget") should have white text color.

##### Actual behavior
Text color is not white because of css rule, which overrides because of css selector specificity
```CSS
.report-widget a {
    color: #7e8c8d;
}
```
vs
```CSS
.btn-primary {
    color: #ffffff;
}
```

##### Reproduce steps
Create report widget with partial
```HTML
<div class="report-widget">
    <a class="btn btn-primary">Test</a>
</div>
```

##### October build
361
