### ISSUE TITLE
[bug] fileupload not available in models afterCreate & afterSave (for create)

### ISSUE THREAD

**Issue by that0n3guy** [octobercms/october#235]
Here is how to duplicate this bug:
- create a model with a file attachment:

```
    public $attachOne = [
        'importfile' => ['System\Models\File', 'public' => false]
    ];
```
- in the model, add an after create

```
    public function afterCreate()
    {
        $importfile = $this->importfile;
    }
```
- create the form yaml and in the backend, upload a file and create your model... something like:

```
    fields:
        name:
            label: Name
        lists:
            label: Lists
            type: relation
        importfile:
            label: Import Excel File
            type: fileupload
            options:
                mode: file-single
```
- result: $import file will be null..... and not a collection like it should be.

This is the same for `afterSave` if on create.  

I would guess that since this is the case, afterUpdate might show the old file if the file is changed in the CMS form.
### Note

An interesting thing is that my other relationships are available on `afterCreate`.
