### ISSUE TITLE
Super users are unable to modify their own group assignments

### ISSUE THREAD

**Issue by LukeTowers** [octobercms/october#2357]
##### Expected behavior

Be able to change the backend user's groups on the update screen for that user.
##### Actual behavior

The groups field does not display on the update screen for backend users. This is due to the context value being set for the groups field. There appears to be a bug in how its contexts are specified or how the form field code handles arrays for context values, as removing that property displays the groups field on the update screen for backend users.

``` yaml
groups:
    context: [create, update]
    label: backend::lang.user.groups
    commentAbove: backend::lang.user.groups_comment
    type: checkboxlist
```
##### Reproduce steps

Create a backend user, assign it to some groups, and then attempt to update it. The groups field will be missing from the update screen.
##### October build

dev-develop (Version as of 2016-09-08)
