### ISSUE TITLE
Backend submenu not rendering

### ISSUE THREAD

**Issue by aurukas** [octobercms/october#2398]
##### Actual behavior

submenu which is described in plugin.yaml is not rendering in backend (no html is produced) 
##### Reproduce steps

```
main-menu-item3:
    label: Pastatai
    url: aurelijus/newcode/buildings
    icon: icon-building
    sideMenu:
        asd:
            label: AAA
            url: aurelijus/newcode/floors
            icon: icon-bars
```
##### October build

367
