### ISSUE TITLE
Unknown built-in list column types

### ISSUE THREAD

**Issue by Eoler** [octobercms/october#2438]
##### Expected behavior
Standard column types number and relation shown in backend list.

##### Actual behavior
Exception: List column type "[typename]" could not be found.

##### Reproduce steps
Create model with a single field in `columns.yaml`:
```    
id:
    label: ID
    #type: number
```
Create controller that references model in `config_list.yaml`:
`list: $/<path_to_model>/columns.yaml`
Observe exception in controller's backend list.

##### October build
375 edge

**Comment by Kunilt** [comment]
+1 same problem

**Comment by Patroklo** [comment]
Hum, it works fine for me... I have made a table 
Just to be sure, you are making a normal list with only the id field from your tables?

But I have the 365 build, don't know if you wrote wrong the 375 or I am behind in the updates :P

**Comment by japomani** [comment]
+1 same problem

**Comment by daftspunk** [comment]
Fixed in Build 376+

**Comment by Eoler** [comment]
This one chokes:
```
    updated_by:
        label: User
        type: relation
        relation: user
        select: login
        sortable: true
```

**Comment by daftspunk** [comment]
Change to 

```
    updated_by:
        label: User
        relation: user
        select: login
        sortable: true
```

The error is correct, there is no *type* called `relation`, there is an option called *relation* though.

**Comment by Eoler** [comment]
Ok, but I have "type: relation" all over the list definitions - it probably was documented somewhere in the past (can't find it in the docs right now).
Not really a problem global search&replace in the project wouldn't solve.

**Comment by MilosStanic** [comment]
I just had the same failure on list column type "html" after the last update. 
It used to work fine until last update. 
I had in yaml: 
```
sound:
        label: 'prove.tests::lang.tests.situation_audio'        
        type: partial
        sortable: false
```

and in my model file: 
```
public function getSoundAttribute(){
        $question = Question::find($this->id);   
        if ($question->situation_audio)
            return '<audio src="'. MediaLibrary::url($question->situation_audio) .'" controls>
                    <div class="media-player-fallback panel-embedded">Your browser doesn\'t support HTML5 audio.</div>
                </audio>';
        else 
            return 'No audio assigned';
    }
```
Now it breaks with the same error. Unknown column type "html". True it's not in the docs, but I picked it up from somewhere before.
