### ISSUE TITLE
OctoberCMS Builder plugin, uploading file and storing in database

### ISSUE THREAD

**Issue by mittultechnobrave** [octobercms/october#2440]
I am new to OctoberCMS and i am trying to create one plugin using builder plugin itself which OctoberCMS provides OctoberCMS Builder Plugin called something like "Social Links", everything working fine expect i am unable to understand the logic of uploading file to any directory and storing that name to my database table's particular field. My table's field name is "social_logo" in which i am trying to store the file name which will be uploaded.

I am able to upload file to default directory at the moment whichever OctoberCMS generating with the file i am uploading. But the thing is i am unable to store that particular file name to my database table's field.

Can someone guide me what should i do to achieve this ?

Here is the my model file what i have done so far.

SocialLinks.php

```
<?php

             namespace Technobrave\SocialLinks\Models;

              use Model;

             /**

                         Model */ class Sociallink extends Model { use \October\Rain\Database\Traits\Validation;

             /*
             Validation */ public $rules = [ ];

    /*
        Disable timestamps by default.
        Remove this line if timestamps are defined in the database table. */ public $timestamps = false;

    /**
        @var string The database table used by the model. */ public $table = 'technobravesociallinks';

    public $attachOne = [ 'social_logo' => 'System\Models\File' ];

           }
```

Fields.yaml

```
fields:
           social_logo:
    label: 'technobrave.sociallinks::lang.Sociallink.social_logo'
    span: auto
    oc.commentPosition: ''
    mode: file
    useCaption: true
    thumbOptions:
        mode: crop
        extension: auto
    type: fileupload
```

columns.yaml

```
columns:
social_logo:
    label: 'technobrave.sociallinks::lang.Sociallink.social_logo'
    type: text
    searchable: true
    sortable: true

```
As you can see on above code, for now i have only 1 field because i am having issues with this particular field only while uploading an image, i want to store that file name . All other form attributes working for me like text,textarea etc so for now i m only trying to achieve this thing with this single field.

Can someone guide me what should i do to solve this ?

Thanks

**Comment by Patroklo** [comment]
I don't see why you whould need to store that data in your table, when it's already stored and linked to your rows.

To access your files you only have to call the attached file as a method.

For example, having a attachOne called `image` I'd call it with `$model->image()`. That will return the FileModel loaded with all the data you could need.

Now. If you really really need to put that file name in your table, you can use a event listener, in this case, the `saved` one.
```php
        Sociallink::saved(
            function($model){
               1 - check you have uploaded a new file
               2 - if so, change the attribute of the model to the new filename
               3 - save again, since you are checking a new file upload, in step 1 you shouldn't have recursivity problems.
               
               To get the file data :
               // Maaaaaaaybe camelcase? 
                // Haven't checked and never did a file with "_" in the name. Sorry
                $file = $model->socialLogo();
            }
        );
``` 

With that you should be ok. You can add this listener to your construct, or your plugin boot, or whatever you want.

**Comment by mittultechnobrave** [comment]
Well the reason i want to store file name is to diplay on front end. How can i display on front end. 
And my database field at the moment showing NULL data . is it what octobercms follows ? coz i have to create field to upload files, isnt it so will it be fine if it stores null data for each row ? 

Also how can i show this attached file in my cms page using this component ?

**Comment by Patroklo** [comment]
Ok, if you want to upload and show the file you must use a file upload of image type. Then, october cms will do everything for you.

You only have to change your `Fields.yaml` social_logo into this:
```
fields:
social_logo:
            label: 'technobrave.sociallinks::lang.Sociallink.social_logo'
            mode: image
            type: fileupload
```

Then you will see the image file uploaded.

thumbOptions, useCaption are not useful there because they have the same value as the default one.

About the `oc.commentPosition` don't know why you are using it or where did you get it, but it's a private property from the plugin builder and you can't define it in your yamls since it gets its value from the commentPosition and comment options.

tl;dr: change the mode from your yaml from file to image and it will do what you want.

**Comment by mittultechnobrave** [comment]
ok .. i have updated my fields.yaml file .. this is how my .yaml look like now .. 

```
fields:
    social_logo:
        label: 'Social Logo'
        span: auto
        oc.commentPosition: ''
        mode: image
        useCaption: true
        thumbOptions:
            mode: crop
            extension: auto
        type: fileupload

```

Can you guide me how can i show now in my any of the front page which will be CMS page ofcourse .. 
This is my test file code for now https://s13.postimg.org/4z0gt376f/test_cms_page.png 

now how can show my image at front page ?
