### ISSUE TITLE
RFE: Empty option for backend dropdown 

### ISSUE THREAD

**Issue by leoquijano** [octobercms/october#2450]
Hi,

I'm building a backend form, like this:

```
  interval_type:
      label: Foo
      type: dropdown
      showSearch: false
      span: left
```

It would be useful to have an option to specify an empty option:

```
      emptyOption: Select a Foo
```

This is similar to what Laravel does, and to what the frontend does. Importantly, it should save NULL as the model value for that field, if the field is not specified. This is important for numeric dropdowns (such as an enum), since adding "" => "something" is not the same, and can bring a database error.

Is this feasible?

**Comment by mplodowski** [comment]
Try to use `placeholder` property.

**Comment by leoquijano** [comment]
Thanks, that works. Maybe the documentation could use an example in the ```dropdown``` section. Even though the ```placeholder``` property is mentioned in the general field options, it is not clear it can be used in the ```dropdown``` field, since HTML5 doesn't support placeholders for SELECTs.

**Comment by leoquijano** [comment]
There's an additional issue with the usage of the ```placeholder``` property. Typically, a lot of dropdowns like this have integer keys. For example, consider the following possible values for a "status" dropdown: 

```php
[ 
  1 => "Pending",
  2 => "Processed",
  3 => "Completed"
]
```

But if I pick the placeholder only, the SELECT will return an empty string ''. A database, like PostgreSQL, won't accept that for a numeric value:

```
"SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "" (SQL: insert into "plan_types" ("recurring", "code", "name", "description", "currency_code", "amount", "recurring_amount", "interval_type", "interval_count", "updated_at", "created_at") values (0, test_plan, Test Plan, Single $50 fee, USD, 500, , , 1, 2016-10-28 18:42:40, 2016-10-28 18:42:40) returning "code")" 
```

So I'm stuck when using the placeholder property. Note that FormController doesn't allow me an easy way to filter values, since the ```update_onSave``` and ```create_onSave``` methods are a bit convoluted.

It would be nice to make dropdowns default to NULL when the placeholder is selected. Something like this in ```modules/backend/widgets/Form.php``` line 976:

```php
/*
 * Number fields should be converted to integers
 */
if ($field->type === 'number') {
    $value = !strlen(trim($value)) ? null : (float) $value;
}
/*
 * Empty dropdown fields should be converted to NULL
 */
elseif ($field->type === 'dropdown') {
    $value = !strlen(trim($value)) ? null : $value;
}
```

is this possible?

**Comment by Patroklo** [comment]
Way I see this problem, you are adding a placeholder into a dropdown. Usually the way that works in web pages is that, if you don't select anything in that object, it will throw a validation error, since those are there to make you select one option. Usually they have texts like "Select an option" or something like that.

To sum up: a placeholder it's a text that gives you a hint of the field, NOT a default value, and you should not use it as that.

For example, in the google sign up form, the month field has the "Month" text by default, and you have to manually add it.

BUT if you want to use a default value in a form field, you should use the `default` parameter:

For instance:

```yaml
        fieldDerp:
            label: Foo
            type: dropdown
            showSearch: false
            span: left
            default: 0
            options:
              0: Default value!
              2: Cacafuti value!
```

It will show `Default value!` the first time you load that form. With this you will be able to use a "placeholderlike" field with an acceptable value for your database table.

You can extend this kind of behavior to relation dropdowns with a different approach. Since you can't add a default parameter into your yaml file because that value will probably be dynamic, you can add into your model class a method that will return that value by default when accessing that attribute:

For instance, we have a chapter attribute that it's a many on one relation:

```yaml
        chapter:
            tab: nicarane.cms::lang.forms.tabs.strip.secondary
            type: relation
            label: nicarane.cms::lang.models.strip.chapter
            emptyOption: nicarane.cms::lang.models.strip.chapter_placeholder
            nameFrom: title
```

The best way I could find to add default values here it's overwriting the attribute get method with this:

```php
     public function getChapterIdAttribute()
    {
        if (!array_key_exists('chapter_id', $this->attributes))
        {
            // here the code you need to load a default chapter id
        }

        return $this->attributes['chapter_id'];
    }

```
Note that I'm using directly the `$this->attributes` array because any other method, like calling `getAttribute()` will cause a stack overflow because they will call the method you are overriding.

With this code you'll have a default value in a relation.

tl:dr: don't ever use `placeholder` as a default value, use `default` instead, and if you use placeholders in dropdowns, check with validation that it's not selected before saving into the database.
