### ISSUE TITLE
Repeater with hasMany relation - Backend

### ISSUE THREAD

**Issue by leoquijano** [octobercms/october#2451]
Hi,

I'm building a backend form with a repeater component. This is the $hasMany entry in the parent model (Plan):

Plugin\Models\Plan class:

``` php
public $hasMany       = [
  'trustees' => 'Plugin\Models\PlanTrustee',
];
```

And this is my YAML field configuration:

```
    ...
    trustees:
        label: Trustees
        type: repeater
        span: left
        prompt: Add New Trustee
        form:
            fields:
                first_name:
                    label: First Name
                    type: text
                last_name:
                    label: Last Name
                    type: text
```

However, when I try to open an existing plan, I get N repeater items (as many as there are trustees), but they're all empty. And when a try to create a new plan (in this case with a Foo Bar trustee), I get this error:

```
SQLSTATE[HY093]: Invalid parameter number: parameter was not defined (SQL: select * from "plan_trustees" where "id" in (Foo, Bar))" on line 662 of /vendor/laravel/framework/src/Illuminate/Database/Connection.php
```

The database tables are the usual:

``` php
Schema::create('plans', function (Blueprint $table) {
  $table->increments('id');
  // ...
});

Schema::create('plan_trustees', function (Blueprint $table) {
  $table->increments('id');
  $table->unsignedInteger('plan_id');
  $table->string("first_name", 50);
  $table->string("last_name", 50);
  $table->timestamps();
  $table->foreign("plan_id")->references("id")->on("plans")->onDelete("cascade");
});
```

I'm using the following versions of October CMS:
- october/rain (dev-master 7325e01)
- october/system (dev-master badbc24)
- october/backend (dev-master 9efa3de)
- october/cms (dev-master 9cd9a2e)

Is this feature working with relations?
