### ISSUE TITLE
General error: 1364 Field 'disk_name' doesn't have a default value

### ISSUE THREAD

**Issue by Asinox** [octobercms/october#2457]
I was uploading files together to my master record.. any idea how to fix this?, btw the files are uploaded.

> PDOException: SQLSTATE[HY000]: General error: 1364 Field 'disk_name' doesn't have a default value in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:390

**Comment by Patroklo** [comment]
At least in my case, I will need more info about your model and form definitions...

**Comment by Asinox** [comment]
@Patroklo  this is a System Model from October, exactly the File model that handle uploads/attachments files

**Comment by Patroklo** [comment]
Ok, something exactly like this?

## MODEL
```php
    public $attachMany = [
        'images' => 'System\Models\File',
    ];
```

##YAML
```yaml
        images:
            label: Cacafuti
            type: fileupload
            mode: image
```
For example? (the yaml can have no mode, for instance)
