### ISSUE TITLE
IIS 7.5 PHP 7.0.13 /backend/preferences error 500.0

### ISSUE THREAD

**Issue by cx-emerge** [octobercms/october#2502]
##### Expected behavior
(Describe expected behavior here)

##### Actual behavior
500.0 error

##### Reproduce steps
iis 7.5
php 7.0.13 x64
database use sqlite3
Click 「Back-end preferences」 menu item

##### October build
382

##### Other
When I delete this, CMS was work
`/modules/backend/models/preference/fields.yaml`
```yaml
        locale:
            tab: backend::lang.backend_preferences.region
            label: backend::lang.backend_preferences.locale
            comment: backend::lang.backend_preferences.locale_comment
            type: dropdown
            span: left
```
I think the problem here
`/modules/backend/models/Preference.php`
`getLocaleOptions` function
