### ISSUE TITLE
After build 385 form field relation doesn't show items related

### ISSUE THREAD

**Issue by alvaro-canepa** [octobercms/october#2524]
##### Expected behavior
Plugins, like RainLab User, must show all groups associated to each user. Or any plugin that use BelongToMany relation, must show all possible relation elements on a checkbox list. 

##### Actual behavior
Plugins, like RainLab User, only show first element in checkbox lists of a BelongsToMany related field.

##### Reproduce steps
```php
// \RainLab\User\Models\User
    public $belongsToMany = [
        'groups' => ['RainLab\User\Models\UserGroup', 'table' => 'users_groups']
    ];
```

```yaml
    # /plugins/rainlab/user/models/user/fields.yaml
    groups:
        label: rainlab.user::lang.user.groups
        tab: rainlab.user::lang.user.account
        type: relation
        emptyOption: rainlab.user::lang.user.empty_groups
```

Navigate to `/backend/rainlab/user/users` and click any user with groups to see the Groups field, empty.

This is the same to any model that has `BelongsToMany` relation

##### October build
385
