### ISSUE TITLE
Preventing a form field from begin submitted 

### ISSUE THREAD

**Issue by meysammahfouzi** [octobercms/october#2560]
Is it possible to prevent a backend form field from being submitted? This would be specially useful when the form contains a field which does not exist in the database. I was thinking of adding an attribute like `submit` which could be set to `false` for fields that we do not want to be submitted, like:

```
fields:
    pivot[hall]:
        label: Hall
        type: text
        span: auto

    pivot[booth]:
        label: Booth
        type: text
        span: auto

    booth_picker:
        label: Select Booth
        type: boothpicker
        span: full
        submit: false
```
My requirement has been explained more in detail here:
http://stackoverflow.com/q/41165172/69537
