### ISSUE TITLE
[feature] Selectable Repeater field Groups

### ISSUE THREAD

**Issue by that0n3guy** [octobercms/october#2772]
I ran across craftcms the other day and one thing they have that is very nice for content editors is matrix fields: https://craftcms.com/docs/matrix-fields

This is basically a repeater field, but is selectable in which fields "groups" you can add.

**Here is craft's backend UI** 
(we wouldn't have a backend ui for making these, we would use the yaml file):
![image](https://cloud.githubusercontent.com/assets/113870/24205464/7a192660-0ee9-11e7-85bf-a4df1a413355.png)

## **Here is a mockup idea of how to do this with octobers repeater fields**
This would have "groups" that could be clicked to add a repeater field; Pull Quote, Text Area, and Image
yaml file:
```
page_body:
    type: repeater
    form:
        fields:
            quote_position:
                label: Quote Position
                type: dropdown
                options:
                    left: Left
                    center: Center
                    right: Right
                selectable_group: Pull Quote     <-- this is the group "Pull Quote"
            quote_content:
                label: Details
                type: textarea
                selectable_group: Pull Quote     <-- this is the group "Pull Quote"
            text_area:
                label: Text Content
                type: textarea
                size: large
                selectable_group: Text Area     <-- this is the group "Text Area"
            img_upload:
                label: Image
                type: fileupload
                mode: image
                imageHeight: 260
                imageWidth: 260
                selectable_group: Image     <-- this is the group "Image"
            img_position:
                label: Image Position
                type: dropdown
                options:
                    left: Left
                    center: Center
                    right: Right
                selectable_group: Image     <-- this is the group "Image"
```

Here is what it might look like as a UI:
![image](https://cloud.githubusercontent.com/assets/113870/24206819/661db208-0eed-11e7-86f4-70258f91d0fb.png)

Templating for this would be similar to https://craftcms.com/docs/matrix-fields#templating except we would use something with the `selectable_group` as the "type".

**Comment by daftspunk** [comment]
Interesting idea. If you could rally some folks to get behind a bounty, I'm sure we could put some time aside to make this happen.

**Comment by that0n3guy** [comment]
How much?   Maybe I'll just get my company to do it.

**Comment by jan-vince** [comment]
Hey it's really interesting - some kind of page builder, isn't it?

How about using nested repeaters?

This of course mean that the login will be reversed and UI not so polished, but can be the way:

* first you add a general block (first repeater)
* after that you can add a specific one (Pull quote, Text area, ...) (from nested repeaters - limited to 1 record only)

But the final result will be probably the same - you will have ordered blocks with specific type and content. And even allow users to add more than one type in one block.

Yaml out of my mind, not sure it actually works - it's just an idea :)

```php
pageBlock:
	type: repeater
	form:
		fields:
			quote:
				type: repeater
				maxItems: 1
				span: left
				form:
					fields:
						quote_position:
							label: Quote Position
							type: dropdown
			text:
				type: repeater
				maxItems: 1
				span: right
				form:
					fields:
						text_area:
							label: Text Content
							type: textarea
							size: large

```

**Comment by that0n3guy** [comment]
@jan-vince That sort of works (if it works currently) but here are the issues I see with that:
* makes the UI confusing
* makes templating more of a pain.   
* some fields will show when you don't want them too, 
* "required" fields will have to be filled even when you don't want them to show.

**Comment by that0n3guy** [comment]
@daftspunk My company will put up some money.   I PM'd you on slack.

**Comment by daftspunk** [comment]
Thanks for your contribution, will take a look soon.

**Comment by rokde** [comment]
+1
Do you need any assistance? We need this behaviour in a customer project really soon. Do you have a schedule?

**Comment by daftspunk** [comment]
Feature is approaching completion.

![grouped-repeater](https://cloud.githubusercontent.com/assets/1392869/25304369/3627b844-27a9-11e7-9c51-648f896fa853.png)

You may test by cloning the October `develop` branch, [pulling down a copy of the latest test plugin](https://github.com/daftspunk/oc-test-plugin) and navigate to Playground > Countries > Update > "Content" tab.

Some items remain

- [ ] Scrollpad not rendering on open
- [ ] Add button lacks loading state
- [ ] Collapsed items should default to or include the group name
- [ ] Test using Translate plugin
- [ ] Document usage

**Comment by daftspunk** [comment]
Note the definition is quite heavy

        content:
            tab: Content
            label: Content
            prompt: Add content block
            span: full
            type: repeater

            groups:
                textarea:
                    name: Textarea
                    description: Basic text field
                    icon: icon-file-text-o
                    fields:
                        text_area:
                            label: Text Content
                            type: textarea
                            size: large
                quote:
                    name: Quote
                    description: Quote item
                    icon: icon-quote-right
                    fields:
                        quote_position:
                            span: auto
                            label: Quote Position
                            type: radio
                            options:
                                left: Left
                                center: Center
                                right: Right
                        quote_content:
                            span: auto
                            label: Details
                            type: textarea
                image:
                    name: Image
                    description: Pick something from the media library
                    icon: icon-photo
                    fields:
                        img_upload:
                            span: auto
                            label: Image
                            type: mediafinder
                            mode: image
                            imageHeight: 260
                            imageWidth: 260

                        img_position:
                            span: auto
                            label: Image Position
                            type: radio
                            options:
                                left: Left
                                center: Center
                                right: Right

This should reduce the bulk and make definition sets reusable


        content:
            tab: Content
            label: Content
            prompt: Add content block
            span: full
            type: repeater

            groups: $/acme/demo/config/repeater_fields.yaml

- [ ] Feature tested / implemented

**Comment by that0n3guy** [comment]
Nice, I may not have time to test until monday, but if I do I'll post something.    Hows templating work?   Loop through "groups" and check by group "name" if needed?

**Comment by daftspunk** [comment]
The repeaters logic has been modified in how it stores the data, previously it kept an index/id as a key like this:
```
{
    1: { foo: bar },
    2: { hello: world }
}
```

Now the data is stored differently, as a clean array with the meta data spliced in with the data.

```
[
    { _index: 1, _group: quote, foo: bar },
    { _index: 2, _group: textarea, hello: world },
]
```

This should be backwards compatible.

- [ ] Above assertion has been tested

**Comment by daftspunk** [comment]
This feature is complete in `develop` branch. Just need someone else to test it out before we package it up in to a build.

**Comment by that0n3guy** [comment]
Hey, finally got around to testing this out.  Everything I see looks good.  I haven't tried putting this on the frontend, but not sure why that would be a problem.

Thanks @daftspunk !

**Comment by daftspunk** [comment]
Hearing many praises sung about this feature already. From all of us, thanks for backing it @that0n3guy!

**Comment by daftspunk** [comment]
Note the stored datasets have been revised in Build 417. Indexes are no longer included in the data, they are now implicit and rewritten based on their position in the array.

```
# Non grouped mode
[
    { foo: bar },
    { hello: world }
]

# Grouped mode
[
    { _group: quote, foo: bar },
    { _group: textarea, hello: world },
]
```

**Comment by that0n3guy** [comment]
> Hearing many praises sung about this feature already. From all of us, thanks for backing it 

Awesome!   I know its one of craftcms's most touted feature so it should do well in october.   Thanks for your hard work @daftspunk

**Comment by jBOKA** [comment]
Missed all this. This is a major step to provide flexibility to devs and usability to customers. Thanks for pushing @that0n3guy and for implementing @daftspunk. There's been a lot of discussion about providing flexible layouting functionality. This might be a october-like solution to allow exactly this kind of functionality without getting opinionated about content management.
Really appreciate where the project is going. Great work!

**Comment by AugmentBLU** [comment]
This is a great addition to October. Will the Pages plugin be able to use this to allow clients a little more control over content layout?

**Comment by AugmentBLU** [comment]
I can't seem to get the element name or description to work with my plugin lang file. I see it works for the fields label and and comment though. Any idea why? 

```
textarea:
    name: 'ablu.myplugin::lang.block.textarea' # not working
    description: plain text works # is working
    icon: icon-file-text-o
    fields:
        text_area:
            label: 'ablu.myplugin::lang.block.textarea' # is working
            commentAbove: 'ablu.myplugin::lang.block.textarea_desc' # is working
            label: Text Content
            type: textarea
            size: large
```

**Comment by LukeTowers** [comment]
@AugmentBLU does https://github.com/octobercms/october/commit/95cd3f70773072732d202c0c69c25c241a7a9936 fix it for you?

**Comment by AugmentBLU** [comment]
@LukeTowers  sure does, thanks for that!

**Comment by AugmentBLU** [comment]
I've noticed that if you use `type: fileupload` it duplicates the previous file uploaded when selecting another file block. I did only try it for images but I assume the same will happen for other file types.

Can we add anything to the following to ensure the file uploaded is some how distinct or is it a limitation? Or am I using the incorrect attach function?

```
public $attachOne = [
        'img_upload' => 'System\Models\File',
];
```

**Comment by LukeTowers** [comment]
File uploads are incompatible with repeaters, no way around that @AugmentBLU. It's the nature of how fileupload form widgets work, they store the information in a database relationship to the record, not to the specific repeater entry. If you want to use files in a repeater, you'll need to use the mediafinder widget instead.

**Comment by marcomessa** [comment]
Are groups compatible with TranslatableModel behavior? Because I'm testing this and getting errors / no record saved

**Comment by LukeTowers** [comment]
@marcomessa is this related to https://github.com/rainlab/translate-plugin/issues/290?

**Comment by marcomessa** [comment]
Exactly, I totally missed that, sorry! I just red this conversation and enthusiastically asked my question ;)

**Comment by carmeloMagna** [comment]
Hi there,

I have a question. Is possible to create groups of groups

I have on my layout this:
```
{repeater name="sections" groups="themes/basic-theme/meta/blocks.yaml"  tab="Componi la tua pagina" placement="secondary"}
    {variable name="_dummy" type="text" label="dummy"}{/variable}
{/repeater}
```

And on my blocks.yaml this:

```


commonboxes:
  name: commonboxes
  description: Add a orizontal section where you can put several contents
  icon: icon-cube
  fields:
    section_boxes:
      label: Boxes
      prompt: Add one, two or three blocks
      type: repeater
      groups:
        textbox:
          name: textbox
          icon: icon-file-text-o
          span: full
          description: text box
          fields:
            text:
              label: add a reach editor 
              type: richeditor
        imagebox:
          name: imagebox
          icon: icon-file-image-o
          description: Share with Twitter
          fields:
            image:
              label: Picture to show
              type: mediafinder
            caption:
              label: Picture caption
              type: text
```

On my page I have that, and it's correct

![pages _ octobercms](https://user-images.githubusercontent.com/11838160/39813709-c1615a7c-5391-11e8-99cf-a13728c21e8b.png)

But when I save and than reload I have not fields in the group.

The data stored in file are:

 ```
sections[2][section_boxes][1][text] = "<p>Lorem ipsum dolor sit amet	<br></p>"
sections[2][section_boxes][2][image] = "/dscf2178a1.jpg"
sections[2][section_boxes][2][caption] = "loremipus Caption"
sections[2][_group] = "commonboxes"
```

There is something I can do to let the things working?

Thank you all in advance!

Carmelo
