### ISSUE TITLE
Repeater htmlentities error

### ISSUE THREAD

**Issue by getrightnl** [octobercms/october#2781]
##### Expected behavior
I've nested some repeaters, so I expect it to have a json with a json inside. This works like expected and is saving data to the database. But the backend can't handle this or something.

##### Actual behavior
I get a htmlentities error when I save my nested repeater form

`"htmlentities() expects parameter 1 to be string, array given" on line 925 of /var/www/gi/modules/backend/Widgets/Lists.php`

My fields.yaml looks like this:

```
results:
            label: Resultaten
            prompt: 'Voeg nieuw resultaat toe'
            span: full
            type: repeater
            commentAbove: 'Voeg resultaten toe aan het icoon'
            tab: 'Tab 1'
            form:
                fields:
                    result_name:
                        label: 'Naam voor resultaat'
                        span: full
                        type: text
                        commentAbove: 'Geef een benaming voor het resultaat'
                    result:
                        label: Resultaat
                        prompt: 'Voeg nieuw resultaat toe'
                        span: full
                        type: repeater
                        commentAbove: 'Geef het resultaat die hoort bij de benaming'
                        form:
                            fields:
                                result_type:
                                    label: 'Het resultaat is een nummer'
                                    span: auto
                                    default: 1
                                    type: switch
                                    comment: 'Zet aan als het veld een nummer is'
                                result_value:
                                    label: Resultaat
                                    span: full
                                    trigger:
                                        action: hide
                                        field: result_type
                                        condition: unchecked
                                    type: number
                                    commentAbove: Resultaat
                                result_text:
                                    label: Resultaat
                                    span: full
                                    trigger:
                                        action: hide
                                        field: result_type
                                        condition: checked
                                    type: text
                                    commentAbove: 'Geef resultaat in'
                                text_after:
                                    label: 'Tekst na resultaat'
                                    span: full
                                    type: text
                                    commentAbove: 'Geef tekst in voor na het resultaat'
```

The result in the database looks like this:

```
{
  "1": {
    "result_name": "Facebook",
    "result": {
      "1": {
        "result_type": "1",
        "result_value": "1000",
        "result_text": "",
        "text_after": "likes"
      }
    }
  }
}
```

I also set this in my model 

```
 protected $jsonable = [
        'results'
    ];
```

##### Reproduce steps
Make a nested repeater. When you click save the data is stored except you get this error.

##### October build
Can't find it
