### ISSUE TITLE
Bug / Upgrade - Backend Navigation

### ISSUE THREAD

**Issue by ghost** [octobercms/october#2820]
Hi,

Firstly thanks to Daftspunk and Luke for all your hard work.

This is a small issue, but it has always annoyed me with October CMS.

![untitled](https://cloud.githubusercontent.com/assets/17784082/25016326/6e496d5a-2077-11e7-9ca5-d92fd97afec1.png)

I am not sure if it's because my monitor is touch screen or not?

But these arrows are tiny and should be increased in size and work with a mouse clicking on them. For me this does not work at all and I have to slide the navigation with my hand scrolling on the screen.

I'm lazy and want to click on them with my mouse and have them bigger please!

(Hopefully you may consider this issue)

Thanks.

**Comment by LukeTowers** [comment]
They're currently not meant to be clickable, only visual indicators that you can scroll the menu. I agree that the UX for them could probably be improved by making them clickable, but honestly you're probably better off when you have that many items in your menu to switch your navigation style to the expandable side menu instead.

**Comment by ayumihamsaki** [comment]
Hi Luke, Thanks for your reply. Tried changing in Settings with your suggestion, same kind of thing poor ux design. I would also say to update these three dots as well see picture:

![untitled](https://cloud.githubusercontent.com/assets/17784082/25020248/7d76d2aa-2085-11e7-9180-a30daccb07ef.png)

Probably better to have Up and Down Arrows that are clickable,...

**Comment by amdad** [comment]
You can use mouse wheel. Faster than clicks.

**Comment by ayumihamsaki** [comment]
@amdad you're right! The trouble is only mouse wheel works, clicking doesn't work at all.

My point being October should give both options and make these icons clickable. The first option scrolling along the top I rather have but right now doesn't do anything unless I run my finger across my touch screen and I rather not have fingerprints on a screen I am looking at 18 hours a day :(

**Comment by amdad** [comment]
Yea, But it's because clicking here is harder to be done. How fast/slow scroll on click should be. Smooth or jumping... This was designed to wheel or touch. Start using it and forget about those small bastards. They are only indicators scrolling in specific direction available.

**Comment by petehalverson** [comment]
We've opted to remove icons from the backend nav altogether which mitigates the issue a bit:

![screen shot 2017-04-18 at 12 01 02 pm](https://cloud.githubusercontent.com/assets/911099/25145856/645e62a8-242f-11e7-9f68-cd74b3eec076.png)

@LukeTowers, if you're open to some UI improvements we can take those on and submit some pull requests.

**Comment by LukeTowers** [comment]
If you'd like to work on some UI improvements, I'd suggest that you make issues as pre-pull requests in order to discuss the changes first. Apart from that I'm always open for improvements :)

**Comment by daftspunk** [comment]
You're supposed to click and drag the whole menu, the whole thing is draggable. Alternatively you can scroll it. I guess we could do all three? I have seen clients try to click those arrows on more than one occasion.

**Comment by LukeTowers** [comment]
@Teranode another UX issue for you :)

**Comment by ayumihamsaki** [comment]
@LukeTowers 

Please have a look at this github code I was playing about for the backend menu:

https://github.com/ayumihamsaki/oct-menu-bar

**Comment by ayumihamsaki** [comment]
Just going through my github issues.

Testing this today, there seems to be another issue with the top menu.

- Chrome - Can use the mouse wheel

- Firefox - Mouse wheel doesn't work

Haven't tested rest of the browsers.

**Comment by ayumihamsaki** [comment]
@LukeTowers @daftspunk 

Please decide whether you want to remove these pointless arrows, I can do the following.

Remove the following code:

## October.css File

```css
nav#layout-mainmenu .toolbar-item::after {
    right: -12px;
}
nav#layout-mainmenu .toolbar-item::before, nav#layout-mainmenu .toolbar-item::after {
    margin-top: 0;
}
nav#layout-mainmenu .toolbar-item::before {
    left: -12px;
}
nav#layout-mainmenu .toolbar-item::before, nav#layout-mainmenu .toolbar-item::after {
    margin-top: 0;
}
```

## Storm.css File

```css
.control-toolbar .toolbar-item.scroll-after::after {
    display: block;
}
.control-toolbar .toolbar-item::after {
    right: 6px;
}
.control-toolbar .toolbar-item::after {
    right: -8px;
    font-family: FontAwesome;
    font-weight: normal;
    font-style: normal;
    text-decoration: inherit;
    -webkit-font-smoothing: antialiased;
    *margin-right: .3em;
    content: "\f105";
}
.control-toolbar .toolbar-item::after, .control-toolbar .toolbar-item::before {
    display: none;
    position: absolute;
    top: 50%;
    margin-top: -7px;
    height: 9px;
    font-size: 10px;
    color: #bbb;
}
.control-toolbar .toolbar-item.scroll-before::before {
    display: block;
}
.control-toolbar .toolbar-item::before {
    left: -10px;
}
.control-toolbar .toolbar-item::before {
    left: -6px;
    font-family: FontAwesome;
    font-weight: normal;
    font-style: normal;
    text-decoration: inherit;
    -webkit-font-smoothing: antialiased;
    *margin-right: .3em;
    content: "\f104";
}
```
