### ISSUE TITLE
Trigger condition from checkbox list field type

### ISSUE THREAD

**Issue by neilcarpenter1** [octobercms/october#2861]
I can't find any other issues relating to this, so forgive me if this has been raised before.
I was wondering if it's possible to compare a trigger condition to selected values on a checkboxlist field type?

```
roles:
    label: Roles
    type: checkboxlist
    options:
      teacher: Teacher
      governer: Governer

class:
      label: Class
      type: dropdown
      options:
        one: Class one
        two: Class two
      trigger:
        action: show
        field: roles
        condition: value[teacher]
```

**Comment by LukeTowers** [comment]
It should be in theory. Are you saying that it isn't possible in practice?

**Comment by neilcarpenter1** [comment]
It's not working for me no

**Comment by daftspunk** [comment]
This is a complex case. Please submit a Pull Request to the [test plugin for investigation](https://github.com/daftspunk/oc-test-plugin) that demonstrates the issue. Don't forget to include step by step instructions how how to replicate it *using the test plugin*.

**Comment by LukeTowers** [comment]
@neilcarpenter1 @jimcottrell could either of you make a PR to fix this bug?

**Comment by jimcottrell** [comment]
I'll take a look.

**Comment by daftspunk** [comment]
Thanks all who contributed to the research here.

This is solved with the following:

```
roles:
    label: Roles
    type: checkboxlist
    options:
      teacher: Teacher
      governer: Governer

class:
      label: Class
      type: dropdown
      options:
        one: Class one
        two: Class two
      trigger:
        action: show
        field: roles[]
        condition: value[teacher]
```

Note the diff:

```
        field: roles[]
```

Available in Build 435+.
