### ISSUE TITLE
Backend list relation column

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#2873]
##### Expected behavior
Use 'relation' and 'select' to select child attribute value and display the value in the backend list of parent.

##### Actual behavior
Returns completely empty backend list. Parents attributes are not visible. No records found.

##### Reproduce steps
 - Create "Product" and "Description" model. Products primary key is 'products_id' and Descriptions primary key is 'products_id'. 
 - The relationship from product to description is hasOne. 
 - Show the 'products_name' column from Description model on the Products backend list.

columns.yaml from Product model looks like this. 

```
columns:
    products_model:
        label: Productnummer
        type: text
        searchable: true
        sortable: true
    rel_descriptions:
        label: Naam
        type: text
        searchable: true
        sortable: true
        relation: descriptions
        select: products_name
```
Products relation definition looks like this:

```
public $hasOne = [
        'descriptions' => [
            'Codecycler\Warehouse\Models\Description',
            'key' => 'products_id',
            'otherKey' => 'products_id',
            'conditions' => 'language_id = "2"',
        ],
    ];
```

Result is empty list. But if I remove the rel_descriptions field from the columns.yaml, the list is back and filled with the products_model values of Product model. When you change:
```
select: products_name
```
to: 
```
select:
```

The list is back and populated with the products_model values. So I think everything works well except selecting the models attribute. 

##### October build
419

**Comment by LukeTowers** [comment]
Why is your `key` and `otherKey` both `products_id`? http://octobercms.com/docs/database/relations#one-to-one.

**Comment by SebastiaanKloos** [comment]
I needed to attach my application to a zencart database. Unfortunately this is not as clean as OctoberCMS. I can confirm that both primary keys of the models are products_id.

**Comment by LukeTowers** [comment]
what happens if you set `rel_descriptions` to `products_id`?

**Comment by SebastiaanKloos** [comment]
@LukeTowers haven't tried that yet. Will try this. I'll keep you updated. Thanks for the quick reply!

**Comment by SebastiaanKloos** [comment]
@LukeTowers this does not solve my problem

**Comment by SebastiaanKloos** [comment]
@LukeTowers If I change the columns.yaml to this:

```
columns:
    products_model:
        label: Productnummer
        type: text
        searchable: true
        sortable: true
    descriptions[products_name]:
        label: Naam
        type: text
        searchable: true
        sortable: true
```
Everything works fine. Except the searchable and sortable not working. So filtering and sorting the table on descriptions[products_name] is not working.
