### ISSUE TITLE
Unable to override list partials for relation lists

### ISSUE THREAD

**Issue by priitperna** [octobercms/october#2889]
##### Expected behavior
When I add `customViewPath` to the related list configuration the overriden partials should be loaded.

##### Actual behavior
`customViewPath` attribute is not read by the `RelationController` and therefore the partials are not loaded

##### Reproduce steps
Create a custom folder for partials and add the `customViewPath` attribute to the relation configuration.

```
articles:
    label: Articles
    view:
        list: $/acme/shop/models/article/pivot_columns.yaml
        toolbarButtons: add|remove
        customViewPath: $/acme/shop/controllers/articles/list
```

##### October build
419

**Comment by vakopian** [comment]
I would love for this to work as well, even if it turns out not to be a bug (since the documentation for relations does not really mention `customViewPath`)

**Comment by SaifurRahmanMohsin** [comment]
Is there a workaround for now? For example, would it be possible to define one of the relation extension methods and manipulate the relation config to specify the partial path for a custom toolbar button.

For example, I'm using:
```
# ===================================
#  Relation Behavior Config
# ===================================
contracts:
    label: Contracts
    view:
        list: $/mohsin/acme/models/contract/columns.yaml
        toolbarButtons: renew
```

And OctoberCMS throws me a `The partial '_button_renew.htm' is not found.`. I tried creating the file in the contract model folder but that didn't work. There's no controller folder since it's an internal model. However, I tried scaffolding and created the partial to test it, but in vain. Is there a temporary workaround for this?

**Comment by LukeTowers** [comment]
@SaifurRahmanMohsin put partials for the relation controller behavior in the controller folder where it is being rendered. I.e., if you are rendering your `contracts` relation in your `Jobs` controller, then put your partial in your `jobs` controller folder. That, or you can just specify a full path to the desired partial using `~` for the application root or `$` for the plugins root. Example: 
```
toolbarButtons: $/myauthor/myplugin/partials/btn.renew.htm
```

**Comment by SaifurRahmanMohsin** [comment]
The first method didn't work at all. I tried putting a `_button_renew.htm` in the jobs folder, then I also tried creating a folder called contracts (since that's the name of the relation) and moved the partial inside that as well and it still didn't pick up.

The second method, returned an error: 'The partial 'button_$/mohsin/acme/partials/_btn.renew.htm' is not found.`. I think it prepends button_ and that's why the issue occurs.

**Comment by LukeTowers** [comment]
Ah, right I remember now. @SaifurRahmanMohsin you need to use `toolbarPartial:` instead and render the entire toolbar yourself if you need a custom toolbar.

**Comment by SaifurRahmanMohsin** [comment]
Yes, that worked. Thank you.

**Comment by SaifurRahmanMohsin** [comment]
If you add an option to set a customViewPath to the relation config then you still would need to re-define all the existing relationController elements i.e. create, delete, etc. if you want to use those in your project. This means that developers would have to copy paste the button html files from `modules/backend/behaviors/relationcontroller/partials` to re-create the buttons. I think it would be better for OctoberCMS to have a provision by which the relation controller's folder is also searched so that the button rendering code checks both the paths to resolve which path to use i.e. for create, delete, etc.

This way it would use `modules/backend/behaviors/relationcontroller/partials` folder for the usual suspects i.e. create, delete, remove, etc. but for some custom user-defined one like 'mybutton' it will search plugins/authorname/acme/plugin/controller/myRelationController folder. I see that there is a relationMakePartial function in the RelationController which is responsible for calling the renderPartial code so I think it should be possible to use the $params variable to pass an extra path to search?

**Comment by SaifurRahmanMohsin** [comment]
Ah ok... I didn't notice that @LukeTowers . I realize now that you can simply add a custom user-defined button like **predict** and create a _relation_button_predict.htm and it takes the view automatically even without setting customViewPath in the config. The OctoberCMS documentation should probably have this information since it was confusing to figure out. Even the error message said _button_predict missing so one wouldn't be able to easily figure out on their own that it needs to be written as **_relation**_viewName.htm

**Comment by LukeTowers** [comment]
@SaifurRahmanMohsin make the desired improvements to the documentation and I'd be happy to review it!

**Comment by netsmertia** [comment]
I think the whole discussion was moved to another direction. 
I also using the great octobercms to build my application and need to add a `Total` row at the end of `lists` inside a relation.
I have following setup to show order items inside a order form (update.htm) using `relationController`

```
orderItems:
  label: Order Items
  view:
    customViewPath: $/pitaro/pitaro/controllers/order/order_item_list
    list: $/pitaro/pitaro/models/orderitem/columns.yam
```
The lists is not using the partials at `order_item_list` folder. Also I don't have controller for `OrderItem`.
How should I update the layout and partials of lists inside a relation.
