### ISSUE TITLE
Selectable Repeater error when using taglist

### ISSUE THREAD

**Issue by jrnski** [octobercms/october#2933]
##### Expected behavior
After filling out the taglist, the form should save und able to be loaded again.

##### Actual behavior
Saving seems to work, and page looks good. Only when selecting the record from the list again i get this error:

explode() expects parameter 2 to be string, array given
xxx/FormWidgets/TagList.php line 143

##### Reproduce steps
Use a model, create a field 'content_modules', make it jsonable and enter into fields.yaml:

```
        content_modules:
            tab: Content
            label: Content
            prompt: 'Add content block'
            span: full
            type: repeater
            groups: $/acme/xxx/config/repeater_fields_xxx.yaml
            form: {  }

```

repeater_fields_xxx.yaml:

```
demands:
    name: searches for
    description: searches for
    icon: icon-quote-right
    fields:
        urgent:
            label: Urgent
            span: auto
            type: taglist
        normal:
            label: normal
            span: auto
            type: taglist
offers:
    name: offers
    description: offers
    icon: icon-quote-right
    fields:
        highlights:
            label: Highlights
            span: auto
            type: taglist
        normal:
            label: normal
            span: auto
            type: taglist
```

Enter some data, save, go back to record list and chose record again. The error should occur.

##### October build
Using composer, where can i find the build number? ;)
