### ISSUE TITLE
Repeater Index

### ISSUE THREAD

**Issue by shoguniphicus** [octobercms/october#2986]
##### Expected behavior
Repeater's index should be the same whether it's record derived from database or from click "+".

##### Actual behavior
If there is already record on any repeater item, the _repeater_index always start with 0. However, if user click "+" to add a new repeater item on an empty list, the _repeat_index always start with 1.

##### Reproduce steps
Click on "+" on any repeater type form field, and check out the _repeater_index, it's always starting with 1. 

This might not be an issue for most that don't build custom javascript code for backend. But it's inconsistent that the index is different each time.

Right now, I changed the formwidget file at /modules/backend/formwidgets/Repeater.php at line 56, change to -1 and it's behaving as expected.

##### October build
419

**Comment by LukeTowers** [comment]
Closing as it has been over a month since any activity on this occurred.

If you'd still like this fixed @shoguniphicus please make a PR with a fix.

**Comment by mohsin** [comment]
@LukeTowers Is there any provision by which I can specify the label to show the line number in a repeater field?

```
lines:
   label: Line
   type: repeater
   style: accordion
   maxItems: 3
   form:
       fields:
           line:
               label: Line :index
```
