### ISSUE TITLE
nameFrom concatenate on TagList is not working

### ISSUE THREAD

**Issue by Damienov** [octobercms/october#3000]
##### Expected behavior
`nameFrom: concat(name, ' ', last_name)`
on fields.yaml should concatenate the first_name and last_name.
`type: taglist
        label: Clients
        span: full
        customTags: false
        mode: relation
        nameFrom: concat(name, ' ', last_name)`
related commit:
https://github.com/octoberrain/backend/commit/9417d7e5f47fcfeab7cd8b17c78b68da129cb222

##### Actual behavior
throws an error:

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'concat(name, ' ', last_name)' in 'field list'

##### Reproduce steps
(Describe the steps to reproduce the problem here)

##### October build
419

**Comment by LukeTowers** [comment]
Try this instead:
```yaml:
clients:
    type: taglist
    label: Clients
    span: full
    customTags: false
    mode: relation
    sqlSelect: concat(name, ' ', 'last_name')
```

(**sqlSelect** instead of **nameFrom**)
