### ISSUE TITLE
New input filter for backend list

### ISSUE THREAD

**Issue by pvullioud** [octobercms/october#3048]
##### Expected behavior
Create an input filter to search into one or more fields. This could be used in plenty of situation (name, lastname, cutomer id, invoice id..)
![dhu3zstxoaac6ul](https://user-images.githubusercontent.com/3446410/29519085-51eebd70-867c-11e7-82ef-8db04b28fd15.jpg)

##### Actual behavior
If I search the id "18" and I have a date column with "18 jan 2017" global search will return both (see picture).

**Comment by ChVuagniaux** [comment]
Nice idea

Something like that can be very usefull
```yaml
    id:
        label: "ID"
        type: input
        conditions: id = :value 
        size: 10
```
