### ISSUE TITLE
backend List - Switch column doesn't show right value

### ISSUE THREAD

**Issue by pat-och** [octobercms/october#3079]
##### Expected behavior
having yes or no value based on field boolean value (0 = yes and 1 = no)

##### Actual behavior
display 'no' even if boolean value is 1

##### Reproduce steps
columns yaml (code generated with builder)

```
    Visible:
        label: Visible
        type: switch
```

##### October build
419

I had to add the valueFrom line to make it work as intended
```
    Visible:
        label: Visible
        type: switch
        valueFrom: visible
```

If this is the intended behavior, i suggest to update builder to implements it and improve [switch column documentation](https://octobercms.com/docs/backend/lists#column-switch)
Else just fixed it

thanks for attention
