### ISSUE TITLE
Change of richeditor z-index broke popup-ovelay

### ISSUE THREAD

**Issue by Fl0Cri** [octobercms/october#3111]
Changing the z-index of the richeditor in https://github.com/octobercms/october/pull/3099 caused a side effect with popover-overlay when the richeditor is not inside a popup, like in static pages plugin when using a page snippet.

##### Expected behavior
The following capture shows the behaviour of a static page snippet before changing the richeditor's z-index (like in build 422).
![backend_expected](https://user-images.githubusercontent.com/16371551/30417236-516cb1de-992f-11e7-8075-21f913052733.png)

##### Actual behavior
Currently (build 423), the richeditor's z-index is higher than both `.popover-overlay` (597) and `.control-popover` (599):
![backend_actual](https://user-images.githubusercontent.com/16371551/30417308-8ade5c9c-992f-11e7-87ff-1795788cc8c9.png)

##### Reproduce steps
1. From a clean install, install the static pages plugin.
1. Create a partial that will be usable as a snippet:
```
[viewBag]
snippetCode = "testSnippet"
snippetName = "Test"
snippetProperties[titleText][title] = "Test"
snippetProperties[titleText][type] = "string"
snippetProperties[titleText][default] = ""
snippetProperties[titleText][options][] = ""
==
<span>{{ titleText }}</span>
```
3. Create a new static page
3. Include the snippet in the page and try clicking on it to show the edition popup.

##### October build
since 423

##### Workaround
I managed to fix it in my case by putting the following css in my backend styles, but it's kind of a z-index war and I don't know what side-effects it could cause in other situations.
```CSS
div.popover-overlay {
    z-index: 1001;
}
div.control-popover {
    z-index: 1002;
}
/* Fix user settings menu */
nav#layout-mainmenu ul li .mainmenu-accountmenu {
    z-index: 1002;
}
```

**Comment by LukeTowers** [comment]
Could you please look into reverting the PR that made the issue and the fixing the original issue with CSS instead?

**Comment by datune** [comment]
@Fl0Cri 1. Thanks for a supreme example of how to submit a bug report, chapeau! 2. It is indeed a z-index war, since the layout-side-panel is also affected when unpinned, it's z-index is 600.

So to append your workaround for the time being I've added:
```css
body.display-side-panel #layout-side-panel {
    z-index: 1001;
}
```
