### ISSUE TITLE
emptyOption for controller filters

### ISSUE THREAD

**Issue by Hambern** [octobercms/october#3116]
##### Expected behavior
Just like I can add an emptyOption to fields in the backend forms i would like to be able to filter the fields with an emptyOption as well. Like this:

```
status:
        label: acme.plugin::lang.string.status
        modelClass: Acme\Plugin\Models\Status
        conditions: status_id in (:filtered)
        emptyOption: acme.plugin::lang.string.none
```

##### Actual behavior
No empty option shows up

##### Reproduce steps
1. Add an emptyOption string to a filter
1. See the result

##### October build
423

**Comment by LukeTowers** [comment]
Mind explaining a bit more how this would work?

**Comment by Hambern** [comment]
Not at all. Like this:

Lets say I have a `status_id` column in the database. It could either be an integer or NULL (or 0). Ant that relates to another table's id number.

Then Lets say the relation looks like this  Stuff –> belongsTo -> Status.

This can be done as a field in the backend like this:

```
status:
        label: 'maker.plugin::lang.string.status'
        type: relation
        emptyOption: 'maker.plugin::lang.string.none'
```

Now I want to be able to filter the list based on this. Including the Stuff with status_id NULL or 0. And preferably like this:

```
status:
        type: group
        label: 'maker.plugin::lang.string.status'
        modelClass: Maker\Plugin\Models\Status
        conditions: status_id in (:filtered)
        emptyOption: 'maker.plugin::lang.string.none'
```

Than I want it to list the Statuses like it does right now, but add an emptyOption that adds the string maker.plugin::lang.string.none to the list and adds null (or 0) to the `(:filtered)`. Look at it as the inversion of the field.

How to this technically I have no idea ;) Explained my self enough?
