### ISSUE TITLE
Add support for 'select' property in list filters

### ISSUE THREAD

**Issue by roulendz** [octobercms/october#3158]
##### Expected behavior
I can not figure out how to concatenate name and surname for list view filter.
[I saw some issues that this was fixed, but maybe it was something else.](https://github.com/octobercms/october/pull/1579)

Thanks in advance!
```
manager:
        label: Filter by Manager
         modelClass: RainLab\User\Models\User
        conditions: manager_id in (:filtered)
        nameFrom: CONCAT(first_name, ' ',last_name)
        # nameFrom: CONCAT(first_name, last_name)
        # nameFrom: CONCAT(first_name || ' ' || last_name)
        # nameFrom: CONCAT(first_name || ' ' || last_name)
        # nameFrom: concat_ws(' ', first_name , last_name)
```

##### Actual behavior
I want it to concatenate name and surname for list view filter.
I am using PostgreseSQL
##### October build
419

**Comment by LukeTowers** [comment]
The nameFrom and select options are not supported in list filters. http://octobercms.com/docs/backend/lists#list-filters

The support demand for October is increasing, while the available time the founders have to give remains the same. These issues will be handled in time, however there are ways you can help:

- Submit a pull request that introduces this feature and wait for it to be reviewed
- [Make a financial contribution to the project](http://octobercms.com/fundraising) so we can allocate more time towards making improvements like these that benefit everyone

**Comment by geoffbeaumont** [comment]
According to the documentation page you linked to:
http://octobercms.com/docs/backend/lists#list-filters

nameFrom is supported (first example filter scope) - though it only shows it with a single field name, not concatenating.

**Comment by LukeTowers** [comment]
http://octobercms.com/docs/backend/lists#filter-scope-options

You're right, nameFrom is supported, but not in the way that you are trying to use it.

**Comment by riartem** [comment]
@roulendz 
### For future readers
**(Checked in October 437 and fully works solution)**
To solve that case we need to define the [Accessor](http://octobercms.com/docs/database/mutators#accessors-and-mutators) in the model class.

```php
// In Plugin.php
public function boot()
{
    UserModel::extend(function($model) {
         $model->addDynamicMethod('getFullNameAttribute', function ($value) use ($model) {
             if($model) {
                 return $model->name . ' ' . $model->surname;
             } else { return ''; }
    });
}
```

// And in the config_filter.yaml we call new "virtual field"
```yaml
manager:
     label: Filter by Manager
     modelClass: RainLab\User\Models\User
     conditions: manager_id in (:filtered)
     nameFrom: full_name
```
