### ISSUE TITLE
Show / Hide tabs with fields

### ISSUE THREAD

**Issue by Asinox** [octobercms/october#3239]
Hello guys, i would like to know if there is a way to show/ hide tabs like with hide/show fields in backend, using a trigger or condition?

Thanks!

**Comment by jan-vince** [comment]
I don't know about any such feature but when you hide all fields on the tab also this tab itself is hidden.

**Comment by Asinox** [comment]
@jan-vince i tried, you can hide all fields, but the tab is alway there, with or without fields...

**Comment by jan-vince** [comment]
@Asinox 

I have used this in some of my plugins and it works.

*I usually hide a field (and so tab) before a record actually exists (= is created).*

My fields.yaml is like this:

````
        tags:
            label: Tags
            type: relation
            tab: Tags
            trigger:
                action: hide
                field: id
                condition: value[]
````

Unless there is value in field ID, tab ````Tags```` is hidden.

----

You can [check source code](https://github.com/jan-vince/smallrecords) or test by [installing it](https://octobercms.com/plugin/janvince-smallrecords).

**Comment by Asinox** [comment]
@jan-vince i think i need to be a bit clear here.
I just need the **tab** visible when im updating, sure, im using the context parameter, that is fine, but based on my **trigger** and **condition value[]**, the **tab** is always visible, don't matter if **value[]** is there or not, the **tab** just hide the fields inside it, but the tab itself is there.

For example:
```
vehicle:
      label: Information
      type: partial
      path: field_vehicle
      tab: Extra Info
      context: update
      trigger:
        action: show
        field: category_id
        condition: value[2]
```
Dont matter if **condition value[]** is there or not, the **tab** is always **visible**, and i want to start the form with the tab hidden and them show it if condition value is there.

I tried a few things and nothing.

I think there is not a option for this.
