### ISSUE TITLE
Boolean fields are interpreted wrongly in the fields.yaml

### ISSUE THREAD

**Issue by mohib0306** [octobercms/october#3293]
Hi;

I have a nullable boolean field (my_field) in my table. I used the following configurations in the fields.yaml file of the corresponding model.
```
    my_field:
        label: My Field
        type: radio
        options:
             1: 'Yes'
             0: 'No'
```
or
```
    my_field:
        label: My Field
        type: radio
        options:
             true: 'Yes'
             false: 'No'
```

The expected behavior is that if the field is `false` in the table, then `No` should be selected. And in case of `Null` none of the two options should be selected. But this does not happen and either of the above configurations the `No` is not selected.

I looked into the `/modules/backend/widgets/form/partials/_field_radio.htm` and on Line 22 it is calling `ìsSelected()` function, which evaluates the `false` value to `empty string` in its `return (string) $value === (string) $this->value;`

I changed the Line 22 in `/modules/backend/widgets/form/partials/_field_radio.htm` to `<?= (int) $field->value === $value ? 'checked="checked"' : '' ?>` and it works.

"name": "october/backend",
            "version": "v1.0.428",
