### ISSUE TITLE
Set dropdown emptyOption value

### ISSUE THREAD

**Issue by HekmatFavid** [octobercms/october#3340]
I have dropdown with following fields.yaml 
```
    material:
        label: materials
        oc.commentPosition: ''
        nameFrom: title
        descriptionFrom: description
        span: auto
        required: 1
        emptyOption: 'none'
        type: relation
```
in my product table has material_id corresponding material dropdown.
when material_id field defined Nullable in database and user dosent select any option and default option is 'none' Null value save in my database.
i want save 0 instead of null. is solution for define emptyValue like property in fileds ?
