### ISSUE TITLE
Backend Form Update Issue

### ISSUE THREAD

**Issue by ibanks** [octobercms/october#3381]
##### Expected behavior
On the backend, when using the built in FormController to build a custom slider plugin that uses the widget's create, update, and preview controller views, I expect when saving the slider to be updated, using the update view along with the example for the update.htm file provided in the OctoberCMS docs, that the slider and any updated content is saved successfully.

##### Actual behavior
What is happening is that it's asking me to upload an image each time when the image is already there. This is coming from the onSave method in the FormController. I do not understand why it is looking for an image on the update page when it is already there.

##### Reproduce steps
I'm using the native example provided in the Backend -> Forms section of the docs. I copied the code for the create, update, and preview files. On the update page, its clearly referencing the newly created model record with the id at the end of the url.

##### October build
Version: 431

**Comment by LukeTowers** [comment]
Post your code for the view (`update.htm`), your controller class, your config_form.yaml, your fields.yaml, and your model class. Make sure to enclose it properly in three backticks at the start and end of each file to indicate that it is code. @ibanks

**Comment by ibanks** [comment]
Thanks for assisting.

**update.htm**

```
<?php

    $protocol = 'http://';
    $serverName = request()->server('SERVER_NAME');
    $createSliderAddress = '/backend/kamby/slider/create';
    $sliderID = request()->segment(6);

?>

<?= Form::open(['class'=>'layout']) ?>

    <div class="layout-row">
        <?= $this->formRender() ?>
    </div>

    <div class="form-buttons">
        <div class="loading-indicator-container">
            <button
                type="button"
                data-request="onSave"
                data-request-data="close:true"
                data-hotkey="ctrl+enter, cmd+enter"
                data-load-indicator="Saving Category..."
                class="btn btn-default">
                Save Updates
            </button>
            <span class="btn-text">
                or <a href="<?= $protocol . $serverName . $createSliderAddress . '/preview/' . $sliderID ?>">Cancel</a>
            </span>
        </div>
    </div>

<?= Form::close() ?>
```
**Controller**
```
<?php

namespace Kamby\Slider\Controllers;

use BackendMenu;
use Input;

class Create extends \Backend\Classes\Controller
{

    public $implement = ['Backend.Behaviors.FormController'];

    public $formConfig = 'form_config.yaml';

    public function __construct()
    {
        parent::__construct();

        BackendMenu::setContext('Kamby.Slider', 'slider', 'create');
    }

    /**
     * Publishes a slider by marking it active.
     *
     */
    public function onPublish() {}

    /**
     * Marks a slider as pending. (The slider is technically created after the onSave method
     * is first called on the create.htm page. This will mark the current slider as pending
     * which will show up on a list of sliders to be published later.)
     *
     */
    public function onMarkPending() {}

    /**
     * Updates the current slider.
     *
     */
    public function onUpdate()
    {
        $sliderID = Input::get('sliderid');
        return $this->update_onSave($sliderID, 'update');
    }

}

```
**form_config.yaml**
```
# ===================================
#  Form Behavior Config
# ===================================

name: Slider Category
form: $/kamby/slider/models/sliders/fields.yaml
modelClass: Kamby\Slider\Models\Sliders

create:
    title: Slider Upload
    redirect: kamby/slider/create/preview/:id

update:
    title: Update Sliders
    redirect: kamby/slider/create/preview/:id
    flashSave: Your slider has been updated successfully!
    flashDelete: The slider has been deleted.

preview:
  title: View Slider
```

**fields.yaml**

```
# ===================================
#  Form Field Definitions
# ===================================

fields:
    slidername:
        label: Slider Name
        description: The name of your new slider
        type: text
        size: large
        placeholder: Enter Slider Name
        commentAbove: This is just way to identify your new slider entry

    image:
        label: Upload Image
        description: Your slider image file
        type: fileupload
        mode: image
        mimeTypes: jpeg,gif,png
        prompt: Upload image
        commentAbove: Your slider image needs to be no smaller than 1920 (width) x 1280 (height) pixels

    primarytext:
        label: Primary Text
        description: The slider image leading (larger) text
        type: text
        size: large
        placeholder: Enter leading text
        commentAbove: This is the leading text on your new homepage slider

    secondarytext:
        label: Secondary Text
        description: The slider image secondary (smaller) text
        type: text
        size: large
        placeholder: Enter secondary text
        commentAbove: This is the sub-text that will appear underneath the primary text on your new homepage slider

    buttontext:
        label: Link Text
        description: The slider image link text
        type: text
        size: small
        placeholder: Enter link text
        commentAbove: This is the button text on your new home page slider. Make sure to keep your message to a 2-3 word minimum here
```
