### ISSUE TITLE
Backend list column sorting of jsonable element

### ISSUE THREAD

**Issue by ghost** [octobercms/october#3388]
Hello,

I noticed something strange when you work with backend list with sortable json column.

let's assume you have a "customer" json field like that

    {
        firstname: 'John',
        lastname: 'Doe'
    }

In your column.yaml you want to output the firstname and lastname in separate columns.

    customer[firstname]:
        label: Firstname
        type: text
        searchable: true
        sortable: true
    customer[lastname]:
        label: Lastname
        type: text
        searchable: true
        sortable: true

It will works, but the columns are not sortable, even with "sortable" set to "true".

But if I do something like that : 

    first_name:
        label: Firstname
        type: partial
        searchable: true
        sortable: true
        path: first_name

And in my partial _first_name.htm

    <?= json_decode($record->attributes['customer'])->firstname; ?>

My column will be sortable.

The bracket syntax in columns.yaml seems to be the cause of the problem. When you use another name without brackets and manually display the value using partial, it perfectly works.

**Comment by EdisonLV** [comment]
if the column type for **customer** in your MySQL is set to JSON, than this should work:
```
    first_name:
        label: Firstname
        type: text
        searchable: true
        sortable: true
        select: 'customer->"$. firstname"'
    last_name:
        label: Lastname
        type: text
        searchable: true
        sortable: true
        select: 'customer->"$. lastname"'
```
