### ISSUE TITLE
Issue with fileUploader in a model saved through RelationController behavior

### ISSUE THREAD

**Issue by marcomessa** [octobercms/october#3390]
##### Scenario
I have a Product model with RelationController behavior, which $belongsTo Blueprint model. I need to create a Blueprint from inside Product form, using backend relationships. The Blueprint model has $attachOne and $attachMany fields. I'm in Product create action ( onRelationManageCreate() )

##### Expected behavior
I expect to be able to correctly set and save both $attachOne and $attachMany Blueprint's value, from Product form.

##### Actual behavior
The Blueprint model is correctly saved, but both $attachOne and $attachMany aren't.

##### October build
431

##### Notes
During Product's update action ( onRelationManageUpdate() ), when updating its Blueprint, both attachment are correctly saved.
Is I create Blueprint from it's "normal" form (backend/author/products/blueprints/create) everything is okay, both on create and update action.
Attachments' relations are called thumbnail and gallery. In Blueprint model, i tried to dump, on before save, $this->thumbnail and $this->gallery, and it always return null

**Comment by LukeTowers** [comment]
Sounds like somethings going wrong with your deferred binding on the create. Are you able to dig deeper and see if you can find the issue?

**Comment by marcomessa** [comment]
Sure! I'm inspetting onRelationManageCreate() call with xDebug and i can tell that:

1) deferredBinding is set tu true
2) view mode is single
3) my attachments fields in $saveData are set to -1 - maybe this is the issue? Maybe not, because the same happens when inspecting onRelationManageUpdate()

Just to check if I made some king of implementing error, here are my steps:

- in Products controller I enabled the behavior
` public $implement = [
        'Backend.Behaviors.FormController',
        'Backend.Behaviors.ListController',
        'Backend.Behaviors.RelationController',
    ];`
- I set my relation config yaml
`public $relationConfig = 'config_relation.yaml';`
- Then I configure my relation
```yaml
blueprint:
  label: Scheda prodotto
  view:
    form: $/up/products/models/blueprint/fields.yaml
    toolbarButtons: create|update
  manage:
    form: $/up/products/models/blueprint/fields.yaml
    list: $/up/products/models/blueprint/columns.yaml
```
- and in my model field.yaml I add the reference to the partial
```yaml
blueprint:
      label: Scheda prodotto
      comment: Aggiungi la scheda prodotto
      type: partial
      path: field_blueprint
      tab: Scheda Prodotto
```
- and, lastly, my partial
`<?= $this->relationRender('blueprint') ?>`

I think that's all, now here it's getting late, tomorrow I'll continue debugging and checking
