### ISSUE TITLE
Saved settings are not appearing in custom plugin

### ISSUE THREAD

**Issue by tylerssn** [octobercms/october#3398]
##### Expected behavior
Plugin settings' field values should populate with saved setting values

##### Actual behavior
settings are saved to DB but do not populate the backend settings form

##### Reproduce steps
1. system_settings table is empty
2. Save new backend settings for plugin using  admin UI (URI: `backend/system/settings/update/[vendor]/[namespace]`
3. system_settings table is no longer empty(item:`etre_addresssweet_settings`, value: json object
4. Refreshing admin settings form displays values.
5. Click save, refresh -- settings no longer appear and the JSON object in the DB has empty values

##### October build
Fresh install

Additional info:

```php
# plugin.php
    public function registerSettings()
    {
        return [
            'address-sweet' => [
                'label' => 'etre.addresssweet::lang.settings.menu_label',
                'description' => 'etre.addresssweet::lang.settings.menu_description',
                'category' => SettingsManager::CATEGORY_ADDRESS_SWEET,
                'icon' => 'icon-cog',
                'class' => 'Etre\AddressSweet\Models\Settings',
                'order' => 500,
                'permissions' => ['etre.addresssweet.settings.modify'],
                'keywords' => 'address fedex api sandbox'
            ]
        ];
    }
```

```php
# models/Settings.php

namespace Etre\AddressSweet\Models;

use Etre\AddressSweet\Helpers\SettingsManager;
use Lang;
use Model;
use RainLab\User\Models\User as UserModel;

class Settings extends Model
{
    /**
     * @var array Behaviors implemented by this model.
     */
    public $implement = [
        \System\Behaviors\SettingsModel::class
    ];

    /** @var 'etre_addresssweet_settings' $settingsCode */
    public $settingsCode = SettingsManager::SETTINGS_CODE;

    public $settingsFields = 'fields.yaml';


}
```

```yml
# models/settings/fields.yaml
fields:
  is_sandbox:
      label: Sandbox Mode
      tab: etre.addresssweet::lang.settings.tab_api_label
      type: balloon-selector
      default: 1
      options:
          0: No
          1: Yes
tabs:
  fields:
    # Production API Tab
    fedex_key:
        label: FedEx Key
        tab: etre.addresssweet::lang.settings.tab_api_label
        type: password
    fedex_password:
        label: FedEx Password
        tab: etre.addresssweet::lang.settings.tab_api_label
        type: password
    fedex_account_number:
        label: FedEx Account Number
        tab: etre.addresssweet::lang.settings.tab_api_label
        type: password
    fedex_meter_number:
        label: FedEx Meter Number
        tab: etre.addresssweet::lang.settings.tab_api_label
        type: password
    fedex_hub_id:
        label: FedEx Hub ID
        tab: etre.addresssweet::lang.settings.tab_api_label
        type: password
    fedex_server:
        label: FedEx Server
        tab: etre.addresssweet::lang.settings.tab_api_label
        type: text
        default: ws.fedex.com

    # Sandbox API Tab
    sandbox_fedex_key:
        label: Sandbox FedEx Key
        tab: etre.addresssweet::lang.settings.tab_sandbox_api_label
        type: password
    sandbox_fedex_password:
        label: Sandbox FedEx Password
        tab: etre.addresssweet::lang.settings.tab_sandbox_api_label
        type: password
    sandbox_fedex_account_number:
        label: Sandbox FedEx Account Number
        tab: etre.addresssweet::lang.settings.tab_sandbox_api_label
        type: password
    sandbox_fedex_meter_number:
        label: Sandbox FedEx Meter Number
        tab: etre.addresssweet::lang.settings.tab_sandbox_api_label
        type: password
    sandbox_fedex_hub_id:
        label: Sandbox FedEx Hub ID
        tab: etre.addresssweet::lang.settings.tab_sandbox_api_label
        type: password
    sandbox_fedex_server:
        label: Sandbox FedEx Server
        tab: etre.addresssweet::lang.settings.tab_sandbox_api_label
        type: text
        default: wsbeta.fedex.com
```
