### ISSUE TITLE
DateTime picker in mode:time stores DATE and TIME I need just TIME to be stored

### ISSUE THREAD

**Issue by roulendz** [octobercms/october#3439]
##### Expected behavior
Using repeater for storing in JSON day of the week and working hours.

Somehow saves not just hours/time but also date.
```
businessHours:
            label: 'Classroom working days and hours'
            prompt: 'Add new item'
            span: left
            type: repeater
            tab: 'Classroom working hours'
            form:
                fields:
                    dow:
                        label: Dropdown
                        options:
                            - Sunday
                            - Monday
                            - Thursday
                            - Wednesday
                            - Thursday
                            - Friday
                            - Saturday
                        span: left
                        default: '1'
                        emptyOption: '--'
                        type: dropdown
                    start:
                        label: 'Start time'
                        mode: time
                        span: left
                        default: '10:00'
                        type: datepicker
                    end:
                        label: 'End time'
                        type: datepicker
                        mode: time
                        span: auto
                        default: '18:00'
```
#### I can not figure out why date is stored along ;(
```
[
   {
      "dow":"0",
      "end":"2018-03-10 18:00:00",
      "start":"2018-03-10 10:00:00"
   },
   {
      "dow":"1",
      "end":"2018-03-10 18:00:00",
      "start":"2018-03-10 10:00:00"
   },
   {
      "dow":"2",
      "end":"2018-03-10 18:00:00",
      "start":"2018-03-10 10:00:00"
   },
   {
      "dow":"3",
      "end":"2018-03-10 18:00:00",
      "start":"2018-03-10 10:00:00"
   },
   {
      "dow":"4",
      "end":"2018-03-10 18:00:00",
      "start":"2018-03-10 10:00:00"
   },
   {
      "dow":"5",
      "end":"2018-03-10 18:00:00",
      "start":"2018-03-10 10:00:00"
   },
   {
      "dow":"6",
      "end":"2018-03-10 18:00:00",
      "start":"2018-03-10 10:00:00"
   }
]
```
##### Reproduce steps
Maybe the issue is connected that I am storing all that repeater data in one JSON field - bussinesHours

##### October build
434
