### ISSUE TITLE
Flash message for Logout not popping up

### ISSUE THREAD

**Issue by WWRFresource** [octobercms/october#3467]
##### Expected behavior
When a user logs out using the RainLab.User plugin's Session component, they should see a popup flash message with confirmation that they have logged out.

##### Actual behavior
The flash message is displayed in a static div on the page and does not popup.

##### Reproduce steps
1. Add the following code to the login page:
`{% flash %} <div class="alert alert-{{ type }}">{{ message }}</div> {% endflash %}`
2. Provide a link to call the onLogout function
`<a data-request="onLogout" data-request-flash>Logout</a>`
3. Sign in as normal with valid account information.
4. Logout using the link provided.
5. Redirects to login page
6. Message is shown in a static div that does not popup.
![image](https://user-images.githubusercontent.com/28734844/37841143-f33c545e-2e8c-11e8-9ca1-f9cac9e09fc0.png)

##### October build
434

**Comment by LukeTowers** [comment]
@WWRFresource if you want the flash message to popup then that's something that you implement on your theme yourself. It's not the job of the plugin to do that on the frontend for you. Below is what I typically put in my themes to handle it:
```js
function($) {
    "use strict";

    jQuery(document).ready(function($) {
        /*-------------------------------
        OCTOBERCMS FLASH MESSAGE HANDLING
        ---------------------------------*/
        $(document).on('ajaxSetup', function(event, context) {
            // Enable AJAX handling of Flash messages on all AJAX requests
            context.options.flash = true;

            // Enable the StripeLoadIndicator on all AJAX requests
            context.options.loading = $.oc.stripeLoadIndicator;

            // Handle Flash Messages
            context.options.handleFlashMessage = function(message, type) {
                $.oc.flashMsg({ text: message, class: type });
            };

            // Handle Error Messages
            context.options.handleErrorMessage = function(message) {
                $.oc.flashMsg({ text: message, class: 'error' });
            };
        });
}(jQuery)};
```
and 
```css
.flash-message{position:fixed;width:500px;left:50%;top:50px;margin-left:-250px;color:#ffffff;font-size:14px;padding:10px 30px 10px 15px;z-index:10300;word-wrap:break-word;text-align:center;-webkit-box-shadow:0 1px 6px rgba(0,0,0,0.12),0 1px 4px rgba(0,0,0,0.24);box-shadow:0 1px 6px rgba(0,0,0,0.12),0 1px 4px rgba(0,0,0,0.24);-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px}
.flash-message.fade{opacity:0;filter:alpha(opacity=0);-webkit-transition:all 0.5s,width 0s;transition:all 0.5s,width 0s;-webkit-transform:scale(0.9);-ms-transform:scale(0.9);transform:scale(0.9)}
.flash-message.fade.in{opacity:1;filter:alpha(opacity=100);-webkit-transform:scale(1);-ms-transform:scale(1);transform:scale(1)}
.flash-message.success{background:#8da85e}
.flash-message.error{background:#cc3300}
.flash-message.warning{background:#f0ad4e}
.flash-message.info{background:#5fb6f5}
.flash-message button{float:none;position:absolute;right:10px;top:8px;color:white;outline:none}
.flash-message button:hover{color:white}
.flash-message.static{position:static !important;width:auto !important;display:block !important;margin-left:0 !important;-webkit-box-shadow:none;box-shadow:none}
@media (max-width:768px){.flash-message{left:10px;right:10px;top:10px;margin-left:0;width:auto}
}
.stripe-loading-indicator{height:4px;background:transparent;position:fixed;top:0;left:0;width:100%;overflow:hidden;z-index:10300}
.stripe-loading-indicator .stripe,.stripe-loading-indicator .stripe-loaded{height:4px;display:block;background:#3498db;position:absolute;-webkit-box-shadow:inset 0 1px 1px -1px #FFF,inset 0 -1px 1px -1px #FFF;box-shadow:inset 0 1px 1px -1px #FFF,inset 0 -1px 1px -1px #FFF}
.stripe-loading-indicator .stripe{width:100%;-webkit-animation:infinite-loader 60s linear;animation:infinite-loader 60s linear}
.stripe-loading-indicator .stripe-loaded{width:0;opacity:0;filter:alpha(opacity=0)}
.stripe-loading-indicator.loaded{opacity:0;filter:alpha(opacity=0);-webkit-transition:opacity 0.4s linear;transition:opacity 0.4s linear;-webkit-transition-delay:0.3s;transition-delay:0.3s}
.stripe-loading-indicator.loaded .stripe-loaded{opacity:1;filter:alpha(opacity=100);-webkit-transition:width 0.3s linear;transition:width 0.3s linear;width:100% !important}
.stripe-loading-indicator.hide{display:none}
@-moz-keyframes infinite-loader{0%{width:0%}
10%{width:42%}
20%{width:63%}
30%{width:78.75%}
40%{width:88.59375%}
50%{width:94.13085938%}
60%{width:97.07244873%}
70%{width:98.58920574%}
80%{width:99.35943391000001%}
90%{width:99.7475567%}
100%{width:99.94237615%}
}
@-webkit-keyframes infinite-loader{0%{width:0%}
10%{width:42%}
20%{width:63%}
30%{width:78.75%}
40%{width:88.59375%}
50%{width:94.13085938%}
60%{width:97.07244873%}
70%{width:98.58920574%}
80%{width:99.35943391000001%}
90%{width:99.7475567%}
100%{width:99.94237615%}
}
@-o-keyframes infinite-loader{0%{width:0%}
10%{width:42%}
20%{width:63%}
30%{width:78.75%}
40%{width:88.59375%}
50%{width:94.13085938%}
60%{width:97.07244873%}
70%{width:98.58920574%}
80%{width:99.35943391000001%}
90%{width:99.7475567%}
100%{width:99.94237615%}
}
@-ms-keyframes infinite-loader{0%{width:0%}
10%{width:42%}
20%{width:63%}
30%{width:78.75%}
40%{width:88.59375%}
50%{width:94.13085938%}
60%{width:97.07244873%}
70%{width:98.58920574%}
80%{width:99.35943391000001%}
90%{width:99.7475567%}
100%{width:99.94237615%}
}
@keyframes infinite-loader{0%{width:0%}
10%{width:42%}
20%{width:63%}
30%{width:78.75%}
40%{width:88.59375%}
50%{width:94.13085938%}
60%{width:97.07244873%}
70%{width:98.58920574%}
80%{width:99.35943391000001%}
90%{width:99.7475567%}
100%{width:99.94237615%}
}
@-moz-keyframes spin{0%{-moz-transform:rotate(0deg)}
100%{-moz-transform:rotate(359deg)}
}
@-webkit-keyframes spin{0%{-webkit-transform:rotate(0deg)}
100%{-webkit-transform:rotate(359deg)}
}
@-o-keyframes spin{0%{-o-transform:rotate(0deg)}
100%{-o-transform:rotate(359deg)}
}
@-ms-keyframes spin{0%{-ms-transform:rotate(0deg)}
100%{-ms-transform:rotate(359deg)}
}
@keyframes spin{0%{transform:rotate(0deg)}
100%{transform:rotate(359deg)}
}
@-moz-keyframes rspin{0%{-moz-transform:rotate(359deg)}
100%{-moz-transform:rotate(0deg)}
}
@-webkit-keyframes rspin{0%{-webkit-transform:rotate(359deg)}
100%{-webkit-transform:rotate(0deg)}
}
@-o-keyframes rspin{0%{-o-transform:rotate(359deg)}
100%{-o-transform:rotate(0deg)}
}
@-ms-keyframes rspin{0%{-ms-transform:rotate(359deg)}
100%{-ms-transform:rotate(0deg)}
}
@keyframes rspin{0%{transform:rotate(359deg)}
100%{transform:rotate(0deg)}
}
```
