### ISSUE TITLE
dependsOn not working when main and dependent fields located in different sections

### ISSUE THREAD

**Issue by PopcornPHP** [octobercms/october#3503]
It's not working:

```yaml
fields:
    country:
        label: Country
        type: dropdown

tabs:
    fields:
        state:
            label: State
            type: dropdown
            dependsOn: country
```

```php
public function getCountryOptions()
{
    return ['au' => 'Australia', 'ca' => 'Canada'];
}

public function getStateOptions()
{
    if ($this->country == 'au') {
        return ['act' => 'Capital Territory', 'qld' => 'Queensland', ...];
    }
    elseif ($this->country == 'ca') {
        return ['bc' => 'British Columbia', 'on' => 'Ontario', ...];
    }
}
```
