### ISSUE TITLE
Backend form text field preset doesn't work when updating

### ISSUE THREAD

**Issue by WebShapedBiz** [octobercms/october#3516]
##### Expected behavior
In my plugin, when I create or update Employee model using the backend form, 'slug' text field should be updated by model's 'name' field.
fields.yaml:
```
slug:
        label: 'Slug'
        span: auto
        type: text
        readOnly: true
        preset:
            field: name
            type: Slug
```
Employee.php model:
```
use \October\Rain\Database\Traits\Sluggable;
...
protected $slugs = ['slug' => 'name'];
```

##### Actual behavior
When I'm creating a new Employee, 'slug' text field works as it should, reflecting the 'name' field, but when I want to update this model's 'name' field, slug does not change, not while updating the 'name' field nor after saving the updated model.

##### Reproduce steps
(Describe the steps to reproduce the problem here)

##### October build
4.3.4.
