### ISSUE TITLE
Remove button does not trigger "change" event on "recordfinder" field

### ISSUE THREAD

**Issue by termiyanc** [octobercms/october#3591]
Hello.

I have "Product" model and two fields in my form:

```
discount:
    label: Discount
    type: recordfinder
    span: left
```
```
discounted_price:
    label: Discounted price
    type: number
    dependsOn: discount
    trigger:
        action: empty
        field: discount
        condition: value[]
    disabled: true
    span: right
```

As you can see, i would like to clear "discounted_price" field when "discount" field gets empty. But this does not work for me when i press remove button at "discount" field and confirm the removing, value of "discounted_price" field remains the same.

But if i manually triggers "change" event on "discount" field after removing

```
jQuery('#Form-field-Product-discount').trigger('change')
```

then trigger works and value of "discounted_price" gets empty.

So i conclude that remove button does not trigger "change" event on "recordfinder" field.

My versions are (from `composer list`):

```
laravel/framework                     v5.5.39            The Laravel Framework.
...
october/backend                       v1.0.434           Backend module for October CMS
october/cms                           v1.0.434           CMS module for October CMS
october/rain                          v1.0.434           October Rain Library
october/system                        v1.0.434           System module for October CMS
```
