### ISSUE TITLE
noRecordsMessage Not Working in Popup List

### ISSUE THREAD

**Issue by AugmentBLU** [octobercms/october#3594]
##### Expected behavior
When setting the `noRecordsMessage` option in a config_relation.yaml it should show a custom message for no records being found in the popup list when clicking add or link.

##### Actual behavior
This option is ignored and uses the default language file empty message. It appears to only work for the parent relation list but not the popup when clicking add or link existing records.

##### Reproduce steps
Create a simple relation and in the config_relation.yaml, try placing `noRecordsMessage: No stuff found` within the linked relation, perhaps try it in view and manage. When viewing a relation list, it will show a custom `noRecordsMessage`, however clicking add or link will not show a custom message in the popup window list.

##### October build
436

**Comment by LukeTowers** [comment]
@AugmentBLU please post your entire config_relation.yaml file

**Comment by AugmentBLU** [comment]
@LukeTowers 
```
properties:
    label: my.plugin::lang.property.label
    emptyMessage: No properties are linked to this portfolio
    showSetup: true
    view:
        list:  $/my/plugin/models/property/columns.yaml
        toolbarPartial: property_toolbar
        recordUrl: my/plugin/property/update/:checksum
        recordsPerPage: 10
        showSearch: true
        showCheckboxes: true
        defaultSort:
            column: name
            direction: desc
    manage:
        list:  $/my/plugin/models/property/columns.yaml
        form:  $/my/plugin/models/property/popup_fields.yaml
        recordsPerPage: 10
        showSearch: true
        defaultSort:
            column: name
            direction: desc
```
