### ISSUE TITLE
Trigger filterfields on adding/removing repeater field

### ISSUE THREAD

**Issue by robinbonnes** [octobercms/october#3595]
##### Expected behavior
When an item gets added/removed from a repeater, it should trigger the 'filterFields' function of the parent model.

##### Actual behavior
It doesn't trigger 'filterFields' on adding/removing an item.

##### Reproduce steps
1. Create a model with a repeater and text field inside:
```
        items:
            label: 'Repeater'
            type: repeater
            form:
                fields:
                    test:
                        label: 'When removing this entry'
        some_other:
            label: 'This should update'
            dependsOn: [items]
```
2. Add an item to the repeater.
3. Remove the item from the repeater

##### October build
436
