### ISSUE TITLE
datepicker shows up in wrong position

### ISSUE THREAD

**Issue by dundermave** [octobercms/october#3621]
##### Expected behavior
Datepicker should show up in correct position.

##### Actual behavior
Datepicker shows up in bottom left corner.

Here you got gif too see the behavior:
https://i.gyazo.com/62c14ec26aa62cbdb9858dfb1480f4bb.mp4

As you can see, time picker is working fine, but something is wrong with datepicker.
Same problem on chrome and firefox, windows 7

##### Reproduce steps
Create simple form fields in backend:
```
fields:
    datepicker:
        label: 'Date picker'
        span: auto
        type: datepicker
```

##### October build
437
