### ISSUE TITLE
Show week numbers for DatePicker form widget

### ISSUE THREAD

**Issue by mplodowski** [octobercms/october#3634]
##### Expected behavior

Allow to specify in DatePicker form widget if it shows week numbers.

##### Actual behavior

Week numbers are not displayed.

##### Reproduce steps

Create backend form and add datepicker field definition:

```
start_date:
    label: Start Date
    type: datepicker
    showWeekNumber: true
```

##### October build

437

I would like to prepare PR for this. Are you interested?
