### ISSUE TITLE
FR: shorthand for partial form widget path definition

### ISSUE THREAD

**Issue by achtan** [octobercms/october#3641]
Hi, pls dont force us to create boilerplate files like: `controllers/foo/_bar.htm`

for Example:
##### Actual behavior
````yaml
fields:
    languages:
            span: right
            path: languages
            type: partial
            tab: 'O uchadzacovi'
````

controllers/foo/_languages.htm
````php
<?= $this->relationRender('languages') ?>
````

##### Expected behavior
````yaml
fields:
    languages:
            span: right
            path: languages # or even omit if its same as key-name
            type: partial
            tab: 'O uchadzacovi'
````
no need for `controllers/foo/_languages.htm`
