### ISSUE TITLE
Backend list header "align" option does not work without "sortable"

### ISSUE THREAD

**Issue by BenjaVR** [octobercms/october#3649]
##### Expected behavior
When using the `align: center` option in a backend list ([search for "align"](https://octobercms.com/docs/backend/lists)), the column headers should be centered. This works only if the `sortable` option is set to true:
![image](https://user-images.githubusercontent.com/17981138/43110229-1289122a-8eeb-11e8-9b92-d3da05ecd019.png)
If you would put the `sortable` option to false, the result you want would be:
![image](https://user-images.githubusercontent.com/17981138/43110313-90743caa-8eeb-11e8-8788-0adf17aa537e.png)
However, in this screenshot I manually added the `list-cell-align-center` CSS class to the column header to show how it should work.

##### Actual behavior
When setting the `sortable` option to false, the `align` option is ignored for the header:
![image](https://user-images.githubusercontent.com/17981138/43110264-3fac4f56-8eeb-11e8-80e1-cd5ceca35455.png)

##### Reproduce steps
In `columns.yaml` have this and see it's not centered:
```yaml
columns:
    name:
        label: Name
        type: text
        align: center
        sortable: false
```
While this is centered:
```yaml
columns:
    name:
        label: Name
        type: text
        align: center
        sortable: false
```

##### October build
437
