### ISSUE TITLE
How to update formwidget with dependsOn: relation manager?

### ISSUE THREAD

**Issue by pavelmgn** [octobercms/october#3657]
fields.yaml
```
client:
            label: 'Client'
            type: client_creator
            span: auto
            dependsOn: client_information
            tab: 'test'
client_information:
            label: ''
            oc.commentPosition: ''
            type: partial
            dependsOn: client
            path: $/anplus/bz/controllers/clients/_field_client.htm
            tab: 'test'
```

client - formwidget client_information - relation manager

If i update client field, relation manager updated. How to force to update a client field at updating relation manager?

https://octobercms.com/forum/post/how-update-formwidget-with-dependson-option
