### ISSUE TITLE
Relation column on list breaks search

### ISSUE THREAD

**Issue by that0n3guy** [octobercms/october#369]
I have a custom list:

```
# ===================================
#  List Column Definitions
# ===================================

columns:
    id:
        label: ID
    name:
        label: Name
        searchable: true
    firstname:
        label: First Name
    lastname:
        label: Last Name
    email:
        label: Email
    phone:
        label: Phone
    lists:
        label: Lists
        relation: lists
        select: @name
    active:
        label: Active?
        type: switch
```

search is broken with the above (lists is a polymorphic relationship)

If I remove the relation column, then search works:

```
# ===================================
#  List Column Definitions
# ===================================

columns:
    id:
        label: ID
    name:
        label: Name
        searchable: true
    firstname:
        label: First Name
    lastname:
        label: Last Name
    email:
        label: Email
    phone:
        label: Phone
    lists:
        label: Lists
        relation: lists
        select: @name
    active:
        label: Active?
        type: switch
```
