### ISSUE TITLE
Extending Cms\Models\ThemeData assetVar values not available for LESS Compiler

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#3710]
##### Expected behavior

Extending the `Cms\Models\ThemeData` model should make `assetVars` field values available for `System\Classes\CombineAssets` when compiling LESS using `theme` TWIG filter.

##### Actual behavior

Any `assetVar` field values that are added by extending the `Cms\Models\ThemeData` model and not available in `System\Classes\CombineAssets` when when compiling LESS using `theme` TWIG filter.

##### Reproduce steps

https://github.com/octoberrain/test-plugin/pull/51

Add a less file to a theme, eg:

* `themes/example-theme/assets/less/test.less`

```less
.test-colour {
    background: @testColour;
}
.another-test-colour {
    background: @anotherTestColour;
}
```

Then include:

```html
<link href="{{ ['assets/less/test.less'] | theme }}.css">
```

in theme layout partial.

##### October build
4.0.19
