### ISSUE TITLE
Extend the YAML for the use of Laravel accessors and mutators

### ISSUE THREAD

**Issue by Kerensky25** [octobercms/october#372]
**Extend the YAML for the use of Laravel accessors and mutators.**
To allow pre/post processing in columns/fields for the backend list/form

**YAML**

``` yaml
columns:
    name:
        label: Name
        select: accessorsName
```

**And in the model:**

``` php
public function getNameAttribute(){ ... }
```

_The same goes for the mutators in the YAML "fields" file._
