### ISSUE TITLE
Translate options in config_filter.yaml ( type: group )

### ISSUE THREAD

**Issue by LucasZdv** [octobercms/october#3789]
##### Expected behavior
LIST FILTER.
Translation does not work in the scope options.

config_filter.yaml 
```
scopes:
    type:
        label: awebsome.shop::lang.label.type
        type: group
        conditions: type in (:filtered)
        options:
            sale: awebsome.shop::lang.label.sale
            extraction: awebsome.shop::lang.label.extraction
```

##### Actual behavior
in the label works correctly, but not in options.

##### October build
buid 442
