### ISSUE TITLE
morphTo and proxy form fields

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#3807]
https://github.com/octobercms/october/blob/2d77565e6cbdc26e91a2c1459bf90da79e70c23a/modules/backend/traits/FormModelSaver.php#L67

Is there any reason morphTo is not listed in the singular types? I've got a content model which morphs to various type models and the controller displays a different set of fields depending on the type. The problem is that proxy fields cause an error on saving unless I add `morphTo` to the `singularTypes` array, then saving works perfectly.

The error is:

> ErrorException: Undefined offset: 0 in D:\October\Playground\vendor\october\rain\src\Database\Relations\MorphTo.php:51

The content model is:

``` php
class Node extends Model
{
    public $morphTo = [
        'content' => []
    ];
}
```

A content type would be:

``` php
class Article extends Model
{
    public $morphOne = [
        'node' => [Node::class, 'name' => 'content']
    ];
}
```

An example form definition for `Node` would be:

``` yaml
# Title belongs to Node model
title:
    label: Title
    type: text
# Proxy to field on Article
content[body]:
    label: Body
    type: richeditor
```
