### ISSUE TITLE
taglist odd behavior on remove first value

### ISSUE THREAD

**Issue by mberizzo** [octobercms/october#3811]
##### Expected behavior
Add and remove values without problems

##### Actual behavior
You can add coma separeted values without problems but if you want to delete the first value, you can't because when input field lose focus, the first value reappear. Only happend with first value and when you are updating

##### Reproduce steps

1. In your fields.yaml create a field with type=taglist
2. Add diferents values. ie: val1, val2, val3, val4
3. Click Save button
4. Click to edit
5. Delete val1 (click "x")
6. Click "Save" (now the val1 reappear) 

##### October build
434

**Comment by LukeTowers** [comment]
Can you attach a GIF of this happening along with the list of fields used to recreate it?

**Comment by mberizzo** [comment]
![bug_taglist](https://user-images.githubusercontent.com/2679457/45917870-7983a100-be54-11e8-99c5-8815190fc6aa.gif)

fields.yaml
```
tabs:
    fields:
        name:
            label: 'mberizzo.beers::lang.field.name'
            span: auto
            type: text
            tab: 'mberizzo.beers::lang.tab.details'
        category:
            label: 'mberizzo.beers::lang.field.category'
            nameFrom: name
            descriptionFrom: description
            span: auto
            type: relation
            tab: 'mberizzo.beers::lang.tab.details'
        description:
            label: 'mberizzo.beers::lang.field.description'
            size: small
            span: full
            type: textarea
            tab: 'mberizzo.beers::lang.tab.details'
        properties:
            label: 'mberizzo.beers::lang.field.properties'
            span: full
            type: taglist
            tab: 'mberizzo.beers::lang.tab.features'
        specs:
            label: 'mberizzo.beers::lang.field.specs'
            prompt: 'backend::lang.form.add'
            span: full
            containerAttributes: {  }
            type: repeater
            maxItems: 4
            tab: 'mberizzo.beers::lang.tab.features'
            form:
                fields:
                    name:
                        label: 'mberizzo.beers::lang.field.name'
                        span: left
                        type: text
                        comment: 'mberizzo.beers::lang.misc.spects.name_comment'
                    value:
                        label: 'mberizzo.beers::lang.field.value'
                        span: right
                        type: text
                        comment: 'mberizzo.beers::lang.misc.spects.hops_comment'
        launch_date:
            label: 'mberizzo.beers::lang.field.launch_date'
            mode: date
            span: auto
            type: datepicker
            tab: 'mberizzo.beers::lang.tab.config'
            ignoreTimezone: true
        is_featured:
            label: 'mberizzo.beers::lang.field.is_featured'
            span: left
            type: switch
            tab: 'mberizzo.beers::lang.tab.config'
        is_active:
            label: 'mberizzo.beers::lang.field.is_active'
            span: left
            default: 1
            type: switch
            tab: 'mberizzo.beers::lang.tab.config'
secondary_tabs:
    fields:
        logo:
            label: 'mberizzo.beers::lang.field.logo'
            mode: file
            type: fileupload
        image:
            label: 'mberizzo.beers::lang.field.image'
            mode: image
            type: fileupload
```
