### ISSUE TITLE
Custom theme data doesn't support array fields

### ISSUE THREAD

**Issue by SeriousKen** [octobercms/october#3826]
Custom settings on the theme doesn't support array fields, for example if you add the following to the demo theme's `theme.yaml`

``` yaml
form:
    fields:
        custom[forename]:
            label: Forename
        custom[surname]:
            label: Surname
```

It says:

> Unexpected type of array when attempting to save attribute "custom", try adding it to the $jsonable property. 

I've looked into this and it seems the `beforeSave` method is being called too late. I've created a fix by moving the code to the `model.saveInternal` event instead as this is fired before the validation that triggers the error.
