### ISSUE TITLE
Request: Repeater titleFrom bind to more options

### ISSUE THREAD

**Issue by claudchan** [octobercms/october#3921]
Hi,
Can make the repeater titleFrom not just bind to text field (type: text)?
Suggest to also bind with the label (type: section).
I am creating a component that does not have title field required also I do not want user to purposely to key in a label just for the title display after collapsed. 

[https://imgur.com/a/UidiWVl](https://imgur.com/a/UidiWVl)

```
extra_information:
    type: repeater
    titleFrom: section_label
    form:
        fields:
           section_label:
                label: Carousel
                type: section
```
