### ISSUE TITLE
Feature Request: Allow all Backend Tabs to become slide-able

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#3959]
Sorry you must be sick and tired of all my requests!

I keep trying to slide the editor tabs! I am so use to doing this in all my developer tools.

I really think this would be a welcomed feature.

Example `.gif` showing the feature in Google Canary tabs:

![ezgif-2-1bb9608cb2ef](https://user-images.githubusercontent.com/17784082/49390709-932d4880-f721-11e8-933d-f26e2cd432b2.gif)

I am referring to this section in October CMS backend:

![aaaaaaaaaaaaaa](https://user-images.githubusercontent.com/17784082/49390756-ae985380-f721-11e8-8366-e23ae6a8eb6a.png)

It would make the work flow so much easier!

Thanks.

**Comment by LukeTowers** [comment]
Feel free to submit a PR for that @ayumihamsaki. Try to avoid adding any new dependencies.

**Comment by ayumihamsaki** [comment]
@LukeTowers Quick Question, do you know what library October uses for the Dashboard drag n drop. Maybe I could extend that one for the tabs?

**Comment by LukeTowers** [comment]
Isotope isn't it?

**Comment by ayumihamsaki** [comment]
@LukeTowers 

I believe Isotope does not have a drag and drop feature built into it see github here: https://github.com/metafizzy/isotope/issues/213

People keep quoting [Packery](https://packery.metafizzy.co/)

I'm not sure if October uses that library, I can't see any sign of it in October.

I have done a little bit of research into this issue and have found three different solutions:

## Solution 1:

 Use jQuery UI see here: http://jqueryui.com/tabs/?#sortable

Pro's: Very solid coding solution and easy to add
Con's: Way too large code size, using a custom build created something crazy like 85Kb

Also see here a demo combining Isotope + jQuery UI of a dashboard: https://codepen.io/ultimatedelman/pen/kIgrC

## Solution 2:

Using SortableJS see here: https://github.com/SortableJS/Sortable

Pro's: This is the best library I have tested so far! It allows you to drag and drop and slide objects using mouse click events and TOUCH SCREEN.
Con's: Min Code Size is: 15.3 KB

Notes: If it is decided to use this option it could allow more drag and drop features in October CMS, so it does open the doors to some more features in the future!

## Solution 3:

Using the HTML Native Drag and Drop API, there is a library found here: https://github.com/lukasoppermann/html5sortable

Pro's: Only 2KB (minified and gzipped)
Con's: Only allows MOUSE click drag and drop, doesn't allow TOUCH SCREEN events.

Ok please give me feedback.

p.s. My plan is to finish off the code editor section updates, the ajax csp issue and the dashboard issue. Then later work on this, so it's quite far down my to do list, to help out the October Team.

**Comment by w20k** [comment]
@LukeTowers, seems not. Isotope only used in the reportsController (Dashboard).

**Comment by ayumihamsaki** [comment]
@w20k yep very speedy right haha

**Comment by w20k** [comment]
@ayumihamsaki, I'd drop all the options, despite jQuery UI, because it's already a part of the asset library as well as jQuery.Drag and jQuery.Scroll. 
The one huge, like gigantic part, would be - testing (manual & auto. - I want UI tests 😄 or just simple smoke tests). Wouldn't be that great to add a new shiny feature with glitching.

**Comment by ayumihamsaki** [comment]
@w20k I just found the files now, location here:

https://github.com/octobercms/october/blob/master/modules/system/assets/ui/js/drag.scroll.js
https://github.com/octobercms/october/blob/master/modules/system/assets/ui/js/drag.sort.js

fiddle looks ok as well.

**Comment by ayumihamsaki** [comment]
@w20k I just found the files now, location here:

https://github.com/octobercms/october/blob/master/modules/system/assets/ui/js/drag.scroll.js
https://github.com/octobercms/october/blob/master/modules/system/assets/ui/js/drag.sort.js

fiddle looks ok as well, except the "Lock Last Tab" doesn't work. When you turn it on, you can't turn it off. But I think don't need that part for October?

p.s. that's not `padding`, it is being snapped to the `top` of the `div` container when the tabs are dragged. So looks like just need to make the `div` container `height` the same as the tab `height` then no floating effect.

**Comment by w20k** [comment]
That looks awesome, thanks @ayumihamsaki !
Forgot my charger, so no working weekends for me, 50% left 😄

**Comment by ayumihamsaki** [comment]
@w20k @LukeTowers 

Ok I run some experiments right now and need to get some feedback. I do the following code:

1. https://github.com/octobercms/october/blob/master/modules/backend/layouts/_head.htm

add the lines:

```html
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  $( function() {
    var tabs = $( ".tabs-container" ).tabs();
    tabs.find( ".ui-tabs-nav" ).sortable({
      axis: "x",
      stop: function() {
        tabs.tabs( "refresh" );
      }
    });
  } );
</script>
```

2. https://github.com/octobercms/october/blob/master/modules/system/assets/ui/storm.css

```css
.nav-tabs > li {
    float: left;
    /* margin-bottom: -1px; */
}
```

3. https://github.com/octobercms/october/blob/master/modules/backend/assets/css/october.css

```css
.fancy-layout .control-tabs.master-tabs > div > div.tabs-container > ul.nav-tabs > li, .fancy-layout.control-tabs.master-tabs > div > div.tabs-container > ul.nav-tabs > li {
    margin-left: -5px;
    top: 1px;
    padding-top: 3px;
    border-bottom: 1px solid #e67e22; // added this line CSS did not match up before
}

.fancy-layout .control-tabs.master-tabs > div > div.tabs-container > ul.nav-tabs > li a > span.title:before, .fancy-layout.control-tabs.master-tabs > div > div.tabs-container > ul.nav-tabs > li a > span.title:before {
    left: -14px;
    -webkit-border-radius: 8px 0 0 0;
    -moz-border-radius: 8px 0 0 0;
    border-radius: 8px 0 0 0;
    -webkit-transform: skewX(-20deg);
    -ms-transform: skewX(-20deg);
    transform: skewX(-20deg);
    height: 38px; // added this line to fill bottom
}

.fancy-layout .control-tabs.master-tabs > div > div.tabs-container > ul.nav-tabs > li a > span.title:after, .fancy-layout.control-tabs.master-tabs > div > div.tabs-container > ul.nav-tabs > li a > span.title:after {
    right: -14px;
    -webkit-border-radius: 0 8px 0 0;
    -moz-border-radius: 0 8px 0 0;
    border-radius: 0 8px 0 0;
    -webkit-transform: skewX(20deg);
    -ms-transform: skewX(20deg);
    transform: skewX(20deg);
    height: 38px; // added this line to fill bottom
}

```

This gives me the following result:

![tabs](https://user-images.githubusercontent.com/17784082/49690141-c7d74080-fb23-11e8-818b-901fa1533cf6.gif)

### Issues:

The jQuery UI is causing a lot of conflict issues, any suggestions? It needs to be there or I get the following JS error message:

`Uncaught TypeError: $(...).tabs is not a function`

Was thinking of creating a smaller build of jQuery UI?

Or maybe you guys got a better solution.
