### ISSUE TITLE
Cant see code buttons after V446 update

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4019]
I just updated the cms to latest version and notice the code icons are now really hard to see, please see screenshot:

![untitled](https://user-images.githubusercontent.com/17784082/50541966-220a7500-0ba9-11e9-928c-017ef82ac58c.png)

Can I have permission to update the color to pass WCAG 2.0 AA, code section:

![untitled](https://user-images.githubusercontent.com/17784082/50541985-79a8e080-0ba9-11e9-8738-a539546d421c.png)

add the code:

```css
.secondary-tabs .field-codeeditor .editor-toolbar >ul >li >a {
    color: #cdc8c8;
}
```

See after screenshot:

![untitled](https://user-images.githubusercontent.com/17784082/50541996-c68cb700-0ba9-11e9-8542-ac8cfb6076fb.png)

If ok, will create a pr.

**Comment by ayumihamsaki** [comment]
Actually if someone else could create the pr it would be helpful, I have reached my max number of branches open for pr's in github. The css is in the file and LESS file:

`/modules/backend/formwidgets/codeeditor/assets/css/codeeditor.css?v446`

**Comment by LukeTowers** [comment]
@Teranode could you look into this please?

**Comment by Teranode** [comment]
@LukeTowers shoudl I push it to this? https://github.com/octobercms/october/pull/4016 (since they're codeditor and richeditor) or create a separate patch.

**Comment by ayumihamsaki** [comment]
@LukeTowers @Teranode I'm going to create a temp account and fix this right now. I got a feeling my previous pr I missed out the less code. I will create a pr for this right now.

**Comment by ayumihamsaki** [comment]
I can't create the pr github has flagged me:

![wwwww](https://user-images.githubusercontent.com/17784082/50548179-2fbf0980-0c40-11e9-8e07-18833e25aba0.png)

I will write the code below, can someone create the pr for it:

**Comment by ayumihamsaki** [comment]
File Location: \modules\backend\formwidgets\codeeditor\assets\css\codeeditor.css

Code:

```css
.field-codeeditor{width:100%;position:relative;border:2px solid #d1d6d9;-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px}
.field-codeeditor textarea{opacity:0;filter:alpha(opacity=0)}
.field-codeeditor.editor-focus{border:2px solid #d1d6d9}
.field-codeeditor.size-tiny{min-height:50px}
.field-codeeditor.size-small{min-height:100px}
.field-codeeditor.size-large{min-height:200px}
.field-codeeditor.size-huge{min-height:250px}
.field-codeeditor.size-giant{min-height:350px}
.field-codeeditor .ace_search{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";font-size:14px;color:#333333;z-index:13}
.field-codeeditor .editor-code{-webkit-border-radius:3px;-moz-border-radius:3px;border-radius:3px}
.field-codeeditor .editor-toolbar{position:absolute;top:10px;right:25px;z-index:10}
.field-codeeditor .editor-toolbar > ul,.field-codeeditor .editor-toolbar ul > li{list-style-type:none;padding:0;margin:0}
.field-codeeditor .editor-toolbar > ul > li{float:left}
.field-codeeditor .editor-toolbar > ul > li .tooltip.left{margin-right:25px}
.field-codeeditor .editor-toolbar > ul > li > a{display:block;height:25px;width:25px;color:#666;font-size:20px;text-align:center;text-decoration:none}
.field-codeeditor .editor-toolbar > ul > li > a > abbr{position:absolute;font:0/0 a;color:transparent;text-shadow:none;background-color:transparent;border:0}
.field-codeeditor .editor-toolbar > ul > li > a > i{opacity:0.7;filter:alpha(opacity=70);display:block}
.field-codeeditor .editor-toolbar > ul > li > a > i:before{font-size:15px}
.field-codeeditor .editor-toolbar > ul > li > a:hover > i,.field-codeeditor .editor-toolbar > ul > li > a:focus > i{opacity:1;filter:alpha(opacity=100)}
.field-codeeditor.editor-fullscreen{z-index:301;position:fixed !important;top:0;left:0;height:100%;border-width:0;-webkit-border-radius:0;-moz-border-radius:0;border-radius:0}
.field-codeeditor.editor-fullscreen .editor-code{-webkit-border-radius:0;-moz-border-radius:0;border-radius:0}
.field-codeeditor.editor-fullscreen .editor-toolbar{z-index:302}
.field-codeeditor.editor-fullscreen .ace_search{z-index:303}
.secondary-tabs .field-codeeditor .editor-toolbar >ul >li >a {color: #cdc8c8}
```

**Comment by ayumihamsaki** [comment]
File Location: \modules\backend\formwidgets\codeeditor\assets\less\codeeditor.less

Code:

```css
@import "../../../../assets/less/core/boot.less";

@color_1: #cdc8c8;

.field-codeeditor {
    width: 100%;
    position: relative;
    border: 2px solid @color-form-field-border;
    .border-radius(@border-radius-base);
    textarea { .opacity(0); }

    &.editor-focus { border: 2px solid @color-form-field-border-focus; }

    &.size-tiny { min-height: @size-tiny; }
    &.size-small { min-height: @size-small; }
    &.size-large { min-height: @size-large; }
    &.size-huge { min-height: @size-huge; }
    &.size-giant { min-height: @size-giant; }

    .ace_search {
        font-family: @font-family-base;
        font-size: 14px;
        color: @text-color;
        z-index: @zindex-form + 3;
    }

    .editor-code {
        .border-radius(@border-radius-base);
    }

    .editor-toolbar {
        position: absolute;
        top: 10px;
        right: 25px;
        z-index: @zindex-form;
        > ul, ul > li { list-style-type: none; padding: 0; margin: 0; }
        > ul > li {
            float: left;

            .tooltip.left {
                margin-right: 25px;
            }
        }
        > ul > li > a {
            display: block;
            height: 25px;
            width: 25px;
            color: #666;
            font-size: 20px;
            text-align: center;
            text-decoration: none;
            > abbr {
                position: absolute;
                .text-hide();
            }
            > i {
                .opacity(.7);
                display: block;
                &:before {
                    font-size: 15px;
                }
            }
            &:hover, &:focus {
                > i { .opacity(1); }
            }

        }
    }

    &.editor-fullscreen {
        z-index: @zindex-fullscreen + 1;
        position: fixed!important;
        top: 0;
        left: 0;
        height: 100%;
        border-width: 0;
        .border-radius(0);
        .editor-code { .border-radius(0); }
        .editor-toolbar { z-index: @zindex-fullscreen + 2; }
        .ace_search { z-index: @zindex-fullscreen + 3; }
    }
}

.secondary-tabs {
	.field-codeeditor {
		.editor-toolbar {
			>ul {
				>li {
					>a {
						color: @color_1;
					}
				}
			}
		}
	}
}
```

**Comment by ayumihamsaki** [comment]
Gives the following results:

### Main Code Editor (Light Icons):

![untitled](https://user-images.githubusercontent.com/46263127/50548136-9e4f9780-0c3f-11e9-85a6-992f35b9599e.png)

### The rest of October (Dark Icons):

![untitled](https://user-images.githubusercontent.com/46263127/50548160-d5be4400-0c3f-11e9-8970-db32d215b60a.png)

**Comment by LukeTowers** [comment]
@ayumihamsaki why are the buttons offset from the right in the HTML markup section of your screenshot?

**Comment by LukeTowers** [comment]
@Teranode separate patch, that PR doesn't fully solve the original issue so it'll need more review first.

**Comment by Teranode** [comment]
@LukeTowers that offset is there because the regular cms display expects the chevron icon:
![](https://i.imgur.com/vTig2Tz.png)

![](https://i.imgur.com/WzhYVxE.png)

**Comment by LukeTowers** [comment]
@Teranode could you reposition them in the context that doesn't include the chevron as well?

**Comment by ayumihamsaki** [comment]
It was there just like Teranode said in his comment, I have not tested this but from the top of my head you could probably just change this:

From:

```css
.field-codeeditor .editor-toolbar{
    position:absolute;
    top:-30px;
    right:35px;
    z-index:13
}
```

into this:

```css
.field-codeeditor .editor-toolbar {
    position: absolute;
    top: -30px;
    right: 0;
    z-index: 10
}
.secondary-tabs .field-codeeditor .editor-toolbar{
    position:absolute;
    top:-30px;
    right:35px;
    z-index:10
}
```

Then it would probably shift only the main code editor screen - but like I say that's just from the top of my head and not tested in anyway.
