### ISSUE TITLE
Datepicker field not working

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#402]
I have a form field

``` yaml
  expires:
    label: Expires At
    type: datepicker
    mode: date
```

which displays the field but no datepicker when I click on it. No javascript errors. Perhaps because the field is displayed in a modal instead of initial page load?
