### ISSUE TITLE
Documentation for form fields does not mention checkboxes

### ISSUE THREAD

**Issue by jbh** [octobercms/october#406]
The [Form Field Types](http://octobercms.com/docs/backend/forms#form-field-types) documentation does not mention how to do checkboxes.

Here is an example of a checkbox form field:

``` yml
        showFullContent:
            label Show full content?
            type: checkbox
            span: left
            default: true
            comment: This is a comment
            description: This is a description
```
