### ISSUE TITLE
Depends on with 3 fields.

### ISSUE THREAD

**Issue by pavelmgn** [octobercms/october#4070]
Hello. If i write several dependsOn > 2 in fields.yaml, field not updated, by change first field. All 4 fields has dropdown type.
![rfg](https://user-images.githubusercontent.com/8817759/51300222-f9112d80-1a4c-11e9-9592-5a5c8e0abb88.gif)
![default](https://user-images.githubusercontent.com/8817759/51300228-ff070e80-1a4c-11e9-87ce-aef0da2888b4.JPG)

1 field:
```
public function getRegionOptions()
	{
		return Region::all()->lists('name', 'id');
	}
```

2 field:
```
public function getCounterpartyOptions($value, $data)
	{
		$citiesIds = (isset($data->region)) ? Region::find($data->region->id)->cities->lists('id')
			: Region::find(key($this->getRegionOptions()))->cities->lists('id');
		
		$counterparties = Counterparty::whereHas('cities', function($query) use ($citiesIds) {
			$query->whereIn('id', $citiesIds);
		})->lists('name', 'id');
		
		$result = [0 => '-- Не выбран --'] + $counterparties;
		
		return $result;
	}
```

3 field:
```
public function getCityOptions($value, $data)
	{
		$counterparty =
			isset($data->counterparty) ? $data->counterparty->id : key($this->getCounterpartyOptions($value, $data));
		
		$region = (isset($data->region)) ? $data->region->id : key($this->getRegionOptions());
		
		$empty = [0 => '-- Не выбран --'];
		
		if ( ! isset($counterparty) || $counterparty === 0 ) {
			return $empty;
		}
		
		return $empty +
		       Counterparty::find($counterparty)->cities()->whereHas('region', function($query) use ($region) {
			       $query->where('id', $region);
		       })->lists('name', 'id');
	}
```

4 field:
```
public function getShopOptions($value, $data)
	{
		$city = isset($data->city) ? $data->city->id : key($this->getCityOptions($value, $data));
		
		$empty = [0 => '-- Не выбран --'];
		
		if ( ! isset($city) || $city === 0 ) {
			return $empty;
		}
		
		return $empty + Shop::whereHas('city', function($query) use ($city) {
				$query->where('id', $city);
			})->lists('code', 'id');
	}
```

When all fields are selected, after changing the first field only 2 and 3 are updated, their value is set to 0. The last field thinks that 3 field has a value not 0. Help me please

Thanks!

**Comment by LukeTowers** [comment]
@pavelmgn what's your `fields.yaml` look like?

**Comment by pavelmgn** [comment]
@LukeTowers, this is 4 field. Troubles with last field.
```
...
region:
            label: Регион
            type: dropdown
            span: auto
            tab: 'Основная информация'

        counterparty:
            label: Подрядчик
            span: auto
            type: dropdown
            dependsOn: region
            tab: 'Основная информация'

        city:
            label: Город
            span: auto
            dependsOn:
                - region
                - counterparty
            type: dropdown
            tab: 'Основная информация'

        shop:
            label: 'Код магазина'
            span: auto
            type: dropdown
            dependsOn:
                - region 
                - counterparty
                - city
            tab: 'Основная информация'
...
```
