### ISSUE TITLE
ErrorException: count(): Parameter must be an array

### ISSUE THREAD

**Issue by AugmentBLU** [octobercms/october#4178]
- OctoberCMS Build: 448
- PHP Version: 7.2 & 7.3

### Description:
When attempting to change the translation of a repeater an error popup appear.

```ErrorException: count(): Parameter must be an array or an object that implements Countable in modules/backend/formwidgets/Repeater.php:210```

### Steps To Reproduce:
Create a repeater, with a translation. Attempt to change the language - you are presented with this error.

**Comment by w20k** [comment]
@AugmentBLU it was already addressed by @bennothommo. Could you test this PR to see if it helps (https://github.com/octobercms/october/pull/4160)?

**Comment by AugmentBLU** [comment]
@w20k A new error appears now.

```
Undefined offset: 3
```

```
ErrorException: Undefined offset: 3 in /home/forge/why/releases/20190303173327/modules/backend/formwidgets/Repeater.php:206
Stack trace:
#0 /home/forge/why/releases/20190303173327/modules/backend/formwidgets/Repeater.php(206): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined offse...', '/home/forge/why...', 206, Array)
```

**Comment by w20k** [comment]
@bennothommo I guess it's not over yet 😄 Could you look at it?

**Comment by AugmentBLU** [comment]
This bug is breaking several sites. Any idea when it was introduced so I can roll back? It wasn't happening on my local setup with 447 on PHP 7.2.

**Comment by w20k** [comment]
@AugmentBLU I guess with a new release... But it should be an edge build 448.

**Comment by bennothommo** [comment]
@AugmentBLU Could you provide us with your form configuration (ie. `form_config.yml`) that you are using  as well as the POST data you used when the error occurred? It might be a particular widget inside the repeater which is causing this.

**Comment by AugmentBLU** [comment]
Wow, data is being removed from the database on save. I don't have time to read in to this deeper as I now need to restore stuff.

**Comment by Rike-cz** [comment]
The same problem. I added to line 210 condition...
`if (empty($widgetValue) || (is_iterable($widgetValue) && !count($widgetValue))) {`

**Comment by bennothommo** [comment]
@Rike-cz are you using the Translate plugin as well?

@AugmentBLU Does the same issue happen if the Translate plugin is not enabled?

**Comment by Rike-cz** [comment]
@bennothommo In that case (ver. 448) not. I think that issue happen because of custom (?) form widget. I use improved mediafinder and I found that mediafinder value causes that error. My mediafinder returns string - it's not empty but also not countable.

**Comment by bennothommo** [comment]
@Rike-cz thanks for the info. How about with PR #4160 in place? Does that cause any issues for you? Just trying to determine what caused @AugmentBLU 's data loss.

**Comment by Rike-cz** [comment]
@bennothommo PR #4160 works fine for me without Translate plugin. With Translate plugin I have 2 filled forms in repeater (indexes 0 and 1) and try to switch language. It throws `"Undefined offset: 0" on line 206 of C:\dev\web\www\icestudio\brancoreality\modules\backend\formwidgets\Repeater.php`.

**Comment by bennothommo** [comment]
@Rike-cz Are you using the MLRepeater widget provided through the Translate plugin in this instance, or just a normal Repeater widget?

**Comment by tobias-kuendig** [comment]
This is my fields config:

```
    downloads:
            label: Downloads
            span: auto
            type: repeater
            tab: Details
            form:
                fields:
                    download_name:
                        label: Bezeichnung
                        span: auto
                        type: text
                    download_file:
                        label: Datei
                        mode: file
                        span: auto
                        type: mediafinder
```

I am using RainLab.Translate as well and the whole `downloads` field is marked as translatable. 

What I noticed is that if I change the repeater to an other language I can save just fine (even changes made on other languages are saved). The countable error only appears if I have the primary language active in the repeater.
