### ISSUE TITLE
dependsOn not working for datepicker with time format

### ISSUE THREAD

**Issue by robinbonnes** [octobercms/october#4268]
- OctoberCMS Build: 451
- PHP Version: 7.1

### Description:
When having a form with a datepicker field in time mode, other fields that depend on that field by the dependsOn configuration, don't update.

The same is happening for datetime fields, but then it only updates on changing the date.

### Steps To Reproduce:

Create a form like this:

```
field1:
    type: datepicker
    mode: time

field2:
    type: datepicker
    mode: time
    dependsOn: field1
```

Changing the time in field 1 doesn't trigger the filterFields method.
