### ISSUE TITLE
Add a list of optionally supported plugins in theme.yaml

### ISSUE THREAD

**Issue by lautsevich** [octobercms/october#4307]
Hi.

By developing themes for October CMS websites you must list required plugins in the `theme.yaml` file. But themes can support some other plugins as an available option. So it can be very useful to add to the `theme.yaml` file a new block with the list of optional dependencies, e.g.:

```yml
name: Awesome theme
description: 'My super-duper theme for October CMS'
author: Lovata
homepage: ''
code: 'awesome-theme'
require:
    - Lovata.Toolbox
    - Lovata.Shopaholic
optional:
    - Lovata.ReviewsShopaholic
```
And the optional plugins will show on the theme page in the marketplace like the required plugins.

![image](https://user-images.githubusercontent.com/196445/57069321-f4f7db80-6cdc-11e9-9acc-05f7b3d4ceb9.png)

It would be much useful to list optional plugins near the required instead of listing them in the description.

![image](https://user-images.githubusercontent.com/196445/57069414-3e482b00-6cdd-11e9-8c70-41687110a774.png)

We at LOVATA just started to develop themes for our Shopaholic. And we plan to add a huge amount of themes to the marketplace in the near future. Each theme will support a lot of required and optional plugins. And we prefer to tell in the theme description more about the functionality and benefits of using it instead of stealing the place for listing the optional plugins.
