### ISSUE TITLE
Nested Repeater - A widget with class name has not been bound to the controller

### ISSUE THREAD

**Issue by iboved** [octobercms/october#4344]
- OctoberCMS Build: 455
- PHP Version: 7.1.9
- Database Engine: MySQL

### Description:
Nested Repeater does not work if it has **only one** repeater field. For example, I have a "Content" Repeater. This repeater has another "Blocks" Repeater inside it.
```
    content:
        label: Content
        type: repeater
        form:
            fields:
                blocks:
                    label: Blocks
                    type: repeater
                    form:
                        fields:
                            title:
                                label: Description
                                type: textarea

```
When I try to add Block I get this error:

> "A widget with class name 'formContentForm0Blocks' has not been bound to the controller" on line 598 of \modules\backend\classes\Controller.php

Here is a screenshot:
![image](https://user-images.githubusercontent.com/9253603/58339452-503b6a80-7e52-11e9-80df-315e5ec56c64.png)

But if "Content" Repeater has more fields, I don't have this error. For example, I added "Name" field to "Content" Repeater:
```
    content:
        label: Content
        type: repeater
        form:
            fields:
                name:
                    label: Name
                    type: text
                blocks:
                    label: Blocks
                    type: repeater
                    form:
                        fields:
                            title:
                                label: Description
                                type: textarea
```
There is no error:
![image](https://user-images.githubusercontent.com/9253603/58340084-b4126300-7e53-11e9-813b-ce580baa78c5.png)

I also noticed that we will have the error if we use `radio` field type instead of `text` field type in the previous example. For example, in this case we will have the error:
```
    content:
        label: Content
        type: repeater
        form:
            fields:
                position:
                    label: Position
                    type: radio
                    options:
                        left: Left
                        center: Center
                        right: Right
                blocks:
                    label: Blocks
                    type: repeater
                    form:
                        fields:
                            title:
                                label: Description
                                type: textarea
```

### Steps To Reproduce:
Create a "content" column in your table. Add it to the `$jsonable` array in your model. Add my first example to the `fields.yaml` and try to add Content and Blocks items in the Repeater. You will get an error. After that add my second example to the `fields.yaml` and try to add Content and Blocks items in the Repeater. You will not get any errors.
