### ISSUE TITLE
Hard to see the code editor buttons

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4392]
Either my eye sight is going, or this is not correct?

See screenshot:

![aaa](https://user-images.githubusercontent.com/17784082/59785427-a9b18080-92bc-11e9-8e1d-df08e81be2f9.png)

Changing CSS value:

```css
.field-codeeditor .editor-toolbar >ul >li >a {
    display: block;
    height: 25px;
    width: 25px;
    color: #ececec;
    font-size: 20px;
    text-align: center;
    text-decoration: none;
}
```

Putting the two CSS values through my custom plugin tool in October I get the following results:

![Untitled](https://user-images.githubusercontent.com/17784082/59676739-21e64c00-91c0-11e9-887e-a3b091d77699.png)

Passed AA Level.

New screenshot:

![Untitled](https://user-images.githubusercontent.com/17784082/59676793-40e4de00-91c0-11e9-946c-bd35b8b0f34b.png)

That's how I came up with the new value.

I will try to create a PR for this when my other one gets tested and merged.

I really hope I don't get some issue with the CSS compiler 👎 

Files to edit:

https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/codeeditor/assets/css/codeeditor.css

https://github.com/octobercms/october/blob/master/modules/backend/formwidgets/codeeditor/assets/less/codeeditor.less

Side note: Add a custom id attribute here to lock the CSS to only that one web page and not the rest of the CMS: https://github.com/octobercms/october/blob/7590dfd30fb08242c6c8e111115659d38ac4aeb8/modules/cms/controllers/index/index.htm#L17

`id="cms-master-tabs"` will work. 🥇

**Comment by w20k** [comment]
@ayumihamsaki I'd go with the same color as a left side text: `#919898`, but then the hover is incorrect 😄

**Comment by ayumihamsaki** [comment]
Will do:

```css
#cms-master-tabs .field-codeeditor .editor-toolbar > ul > li > a {
    color: #919898;
}
```
