### ISSUE TITLE
List tables are not prefixed

### ISSUE THREAD

**Issue by daftspunk** [octobercms/october#442]
SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'cnesmeteo_user_users' (SQL: select `cnesmeteo_user_certifications`.*, cnesmeteo_user_users.last_name as `userID`, cnesmeteo_user_users.last_name as `checkerID` from `cnesmeteo_user_certifications` left join `cnesmeteo_user_users` on `cnesmeteo_user_users`.`id` = `cnesmeteo_user_certifications`.`user_id` left join `cnesmeteo_user_users` on `cnesmeteo_user_users`.`id` = `cnesmeteo_user_certifications`.`checker_id` group by `cnesmeteo_user_certifications`.`id` order by `userID` desc)

Model

```
class Certification extends Model
{
    /**
     * @var array Relations
     */
    public $belongsTo = [
        'user' => ['CnesMeteo\User\Models\User', 'table' => 'cnesmeteo_user_certifications', 'foreignKey' => 'user_id'],
        'checker' => ['CnesMeteo\User\Models\User', 'table' => 'cnesmeteo_user_certifications', 'foreignKey' => 'checker_id']
    ];
}
```

Yaml:

```


# ===================================
#  YAML (Column Definitions)
# ===================================

columns:
    userID:
        label: User
        relation: user
        select: @last_name
        searchable: true

    checkerID:
        label: Checker
        relation: checker
        select: @last_name
        searchable: true

    certified:
        label: Certified
        type: switch

    updated_at:
        label: Last updated
        type: datetime
        format: dd/M/Y

```
