### ISSUE TITLE
The CSS combiner destroys certain calc rules

### ISSUE THREAD

**Issue by tobias-kuendig** [octobercms/october#4438]
We use [lostgrid.org](http://lostgrid.org) extensively in our projects. For a certain time now we have been experiencing problems with the combiner (I cannot pinpoint the exact October version that introduced this bug).

lost-grid generates rules like this:

```css
.header {
    width: calc(99.9% * 1/1 - 0px); /* the rule for a 1/1 or full-width column */
}
```

When this rule is passed through October's combiner it ends up as 

```css
.header {
    width: calc(99.9% * 1/1 - 0); /* the px unit is missing */
}
```

Because of the `- 0` without a unit the rule becomes invalid CSS and is ignored by the browser. 

It seems like the optimization is not happending for all `calc` calls as these test cases show:

```css
body {
    width: calc(99.9% * 1/1 - 0px);
    width: calc(99.9% * 0px * 1/1 - 0px);
    width: calc(0px * 1/1 - 0px);
    width: calc(0px * 100% - 0px);
    width: calc(0px * 100%);
}
```

becomes

```css
body {
    width: calc(99.9% * 1/1 - 0);         /* X */
    width: calc(99.9% * 0 * 1/1 - 0);     /* X */
    width: calc(0px * 1/1 - 0);           /* X */
    width: calc(0px * 100% - 0);          /* X */
    width: calc(0px * 100%);
}
```

to reproduce paste the css rules above in a css file and include it using

```twig
<link href="{{ ['assets/css/test.css'] | theme }}" rel="stylesheet">
```
