### ISSUE TITLE
Model 'freezes' relation state accross multiple instances being used with relation widget

### ISSUE THREAD

**Issue by amorphine** [octobercms/october#4474]
- OctoberCMS Build: 457
- PHP Version: 7.3
- Database Engine: MySQL 5.7

### Description:
There are two models Problem and Topic:
```
class Problem extends Model
{
    public $belongsTo = [
        'topic' =>  [ProblemScopeTopic::class, 'key' => 'topic_id']
    ];

    public function getNameWithTopicTitleAttribute() {
        return ($this->topic ? $this->topic->title : 'No topic') . ' - ' . $this->title;
    }
}
```
```
class ProblemScopeTopic extends Model
{
    public $hasMany = [
        'problems' => [Problem::class, 'key' => 'topic_id'],
    ];
}
```

There's a model X related to Problem. I need to show a dropdown list with problems in format _'ProblemTopicTitle - ProblemTitle_'. Configuring backend field list:

```
fields:
    problem:
        label: Уточнение
        type: relation
        nameFrom: nameWithTopicTitle
        emptyOption: Not bound to problem
```
What actially happens: at _getNameWithTopicTitleAttribute()_ method _$this->topic_ is always the same topic which has been instantiated the first time method ran. While debugging I discovered for the first time _$this->relations_ is an empty array. But since _$this->topic_ is executed all next method calls _$this->relations_ is instantiated with the same value.
