### ISSUE TITLE
Focus Ring on the codeeditor search for no matches

### ISSUE THREAD

**Issue by ayumihamsaki** [octobercms/october#4482]
I found a small bug, which right now produces two different colored focus rings in the search box in the cms page, see screenshot:

![hard-to-see](https://user-images.githubusercontent.com/17784082/61968889-0cd7b680-afd1-11e9-8025-8bf05a339c29.png)

Adding the following CSS:

```css
.ace_search_form.ace_nomatch input.ace_search_field {
    border: .0625rem solid red;
    -webkit-box-shadow: 0 0 .1875rem .125rem red;
    box-shadow: 0 0 .1875rem .125rem red;
    z-index: 1;
    position: relative;
}
```

Gives me the following:

![ezgif-2-d9ae378b1109](https://user-images.githubusercontent.com/17784082/61969093-97b8b100-afd1-11e9-99fc-bb3fda02d93a.gif)

Now we have a focus ring that is blue, when the word is there and changes to red when the word is not there!
