### ISSUE TITLE
Setting page and sidebar

### ISSUE THREAD

**Issue by ghost** [octobercms/october#4505]
I'm opening this github issue, to try and learn and better understand what the heck is going on with this: `sidenav-tree-root` class.

I need to find out what it's main purpose is in October?

It seems to be some stupid thing! So I am banging my head on the wall asking myself why is it there and what it's main purpose is?

I want to remove it totally out of October!

Here is what it's doing in the setting page:

![seee](https://user-images.githubusercontent.com/17784082/62225910-37e74f00-b3b1-11e9-8f16-d06bfc3ab91e.png)

If there is no good reason for having this class, I plan to do the following things:

1. Totally remove `sidenav-tree-root` class.

2. Fix the Settings sidebar `sidenav-tree` class.

By removing all the repeated and conflicting media queries:

End up having just this clean setup:

```css
@media only screen and (min-width: 400px) {
    .sidenav-tree {
        width: 300px;
    }
}
@media only screen and (max-width: 400px) {
    .sidenav-tree {
        width: 80vw;
    }
}
```

There is so much junk in this issue in the CSS and the LESS.

But I need to know what's the purpose of the `sidenav-tree-root` class before I remove it totally. For now I don't understand why it's there?

How to reproduce this stupid class:

- Open the settings page but make sure your top naivgation settings are set to: `Inline`

The other settings don't seem to try and inject this stupid class into October.

p.s. It's probably causing this issue as well: https://github.com/octobercms/october/issues/4052#issuecomment-453822232

----

This bit of code is stupid, I don't understand why someone has tried to merge the two classes into one: `sidenav-tree-root` class and this `sidenav-tree` class.

Here is two reasons why I think it's dumb:

1. 

![seee1](https://user-images.githubusercontent.com/17784082/62227263-75e57280-b3b3-11e9-8797-55c880ebfe5d.png)

2.

![seee2](https://user-images.githubusercontent.com/17784082/62227357-acbb8880-b3b3-11e9-929e-3d85da174743.png)

Here's a quick example of the sidebar all over the place:

![ezgif-2-d504a9fcdc92](https://user-images.githubusercontent.com/17784082/61581531-63e41400-ab17-11e9-8a02-57b372faba4c.gif)

Note: The above gif has been cleaned up by me and the code in October right now produces even worse results - just try it and see for yourself.

Lastly, here's some of the media query mess which is no good:

```css
@media (min-width: 1200px) {
    .sidenav-tree-root .sidenav-tree {
        width: 900px;
    }
}
@media (min-width: 768px) {
    .sidenav-tree-root .sidenav-tree {
        width: 600px;
    }
}
@media (max-width: 991px) and (min-width: 768px) {
    .sidenav-tree-root .sidenav-tree {
        width: 100%;
    }
}
@media (max-width: 768px) {
    .sidenav-tree-root .sidenav-tree {
        width: 100% !important;
        height: 100% !important;
        display: table-cell !important;
    }
}
@media (max-width: 768px) {
    .sidenav-tree {
        width: 100%;
        height: auto !important;
        display: block !important;
    }
}
.sidenav-tree {
    width: 300px;
}
```

Lastly, I got a really bad feeling all this junk is being injected in by javascript. For example see this:

![seee22](https://user-images.githubusercontent.com/17784082/62228768-39674600-b3b6-11e9-8004-a6727951be8f.png)

Issue at 960px screen width - just looks wrong:

![sq2](https://user-images.githubusercontent.com/17784082/62291975-2eb3bc00-b45d-11e9-9567-abfdedf47157.png)
