### ISSUE TITLE
dependsOn isn't triggred on relationManager update form

### ISSUE THREAD

**Issue by danielbidala** [octobercms/october#4625]
If I create, delete related (orderitem) record(s) with relationManager everythings working fine but if I update an existing one the filterFields method isn't called.

My _fields.yaml:

```
    orderitems:
        tab: Rendelés tételek
        span: full
        type: partial
        path: $/brightstaff/brighterp/controllers/orders/partials/_orderitems.htm
    price:
        tab: Rendelés tételek
        label: Nettó összesen
        span: full
        type: money
        mode: amountcurrency
        dependsOn: orderitems
```
