### ISSUE TITLE
Support multiple actions & multiple conditions for the Trigger API

### ISSUE THREAD

**Issue by haralake** [octobercms/october#4637]
- OctoberCMS Build: ### 458
- PHP Version: 7.3
- Database Engine: MySQL
- Plugins Installed:

### Description:
Trigger on empty value is not working when used with multiple values. 
```
                    options_field:
                        label: Link Type
                        type: dropdown
                        showSearch: false
                        emptyOption: -- Disabled --
                        span: left
                        options:
                            v1: Option 1
                            v2: Option 2
                    value1_field:
                        label: Link
                        type: text
                        span: right
                        trigger:
                            action: hide|empty
                            field: options_field
                            condition: value[v2][]
                    value2_field:
                        label: Link
                        type: text
                        span: right
                        trigger:
                            action: hide|empty
                            field: options_field
                            condition: value[v1][]
```

I'm using this yaml file with static pages backend fields. When empty option -- Disabled -- is selected in dropdown menu the fields are visible.The reason is because there are multiple condition values on fields. If you remove value v1 and v2 from trigger conditions and keep only empty value is working as expected.

### Steps To Reproduce:

1. Create a yaml file like the above
2. Select -- Disabled --
3. Fields must be hidden
4. The problem is that empty value [] on trigger conditions must be the only one to work properly. If there are multiple values is not working.
