### ISSUE TITLE
Ability to skip list view of relation manager for one-to-one relationships.

### ISSUE THREAD

**Issue by paishin** [octobercms/october#4656]
For one-to-one relationships it would be nice if we could just add the manage form in the parent form and be able to edit without having to open the popup.

This works if you set the form in view settings of the config_relation.yaml but it is read-only and you have to click 'update' to make changes.

config_relation.yaml :
```
auction:
    label: '.'
    view:
        form: $/dp/properties/models/auction/fields.yaml
        toolbarButtons: update
    manage:
        form: $/dp/properties/models/auction/fields.yaml
```
