### ISSUE TITLE
Make relation form type's select portable

### ISSUE THREAD

**Issue by multiwebinc** [octobercms/october#4670]
I am creating a plugin and followed [the documentation](https://octobercms.com/docs/backend/forms#widget-relation) to create my model's `fields.yaml` file with the following `relation` type:

```
fields:
    cars:
        label: 'Available cars'
        span: auto
        type: relation
        select: concat(year, ' ', make , ' ' , model)
```

However since I'm using sqlite, I get an error:

> SQLSTATE[HY000]: General error: 1 no such function: concat (SQL: select "id", concat(year, ' ', make , ' ' , model) AS selection from "example_cars_cars" order by "name" asc)

So I therefore need to change it to:

    select: year || ' ' || make || ' ' || model

Since I think that a concatenation function in this context would be very common, what about defining one so that if sqlite is being used, it will transform `concat(year, ' ', make , ' ' , model)` into `year || ' ' || make || ' ' || model`, so that switching between database types (e.g. moving from dev to production) wouldn't be as much of an issue.
