### ISSUE TITLE
Disabled/Enabled event triggers not working with NestedForm widget

### ISSUE THREAD

**Issue by paishin** [octobercms/october#4675]
- OctoberCMS Build: 458 
- PHP Version: 7.1

### Description:
There is an issue when setting 'enable' trigger on NestedForm widget where the form does not get disabled when related field changes value.

This is very strange because setting the trigger action to 'show' does hide the form (but still gets submitted when saving thus in must not get disabled).
Also, setting disabled attribute to true in yaml does disable the form. This leads me to think that the issue must be related to Javascript.

### Steps To Reproduce:
Here is the form yaml file I am using
```
        auction:
            tab: Auction Details
            span: full
            type: nestedform
            form: $/dp/properties/models/auction/fields.yaml
            trigger:
                action: enable
                field: listingType
                condition: 'value[AUCTION]'
```
