### ISSUE TITLE
The theme dependencies feature doesn't work

### ISSUE THREAD

**Issue by lautsevich** [octobercms/october#4728]
- OctoberCMS Build: v1.0.459
- PHP Version: 7.2
- Database Engine: MySQL
- Plugins Installed: no plugins installed

### Description:

Official documentation [describes](https://octobercms.com/docs/themes/development#dependencies) `require` option in the `theme.yaml` file. It says:

>When the theme is installed for the first time, the system will attempt to install the required plugins at the same time.

We and our customers found that it's not working. For example, our [Bootstrap for Shopaholic theme](https://octobercms.com/theme/lovata-bootstrap-shopaholic) `theme.yaml` file content is as follows:

```yml
name: 'Free E-Commerce Bootstrap for Shopaholic'
description: ''
author: Lovata
homepage: ''
code: 'bootstrap-shopaholic'
form: config/fields.yaml
require:
    - RainLab.Pages
    - Lovata.Shopaholic
    - Lovata.Toolbox
```
But the installation of theme _Bootstrap for Shopaholic theme_ doesn't lead to the installation of required plugins. The same problem exists with the paid [Sneakers E-Commerce Theme for Shopaholic](https://octobercms.com/theme/lovata-shopaholic-sneakers) theme.

### Steps To Reproduce:
* Install a new copy of October;
* Install a _Bootstrap for Shopaholic theme_ theme;
* Check for installed plugins.
