### ISSUE TITLE
Editing soft deleted child from relation manager

### ISSUE THREAD

**Issue by nizzac** [octobercms/october#4784]
- OctoberCMS Build: 458
- PHP Version: 7.2
- Database Engine: MySQL

### Description:

Clicking on a soft deleted entry in a relation manager list gives an error...

![image](https://user-images.githubusercontent.com/12571713/69425542-052be280-0d23-11ea-95b4-56c42861eaad.png)

### Steps To Reproduce:
- Create a plugin
- Create 2 models for this plugin, Booking and Attendee
- Add the soft delete trait to theme
- Add database tables (with deleted_at columns
- Define columns.yaml and fields.yaml etc... for these models
- Set up relation *Booking belongsToMany Attendees* with scope `withTrashed()`
- Implement relation behavior tand define $relationConfig property on Bookings controller 
- Setup bookings config_relation.yaml as follows
```
attendees:
  label: Attendees
  view:
    toolbarButtons: create|add|remove
    list: $/author/plugin/models/attendee/columns.yaml
  manage:
    form: $/author/plugin/models/attendee/fields.yaml
```
- Create an attendee
- Create a booking
- Go to attendees list 
- Delete an attendee (Do not remove it from the booking)
- Go back to booking
- Click on the now soft deleted attendee
- You should now see the error `Call to member function getId() on null` 

### Expected Behavior
I'd expect one of three things to happen.
1. Don't allow the soft deleted entries in the relation manager list to be clickable.
2. If the soft deleted item is clicked, show a popup that it can't be edited because it's been deleted / or can't be found
3. Load the soft deleted item into the popup form / Act as though it not been deleted
