### ISSUE TITLE
Browser client side validation not running on backend forms

### ISSUE THREAD

**Issue by multiwebinc** [octobercms/october#4799]
If I have the following yaml for a plugin's registered settings:

```
tabs:
    fields:
        your_age:
            label: Your Age
            type: number
            step: 1  # defaults to 'any'
            min: 1   # defaults to not present
            max: 100 # defaults to not present
```

This does not perform any validation; either client-side (using [form data validation](https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation)) or server-side. In the example above, I can submit any number (e.g. -1000, 0, 1000) and it will save it to the database. I also tried sending a string in the HTTP request, but this gets cast to `0`.
