### ISSUE TITLE
Lists widget hasMany relation columns should show count

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#480]
hasMany relation are currently showing a comma delimited list of related records. More often than not, we'd want to show a count value instead.
## Example Use Case

I have a **Manufacturer** model that hasMany **products**. If I have 100 products attached to my model, the _Products_ column is so long it's unreadable.

I think the only way to show a count at the moment is with

``` yaml
product_count:
    label: Products
    type: number
    select: (SELECT COUNT(1) FROM my_plugin_products WHERE manufacturer_id = my_plugin_manufacturers.id)
```

but this isn't ideal, as it could potentially break DBs other than MySQL.
## Proposal

Either change the default relation for *Many relations to a count value or add a `displays: names|count` column option so we can choose what to show out of the two common scenarios.

I believe changing the default to count is a preferred solution, as this will likely be what the developer is looking for more often than not.
