### ISSUE TITLE
Upload Error - Division by zero

### ISSUE THREAD

**Issue by Nvironmental** [octobercms/october#4810]
Hi there, 

I am trying to upload a csv as part of the import ( I have created import functionality for own plugin, however I wanted to check whether did made mistakes in my code so I also installed  [User import/export](https://octobercms.com/plugin/vojtasvoboda-userimportexport) plugin to check)
I am getting the same error (as in the following image attached) when i try to upload a csv either through my plugin or through the above mentioned plugin. 

Please help me guide to diagnose this error.

![Screenshot 2019-12-07 at 10 58 35 PM](https://user-images.githubusercontent.com/31243747/70378460-9cf61700-1946-11ea-8409-017d26163a5d.png)

**Comment by w20k** [comment]
Hi, could you paste here your error logs it might give us a hint what's happening in there?

**Comment by Nvironmental** [comment]
Sure, below is the the is shared log file (as txt).  However would like to point out that I don't think it logs any errors as such particular to this task. 
Also, noticed that the file does get added to database in the `system_files` table (below is the attached screenshot
![Screenshot 2019-12-08 at 12 22 59 PM](https://user-images.githubusercontent.com/31243747/70385732-fa757c80-19b5-11ea-9e4f-a5d37f9cee6a.png)
)
[system.txt](https://github.com/octobercms/october/files/3935949/system.txt)

**Comment by bennothommo** [comment]
@Nvironmental Would you mind also providing the CSV you are trying to upload as well (feel free to strip out or replace any sensitive data in there)?

**Comment by Nvironmental** [comment]
Sure.
I can't seem to upload it here directly as github won't accept csv file type.
Here is the link to the [file](https://gofile.io/?c=dKHHXQ)

**Comment by w20k** [comment]
@Nvironmental could you also show your import/export yml file?
Found one line in your stack trace: ` file config_import_export.yaml defined for Backend\Behaviors\ImportExportController.`
It might be relevant.

**Comment by Nvironmental** [comment]
Sure.  Here is the code in my `config_import_export.yaml` file.

```
# ===================================
#  Import/Export Behavior Config
# ===================================

import:
    title: Import Thoughts
    modelClass: Mantiseye\Thoughts\Models\ThoughtImport
    list: $/mantiseye/thoughts/models/thought/columns.yaml

export:
    title: Export Thoughts
    modelClass: Mantiseye\Thoughts\Models\ThoughtExport
    list: $/mantiseye/thoughts/models/thought/columns.yaml
```

[Here](https://gofile.io/?c=SpTw9s) is the link to the actual yaml file just for reference.
