### ISSUE TITLE
Can't add nested FileUpload widget to a form

### ISSUE THREAD

**Issue by Flynsarmy** [octobercms/october#485]
When using a field `defaultOptions[images]` in my _fields.yaml_ I'm getting the error

> Call to undefined method Illuminate\Database\Query\Builder::defaultOptions[images]()

The issue is in _/modules/backend/formwidgets/FileUpload.php_ line 69. You're calling `$this->model->$columnName()` but in this case `$columnName` is _defaultOptions[images]_.
## Steps to Replicate

With the YAML in Product model:

``` yaml
defaultOptions[images]:
    label: Images
    type: fileupload
    mode: image
    image-width: 240
    image-height: 110
```

and a model definition of

``` php
// Product
public $belongsTo = [
    'defaultOptions' => ['My\Plugin\Models\ProductOMRecord', 'foreignKey' => 'default_om_id']
];

// ProductOMRecord
public $attachMany = [
    'images' => ['System\Models\File', 'order' => 'sort_order'],
];
```
