### ISSUE TITLE
How to write underscore for ace codeeditor language 

### ISSUE THREAD

**Issue by ayumi-cloud** [octobercms/october#4888]
I will jump straight into it, take the following example:

```yaml
css_content:
    type: codeeditor
    size: huge
    language: apache_conf
```

The parser won't allow `_` so what would be a good suggestion to get around this ?

Link to resource: https://cloud9-sdk.readme.io/docs/language-mode

[edit] I already know you can't escape underscores.
