### ISSUE TITLE
Search in list in Settings menu not working for model using SimpleTree trait

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#4945]
- OctoberCMS Build: 464
- PHP Version: 7.2

### Steps To Reproduce:

I have the following setup:
- a model Certificate using the SimpleTree trait
- a Certificates controller and list setup to be displayed in the Settings Menu
- the default search in the list does not happen

no trace here, as it should be.

```php
public function listExtendQuery($query)
{
    trace_log($query->toSql());
}
```

**Comment by chrisvidal** [comment]
and the sorting setup in `config_list.yaml' is not working as well.

**Comment by bennothommo** [comment]
@chrisvidal Would you please be able to provide the config you are using for the list?

**Comment by chrisvidal** [comment]
the `config_list.yaml`

```yaml
list: $/voilaah/astar/models/capability/columns.yaml
modelClass: Voilaah\Astar\Models\Capability
title: Capabilities
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'voilaah/astar/capabilities/update/:id'
defaultSort:
    column: name
    direction: asc
showTree: true
```
