### ISSUE TITLE
UI issue for Filter Type:switch not displayed as expected on Windows 10 Ent. / Chrome 79

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#4948]
- OctoberCMS Build: 464
- PHP Version: 7.2
- Plugins Installed: Rainlab.User

### Description:

Referring the Rainlab.User Users List and Filter.

```yaml
    activated:
        # Filter name
        label: rainlab.user::lang.user.status_activated
        # Filter type
        type: switch
        # SQL conditions
        conditions:
            - is_activated = '0'
            - is_activated = '1'
```

on MacOs, one click on the filter checkix 'Activated' looks like this
![Screenshot 2020-02-19 15 30 41](https://user-images.githubusercontent.com/2263496/74811611-ceb73100-532c-11ea-91c2-7cec62262bcc.png)

On Windows 10 Entreprise 2018 / Google Chrome: 79.0.3945.130 (Official Build) (64 bit), the checkbox does not change his look (no minus sign), although the filtering of the list is happening.
![Screenshot 2020-02-19 15 31 17](https://user-images.githubusercontent.com/2263496/74811658-e5f61e80-532c-11ea-9226-1c22ad2acb8b.png)
