### ISSUE TITLE
List Controller Filter with nestedtree model is not working

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#5019]
- OctoberCMS Build: #465
- PHP Version: 7.3

### Description:

In a list controller, I have a filter setup

```yaml
scopes:

   capability:

        # Filter name
        label: voilaah.astar::lang.capability.name

        # Model Class name
        modelClass: Voilaah\Astar\Models\Capability

        # Model attribute to display for the name
        nameFrom: name

        # Apply query scope
        scope: FilterCapabilities
```

the model `Capacity` is using a `nestedtree` trait.

in the backend list, I can't seem to be able to filter by capacity.

The `Apply` and `Clear` button appears randomly.
So far I didn't find the conditions of appearance of the `apply` button.
