### ISSUE TITLE
empty Jsonable fields save data in the database

### ISSUE THREAD

**Issue by faselunare** [octobercms/october#5020]
- OctoberCMS Build: 465
- PHP Version: PHP 7.1.14
- Database Engine: mysql  Ver 15.1 Distrib 10.3.22-MariaDB

### Description:
I'm developing a custom plugin and i found a possible bug referenced by another usere here in the forum

https://octobercms.com/forum/post/jsonable-repeater-fields-saving-empty-arrays?page=1#post-30651

Empty jsonable fields save in database an empty array ([])
and if you have a richeditor, it save this {"resource_note":"\r\n"}

in this way i'm not able to check on the frontend if the fields is empty or not

this is part of the form

```
resource:
            type: nestedform
            usePanelStyles: true
            tab: Resource
            form:
                fields:
                    resource_links:
                        label: Links
                        span: left
                        type: repeater
                        tab: Steps
                        form:
                            fields:
                                links:
                                    label: 'Links'
                                    span: full
                                    type: nestedform
                                    form:
                                        fields:
                                            title:
                                                label: Title
                                                span: left
                                                type: text
                                            url:
                                                label: Url
                                                span: right
                                                type: text
                                            icon:
                                                label: Icon
                                                type: awesomeiconslist
                                                unicodeValue: false
                                                emptyOption: false
                                                placeholder: Select Icon
                                                span: left
                    resource_image:
                        label: Image
                        type: fileupload
                        mode: image
                        span: right
                    resource_files:
                        label: Files
                        type: fileupload
                        mode: file
                        span: left
                        fileTypes: zip, pdf, html, htm
                    resource_note:
                        label: 'note'
                        size: ''
                        span: right
                        type: richeditor
```
