### ISSUE TITLE
SASS compiler fails to compile `rgba(#xxx, yy)` value with php 7.4

### ISSUE THREAD

**Issue by TimFoerster** [octobercms/october#5058]
- OctoberCMS Build: dev-master
- PHP Version: 7.4

### Description:
SASS file with
```
#header {
   background-color: rgba(#333, 0.99);
}
```
should compile with php 7.4, but fails

related to https://github.com/leafo/scssphp/pull/710

waiting for https://github.com/assetic-php/assetic/tree/2.0/dev migration?

**Comment by LukeTowers** [comment]
@TimFoerster please try switching to the Laravel 6 branch and let us know if it's still a problem there.

**Comment by XIOLog** [comment]
I have some problem

**Comment by XIOLog** [comment]
I`m switched to the Laravel 6 branch and a problem still remains

**Comment by rwcorbett** [comment]
for what it's worth it seems to be only that particular CSS function not compiling... I tested these:

```
$red1: #ff0000;
$red2: #ff00007c;
.journeyChoosePathBtns  {
    button {
        // background: red !important;                  // WORKS
        // background: $red1 !important;                // WORKS
        // background: $red2 !important;                // WORKS
        // background: rgba(200,0,0,0.9) !important;    // WORKS
        // background: rgb(200,0,0) !important;         // WORKS
        // background: rgba(#ff0000,0.9) !important;    // does not compile
        // background: rgba(#f00,0.9) !important;       // does not compile
        // background: rgba($red1,0.9) !important;      // does not compile
    }
}
```

**Comment by LukeTowers** [comment]
@Jaxwilko if you're feeling bored maybe you could take a look at this?

**Comment by jaxwilko** [comment]
@rwcorbett when I add your code to a file then include it with:

```html
<link href="{{ ['assets/scss/test.scss']|theme }}" rel="stylesheet">
```
The output is:

```css
.journeyChoosePathBtns button {
  background: red !important;
  background: #ff0000 !important;
  background: #ff00007c !important;
  background: rgba(200, 0, 0, 0.9) !important;
  background: #c80000 !important;
  background: rgba(255, 0, 0, 0.9) !important;
  background: rgba(255, 0, 0, 0.9) !important;
  background: rgba(255, 0, 0, 0.9) !important; }
```

In both php7.3 & php7.4

Could you give me a pointer in how to replicate the issue?

**Comment by rwcorbett** [comment]
Okay let me clarify - we were using this method of calling the stylesheet:
```php
<?php
function onStart() {
    $this->addCss(['assets/scss/test.scss']);
}
?>
```

Also please note the specific syntax of the SASS `rgba` function being called `rgba( $color, $alpha);` (see [HERE](https://sass-lang.com/documentation/modules#rgb) for reference).

This is the format that does not work:
```scss
.journeyChoosePathBtns  {
    button {
        background: rgba(#ff0000,0.9) !important;
    }
}

```
test.scss ==> [test.zip](https://github.com/octobercms/october/files/5342991/test.zip)

In your code you are using the 4 param `rgba` functions. However, when there are only 2 params being passed and something is not parsing that syntax.

Is this due to the SASS lib being used? 'Dart Sass' vs 'LibSass' vs 'Ruby Sass'?
