### ISSUE TITLE
Nestedform widget not translatable (e.g. when used with static pages)

### ISSUE THREAD

**Issue by Cobyheart** [octobercms/october#5111]
- OctoberCMS Build: ### 465
- PHP Version: 7.3

- Plugins Installed:  
rainlab.pages-v1.3.3
rainlab.translate-v1.6.7

### Description:
Using a nestedFrom form widget in a static page layout should provide translatable fields in the static pages plugin. Which is not the case. 

### Steps To Reproduce:
Create a yaml in your theme folder e.g.
```
fields:
    section_demo:
        type: repeater
        prompt: Add Item
        form:
            fields:
                section_demo_text:
                        label: demotext
                        type: text
                        span: right
```

Create a layout for a static page. 
Add a nestedForm
```
{variable name="demo" type="nestedform" form="~/themes/yourTheme/file.yaml" tab="demo" }
{/variable}
```
Create a static page with the layout. You will find that unlike using the repeater with groups no language picker is available.

To display the form properly you might need to fix the css to display the nestedForm fields correctly,  or recompile the core style files after adding `:not( .nested-form)` to the styles for the `.fancy-layout .form-tabless-fields` selector.   

### Solution: 
Register a MLnestedForm widget in the translate plugin. I tried to create and register the widget following the content of the MLRepeater.php , but couldn't really get it to work.

Probably somebody with more experience needs to take a look at it or hint me at what needs to be done. 

I'm not an experienced october/laravel dev so this is what I did:
 
create MLNestedForm.php (based on the MLRepeater)
create a widget folder with the .htm (same as in the nestedForm widget in core)
register in translate/plugin.php
add to /classes/EventRegistry.php

But somehow even when I remove MLNestedForm.php october doesn't complain about the missing widget. So I'm clearly missing something.
