### ISSUE TITLE
Builder - Plugin - Seed error when version selected

### ISSUE THREAD

**Issue by pablorq** [octobercms/october#5121]
- OctoberCMS Build: 465 
- PHP Version:  7.2.31
- Database Engine: mysql (docker) 
- Plugins Installed: 
rainlab/debugbar
rainlab/builder

### Description:

When a seed php file is created and added to plugins version file, you get an error when try to apply that version.

The error is:
`'Version file /var/www/html/plugins/[user]/[plugin]/updates/seed_cards.php is not found.'`

I'm using Docker on Windows 10, with the plugin directory mapped to the local filesystem as a volume.

### Steps To Reproduce:

- Create the docker stack with the following docker-compose file.

<details>
<summary>docker-compose.yml</summary>

```
version: '2.2'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=octobercms

  web:
    image: aspendigital/octobercms:latest
    init: true
    restart: always
    ports:
      - 8000:80
    environment:
      - TZ=Europe/Madrid
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_DATABASE=octobercms
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
#      - ./.env:/var/www/html/.env
      - ./html/config:/var/www/html/config
      - ./html/plugins:/var/www/html/plugins
      - ./html/storage:/var/www/html/storage
      - ./html/themes:/var/www/html/themes
```

</details>

- Add developing plugins: Builder, Debugbar.
- Create a new plugin named [plugin].
- Create a new database table.
- Manually create a seeder file:

<details>
<summary>seed_cards.php</summary>

```
<?php namespace [user]\[plugin]\Updates;

use October\Rain\Database\Updates\Seeder;
use [user]\[plugin]\Models\Card;

class SeedCards extends Seeder
{
	    public function run()
    {
        if (Card::count() > 0) {
            return;
        }

        Card::insert([
			['name' => 'name1', 'code' => 'aa', 'description' => ''],
			['name' => 'name2', 'code' => 'bb', 'description' => ''],
			['name' => 'name3', 'code' => 'cc', 'description' => '']
        ]);
		
	}
	
}
```

</details>

- Manually added the seeding to the plugins version file:

<details>
<summary>seed_cards.php</summary>

```
1.0.3:
    - 'Add Cards'
    - seed_cards.php
```

</details>

- In Builder plugin, select `Versions` option.
- Click on `1.0.3` version.
- The error is shown:
`'Version file /var/www/html/plugins/[user]/[plugin]/updates/seed_cards.php is not found.'`
