### ISSUE TITLE
SASS compiler fails to compile `rgba(#xxx, yy)` value with php 7.4

### ISSUE THREAD

**Issue by XIOLog** [octobercms/october#5193]
- OctoberCMS Build: master
- PHP Version: 7.4
- Database Engine: MariaDB

### Description:
SASS file with

``` scss
&__overlay {
    background-color: rgba($link, 0.95);
}
```

I had an error:
```
/* Trying to access array offset on value of type null */
```

I have switched to the Laravel 6 branch (wip/laravel-6), but the problem still remains.
