### ISSUE TITLE
Client-side form validation can break setting model forms

### ISSUE THREAD

**Issue by jimcottrell** [octobercms/october#5239]
- OctoberCMS Build: 467 
- PHP Version: 7.2

### Description:

Not sure that client-side form validation was completely thought through, even with #5088. Any settings form that has been using the `required` flag for fields that might be hidden would be broken in 467.

### Steps To Reproduce:

Create a placeholder settings model with the following form fields YAML:

```
tabs:
    fields:
        field1:
            type: checkbox
            label: Optional field on tab 1
            tab: Tab 1

        field2:
            label: Required Field
            type: text
            required: true
            tab: Tab 2
```

Without doing anything, attempt to save the settings. This silently fails, but you can see the following console error from the hidden field's attempted client-side validation check:

 ![Screen Shot 2020-08-14 at 3 31 34 PM](https://user-images.githubusercontent.com/1483197/90294274-48932780-de43-11ea-898c-e94333c3e812.png)

It seems like settings models should at least only use client-side validation if opting in to that behavior. And presumably the `required` form field config needs to be updated to mention that it affects validation and is no longer UI-only in 467+.
