### ISSUE TITLE
search mode is not working in lists

### ISSUE THREAD

**Issue by mabehiry** [octobercms/october#5241]
When setting search mode in config_list.yaml, nothing changes!
This is how my file looks like:
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
        mode: exact
But I get the results that contain all the word

**Comment by daftspunk** [comment]
Check to make sure at least one list column.yaml has `searchable: true` set

**Comment by mabehiry** [comment]
Yes it is set

**Comment by bennothommo** [comment]
@mabehiry Would you mind providing us with your `columns.yaml` configuration for the model used in the list, as well as a sample of the results and the query you used in the search field?

**Comment by mabehiry** [comment]
This is the columns.yaml
```
columns:
    name:
        label: 'sunsoft.articles::lang.name'
        type: text
        searchable: true
        sortable: true
    slug:
        label: 'sunsoft.articles::lang.slug'
        type: text
        searchable: false
        sortable: true
```
And this is the query with results
![image](https://user-images.githubusercontent.com/33180080/91849719-1cb4d600-ec7a-11ea-9c3c-70754b990bde.png)
