### ISSUE TITLE
Cannot input Chinese characters in a TagList

### ISSUE THREAD

**Issue by boyardnicolas** [octobercms/october#5242]
- OctoberCMS Build: 467
- PHP Version: 7.4.5 and 7.4.9
- Database Engine: 5.7.29-0ubuntu0.18.04.1 and MariaDB 5.5.65
- Plugins Installed: 
    - Vldp-Redirect-v2.5.2
    - Rainlab-Page-v1.3.5
    - Rainlab-Builder-v1.0.26
    - Indikator.Backend-v1.6.12
    - Inetis.Dump-v.1.0.0
    - OFFLINE-SiteSearch-v.1.5.3
    - OFFLINE-ResponsiveImages-v2.3.6
    - Arcane-Seo-v1.1.20
    - Indikator-News-v1.1.18
    - ReazZon-Gutenberg-v1.3.2
    - Martin-Forms-v1.4.20
    - PeterHegman-SlickSlider-v1.1.2

### Description:
It seems impossible to type in Chinese with tag system because you can only type one letter before the possible options disappear (by "options" I'm not talking about tags autocompletion but the way typing in Chinese works). If I only input one letter, I can pick a character from the list and it is properly inserted in the input, as soon as I type the second letter the suggestions disappear.

### Steps To Reproduce:
Use Rainlab Builder plugin to create a Model including a TagList in the fields.yaml, like so:
```
tags:
        label: Tags
        nameFrom: name
        mode: relation
        relation: tags
        separator: comma
        customTags: true
        useKey: false
        span: auto
        type: taglist
```
Then try to type in with Chinese input system, tested on Mac 10.15.4 with Chrome 84.
