### ISSUE TITLE
RelationManager button delete exception build #468

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#5246]
Since the last build 468  update, the partial holding relation manager `button_delete` is raising an exception, in preview mode only; update mode is working fine

```
Undefined variable: text
/Users/christophevidal/Sites/oc-accm/modules/backend/Behaviors/relationcontroller/partials/_button_delete.htm line 24
```

**Comment by LukeTowers** [comment]
@chrisvidal could you `dd($buttonText)` here: https://github.com/octobercms/october/blob/develop/modules/backend/behaviors/RelationController.php#L1559 and show us what it outputs?

**Comment by chrisvidal** [comment]
result of `dd($buttonText)`

```php
array:4 [▼
  "create" => "backend::lang.relation.create_name"
  "add" => "backend::lang.relation.add_name"
  "delete" => "backend::lang.relation.delete"
  "remove" => "backend::lang.relation.remove"
]
```

**Comment by LukeTowers** [comment]
@chrisvidal can you post your config_relation.yaml? I'm unable to reproduce this.

**Comment by chrisvidal** [comment]
sure.

```yaml
# ===================================
#  Relation Behavior Config
# ===================================

groups:
    label: Interest Groups
    view:
        showSearch: true
        recordsPerPage: 25
        toolbarPartial: relation_toolbar
        list: $/voilaah/astar/models/group/columns.yaml
        recordUrl: voilaah/astar/groups/preview/:id

events:
    label: Events
    view:
        showSearch: true
        recordsPerPage: 25
        toolbarPartial: relation_toolbar
        list: $/voilaah/astar/models/event/columns.yaml
        recordUrl: voilaah/astar/events/preview/:id

proposals:
    label: Call-for-Proposals
    view:
        showSearch: true
        recordsPerPage: 25
        toolbarPartial: relation_toolbar
        list: $/voilaah/astar/models/rfq/columns.yaml
        recordUrl: voilaah/astar/rfqs/preview/:id

listings:
    label: Marketplace listings
    view:
        showSearch: true
        recordsPerPage: 25
        toolbarPartial: relation_toolbar
        list: $/voilaah/astar/models/marketplace/columns.yaml
        recordUrl: voilaah/astar/marketplaces/preview/:id

users:
    label: Users
    view:
        showSearch: true
        recordsPerPage: 25
        toolbarPartial: relation_toolbar
        list: $/voilaah/astar/models/rainlabuser/columns.yaml
        recordUrl: rainlab/user/users/preview/:id

```


and `relation_toolbar.htm`

```
<div data-control="toolbar">
    <?= $this->relationMakePartial('button_delete') ?>
</div>
```
