### ISSUE TITLE
Repeater item and parents dependsOn issue

### ISSUE THREAD

**Issue by SebastiaanKloos** [octobercms/october#5249]
- OctoberCMS Build: 468 
- PHP Version: 7.2

### Description:
While depending on repeater field from a field within the repeater fields, the js crashes when deleting a repeater item. 

``` yaml
step_fields:
    label: 'Vragen'
            type: repeater
            span: full
            form:
                fields:
                    question_trigger:
                        label: 'Toon vraag als'
                        type: dropdown
                        placeholder: 'Selecteer vraag'
                        span: storm
                        cssClass: col-sm-6
                        dependsOn: step_fields
                        trigger:
                            action: show
                            field: question_use_trigger
                            condition: checked
```

Produces this error when trying to delete a repeater:
<img width="455" alt="CleanShot 2020-08-25 at 15 28 42@2x" src="https://user-images.githubusercontent.com/6506510/91180219-c8dd4680-e6e7-11ea-8793-2890a3a289ff.png">

#### Fix
Flipping these two lines fixes the issue:
- https://github.com/octobercms/october/blob/0eac1290031224b68e82be4104a574f3f5ee107c/modules/backend/formwidgets/repeater/assets/js/repeater.js#L134

- https://github.com/octobercms/october/blob/0eac1290031224b68e82be4104a574f3f5ee107c/modules/backend/formwidgets/repeater/assets/js/repeater.js#L135

I was wondering why the change event is called before the item is deleted. Is there something expecting this event before deleting the item?

If not, then I would like to suggest flipping these lines.  If needed, I can provide a PR.

### Steps To Reproduce:
See above
