### ISSUE TITLE
Getting password fields returns encrypted empty string instead of empty string when blank

### ISSUE THREAD

**Issue by code-po8** [octobercms/october#5250]
- OctoberCMS Build: 468
- PHP Version: 7.1
- Database Engine: MariaDB
- Plugins Installed: N/A

### Description:
I have a settings model with password fields.  In the past (I don't recall which version of October), I have had to check if the password field was left blank and repopulate the value from originals.  I used `$this->get('stored_password') == ''` to check.  After upgrading October to 468, the get method now returns the encrypted cipher for an empty string instead of the empty string.

I now have to attempt to decrypt the value each time to check if it's empty before restoring.  I've also decoded the attribute directly from JSON (since it's a system settings model) and it is encrypted there too.  I also tried using `$this->getEncryptableValue('stored_password')` but that throws an index error.

### Steps To Reproduce:
1. Create a simple system settings model (i.e. `System.Behaviors.SettingsModel`) with an encryptable password field (`October\Rain\Database\Traits\Encryptable;`).
2. Save the settings with a password supplied.
3. Re-render the settings controller form and save without entering a password.
4. The beforeSave function will show the encrypted version of an empty string for the field when it didn't prior to upgrading to 468.

**Comment by bennothommo** [comment]
@code-po8 this is intentional - see https://github.com/octobercms/library/pull/499.

An empty value - like 0 or an empty string - can be legitimate values that need to be encrypted. If you want to store an *absence* of an encrypted value, you should store the field as `null` instead.

Also, you should be able to access the attribute directly and it will be decrypted on the fly - eg. `$model->stored_password`. That's the intention of the trait.

**Comment by code-po8** [comment]
`$this->stored_password` returns null in my beforeSave whether or not I leave the stored_password field blank on the form.

**Comment by LukeTowers** [comment]
@code-po8 please post the code for your model.

**Comment by code-po8** [comment]
Heavily redacted, so let me know if I messed something up.

Settings.php (model):
```
<?php namespace Domain\Plugin\Models;

use Crypt;
use Model;

/**
 * Settings Model
 */
class Settings extends Model {

    use \October\Rain\Database\Traits\Encryptable;

    public $implement = ['System.Behaviors.SettingsModel'];

    //a unique code
    public $settingsCode = 'domain_plugin_settings';

    //Reference to field configuration
    public $settingsFields = 'fields.yaml';

    /**
     * @var array Guarded fields
     */
    protected $guarded = ['*'];

    /**
     * @var array Fillable fields
     */
    protected $fillable = [];

    /**
     * @var array List of attributes to encrypt.
     */
    protected $encryptable = [
        'arbitrary_field_1',
        'arbitrary_field_2',
        'stored_password',
        'stored_password_2'
    ];

    /**
     * @var array Relations
     */
    public $hasOne = [];
    public $hasMany = [];
    public $belongsTo = [];
    public $belongsToMany = [];
    public $morphTo = [];
    public $morphOne = [];
    public $morphMany = [];
    public $attachOne = [];
    public $attachMany = [];

    
    /**
     * Performs actions before saving.
     * Hooks into the Model save "event flow".
     *
     * @return void
     */
    public function beforeSave()
    {
        if (!empty($this->original) && !empty($this->original['value'])) {
            $originalValuesJSON = $this->original['value'];
            $originalValues = json_decode($originalValuesJSON);
            $values = json_decode($this->attributes['value'], true);
            dd(
                Crypt::decrypt($originalValues->stored_password),
                Crypt::decrypt($this->get('stored_password')),
                Crypt::decrypt($values['stored_password']),
                $this->isDirty('stored_password'),
                $this->stored_password
            );
        }
    }
}

```

fields.yaml
```
# ===================================
#  Form Field Definitions
# ===================================

fields:
    arbitrary_field_1:
        label: Arbitrary Field 1
        span: left
    arbitrary_field_2:
        label: Arbitrary Field 2
        span: left
    stored_password:
        label: Stored Password
        type: password
        placeholder: Leave blank to retain previous value
        span: left
    stored_password_2:
        label: Stored Password 2
        type: password
        placeholder: Leave blank to retain previous value
        span: left
```
