### ISSUE TITLE
`Master` and `Content` tabs are not connected to the yaml files

### ISSUE THREAD

**Issue by summercms** [octobercms/october#5251]
October has 4 tabs: https://octobercms.com/docs/ui/tab

Yaml file code seems to only allow: `Primary` and `Secondary` only and I cant seem to find the code for the `Master` and `Content`.

Code examples:

```
tabs:
    fields:
        text1:
            label: Text
            span: auto
            type: text
            tab: 'Tab 1'
```

and

```
secondaryTabs:
    fields:
        text1:
            label: Text
            span: auto
            type: text
            tab: 'Tab 1'
```

Above both work - however!

```
masterTabs:
    fields:
        text1:
            label: Text
            span: auto
            type: text
            tab: 'Tab 1'
```

and

```
contentTabs:
    fields:
        text1:
            label: Text
            span: auto
            type: text
            tab: 'Tab 1'
```

Do not work - maybe I am missing something here?

**Comment by LukeTowers** [comment]
YAML fields are handled by the Form widget, which supports outside fields, tabs, and secondaryTabs (https://octobercms.com/docs/backend/forms#form-tab-options). The tabs that you linked are different visual ways of displaying tabs, that you have to decide to implement the markup for yourself: https://github.com/octobercms/october/blob/develop/modules/system/controllers/mailtemplates/index.htm

**Comment by summercms** [comment]
@LukeTowers 

Luke I mean, why cant we just modify this file: https://github.com/octobercms/october/blob/develop/modules/backend/widgets/form/partials/_form.htm

and have something like this:

```php
<?php if ($outsideTabs->hasFields()): ?>
    <?= $this->makePartial('section', ['tabs' => $outsideTabs]) ?>
<?php endif ?>

<?php if ($primaryTabs->hasFields()): ?>
    <?= $this->makePartial('section', ['tabs' => $primaryTabs]) ?>
<?php endif ?>

<?php if ($secondaryTabs->hasFields()): ?>
    <?= $this->makePartial('section', ['tabs' => $secondaryTabs]) ?>
<?php endif ?>

<?php if ($masterTabs->hasFields()): ?>
    <?= $this->makePartial('section', ['tabs' => $masterTabs]) ?>
<?php endif ?>

<?php if ($contentTabs->hasFields()): ?>
    <?= $this->makePartial('section', ['tabs' => $contentTabs]) ?>
<?php endif ?>
```

etc.

**Comment by LukeTowers** [comment]
That's tying the organizational structure of the Form widget to the presentational structure of the different tab types.

**Comment by summercms** [comment]
Yah why we cant code out these october core files to allow the 4 tab types to get fully integrated into the yaml files instead of coding `hacks` to inject the extra two tabs into the form widgets.

If they were added to the yaml files it would take a user a **few seconds** to add it into the yaml file - yet the current setup is to instead use a `hack` method and add it via html/php code (which takes minutes to create, instead of seconds).

Really makes no sense to me!

**Comment by daftspunk** [comment]
Three sets of tabs was generally seen as enough to meet 99% of use cases. Can you explain your use case a little more?

**Comment by summercms** [comment]
@daftspunk Sure I can explain a use case, for my reasons:

The `content` tabs are **responsive** and useful for a long list of tabbed items, for example:

![image](https://user-images.githubusercontent.com/57409060/91556337-7475d900-e92a-11ea-89b1-7ffe9d10f734.png)

> Above: The tabs are all display on an ipad device and not hidden for quick and easy access.

Whereas if we used the `Primary` or `Secondary` tabs the **long** list of tabs, that would hide some of the tabs and make them extend out of the screen, needing to be dragged into view.

Working on the principle of good user experience we can take the same example with the `hamburger` menu. User experience drops off when the designer starts to hide menu items! Whereas if you removed the `hamburger` menu and switched to a `tabbed` menu instead the user experience is improved and the click through rate increases. You can learn more here: https://uxplanet.org/the-ultimate-guide-to-the-hamburger-menu-and-its-alternatives-e2da8dc7f1db

Making the developer life easier with October, instead of having to waste time hard coded a html method to achieve this, it would be great just to be able to write a few characters in the `.yaml` file instead - thus saving time.

For example:

```
contentTabs:
    fields:
        text1:
            label: Text
            span: auto
            type: text
            tab: 'Tab 1'
        text2:
            label: Text
            span: auto
            type: text
            tab: 'Tab 2'
```

There is also an extra benefit for doing all this. The tabs are lazy loaded in the core now with the following pr's:

- https://github.com/octobercms/october/pull/4658

- https://github.com/octobercms/october/pull/4839

So the benefits would be:

1. Quick developer time using yaml instead of creating custom html code.

2. `Content` and `Master` tabs could also be lazy loaded like `primary` and `secondary`.

3. Better user experience on smaller screen resolutions.

etc.
