### ISSUE TITLE
Repeater field `minItems: 1` not showing the first entry

### ISSUE THREAD

**Issue by summercms** [octobercms/october#5274]
- OctoberCMS Build: 468

### Description:

It was working fine in previous cms versions. Now is not working in all test plugins.

### Steps To Reproduce:

In our tests we created a repeater field under a `primary` tabs section for example:

```
tabs:
    fields:
        example:
            label: 'Widgets'
            prompt: 'Test'
            size: huge
            span: full
            required: 1
            type: repeater
            minItems: 1
            tab: 'Test 1'
            form:
                fields:
                    blue_widget:
                        label: 'Blue Widget'
                        span: left
                        type: text
                    red_widget:
                        label: 'Red Widget'
                        span: right
                        type: text
```

### Expected results

To be showing the first repeater field.

### Received results

Currently hiding the first repeater field.

Using the `minItems: 1` should force the cms to display the first repeater field entry.

Link: https://octobercms.com/docs/backend/forms#widget-repeater
