### ISSUE TITLE
Datatable throws js errors in relation modal

### ISSUE THREAD

**Issue by Samuell1** [octobercms/october#5276]
- OctoberCMS Build: 458
- PHP Version: 7.3

### Description:
When datatable is added to relation and relation modal is open to edit or add it throws error to clicking in datatable dropdown option.

`Uncaught TypeError: can't access property "tagName", item is null`

### Steps To Reproduce:
```
    statements:
        label: Test
        type: datatable
        columns:
            operation:
                title: Operations
                type: dropdown
                options:
                    'false': False
                    'true': True
            value:
                title: Názov
                type: dropdown
                options:
                    1: Option 1
                    2: Option 2
```
