### ISSUE TITLE
Form setting for Input.trigger.js does not accept null

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#5301]
When in your form setting is something like this:
```
trigger:
    action: disable
    field: common_text_or_number_field
    condition: value[]
```
...everything works as expected. `""` value is compared with empty text field `""` and result is **true**.

But in this case:
```
trigger:
    action: disable
    field: dropdown_field
    condition: value[]
```
... `""` is compared with `null` returned by dropdown and result is **false**.

I did not find way how to impose `null` to form field condition setting.

### Possible solution
When Input.trigger.js `self.triggerConditionValue` contains `""`, add automatically `null` value too.
