### ISSUE TITLE
Component's title hangs out of container due to styling error

### ISSUE THREAD

**Issue by summercms** [octobercms/october#5368]
Latest October version

Screenshot showing error:

![image](https://user-images.githubusercontent.com/57409060/100542062-d56dbf80-323f-11eb-9af3-a0a4856cd957.png)

Screenshot showing fix:

![image](https://user-images.githubusercontent.com/57409060/100542095-fdf5b980-323f-11eb-8d76-bf465a34a418.png)

Note: The part saying `This is an example title hanging out` is where the error is taking place.

Code line:

```
/modules/cms/assets/css/october.components.css?v469:79
```

CSS Code:

```css
.draggable-component-item > div span.name, .component-list .components div.layout-cell > div span.name, div.control-componentlist div.components div.layout-cell > div span.name {
    /* white-space: nowrap; */
    padding: 8px 15px 0;
    font-weight: 400;
    line-height: 20px;
    font-size: 13px;
}
```

Turning off the `nowrap` fixes the problem.
