### ISSUE TITLE
Placeholder text hidden in form widget `number` type

### ISSUE THREAD

**Issue by summercms** [octobercms/october#5397]
Take this example:

![image](https://user-images.githubusercontent.com/57409060/101926798-92123a00-3bcb-11eb-9d70-cec907881f4c.png)

The placeholder says `e.g. 10` - however, the `10` is hidden behind the increment counter.

Adding some css fixes the issue:

![image](https://user-images.githubusercontent.com/57409060/101926942-c84fb980-3bcb-11eb-8969-b0116aa1be65.png)

Would like to add the css as standard to the backend.

```css
.form-widget input[type=number]::-webkit-input-placeholder {
    margin-right: 20px;
}
.form-widget input[type=number]::-moz-placeholder {
    margin-right: 20px;
}
.form-widget input[type=number]::-ms-input-placeholder {
    margin-right: 20px;
}
.form-widget input[type=number]::placeholder {
    margin-right: 20px;
}
```

I wait for permission from admins first.

**Comment by LukeTowers** [comment]
This isn't specific to all browsers, chrome on Mac OS hides the number buttons until you actually click on the field itself. Would require tests on all browsers, perhaps it's something we do behind a `:focus` selector as well?

**Comment by summercms** [comment]
With regards to the `:focus` selector, here is a `.gif` demo'ing my css fix:

![ezgif-7-fb631739d5ca](https://user-images.githubusercontent.com/57409060/101958764-df0e0480-3bfb-11eb-904e-82a33421e4ec.gif)

```css
.form-widget input[type=number]::placeholder {
    margin-right: 20px;
}
```

The above `.gif` shows what happens in Google Canary on Windows 10 - when I hover over the `number` input field with the injected css fix.

---

Browser testing - Would it be a good idea to create a test `number` field in the test plugin with the css injected into it via a hidden `partials` field. Then people could test it on various browsers or just create a pr and people test from that?

Was thinking of adding the css into the `normalize` less file location: https://github.com/octobercms/october/blob/develop/modules/system/assets/ui/less/site.normalize.less

**Comment by LukeTowers** [comment]
@ayumi-cloud the problem is the extra space on the right even when the number selector isn't there; hence why I suggested the addition of the focus and / or hover selectors

**Comment by ayumi-cloud** [comment]
@LukeTowers 

Tried this in several browsers and it doesn't seem to work?

```css
.form-widget input[type=number]:focus::-webkit-input-placeholder {
    margin-right: 20px;
}
.form-widget input[type=number]:focus::-moz-placeholder {
    margin-right: 20px;
}
.form-widget input[type=number]:focus:-ms-input-placeholder {
    margin-right: 20px;
}
.form-widget input[type=number]:focus::placeholder {
    margin-right: 20px;
}
```

Not sure why?

**Comment by ayumi-cloud** [comment]
@LukeTowers 

Doesn't seem to work as intended, using the following test code:

```css
input[type=number]:focus::-webkit-input-placeholder {
    margin-right: 20px;
}
input[type=number]:focus::-moz-placeholder {
    margin-right: 20px;
}
input[type=number]:focus:-ms-input-placeholder {
    margin-right: 20px;
}
input[type=number]:focus::placeholder {
    margin-right: 20px;
}
```

![1](https://user-images.githubusercontent.com/57409060/101961904-a9b8e500-3c02-11eb-87ba-3d5670b116d5.gif)

Above: Mouse hovering over field (no mouse clicking) - **placeholder is still hidden** (method doesn't work!)

![2](https://user-images.githubusercontent.com/57409060/101961988-e1c02800-3c02-11eb-8694-51f10ae22ef2.gif)

Above: Mouse moving over field and clicking the field - **placeholder moves into place**, but user needs to click inside and outside the field to move the placeholder.

Conclusion:

I think there has to be an extra space shown as the `:focus` doesn't seem to be a good solution.

**Comment by summercms** [comment]
Combination of `:focus` and `:hover` would probably work:

### :focus

```css
input[type=number]:focus::-webkit-input-placeholder {
    margin-right: 20px;
}
input[type=number]:focus::-moz-placeholder {
    margin-right: 20px;
}
input[type=number]:focus:-ms-input-placeholder {
    margin-right: 20px;
}
input[type=number]:focus::placeholder {
    margin-right: 20px;
}
```

![2](https://user-images.githubusercontent.com/57409060/101961988-e1c02800-3c02-11eb-8694-51f10ae22ef2.gif)

### :hover

```css
input[type=number]:hover::-webkit-input-placeholder {
    margin-right: 20px;
}
input[type=number]:hover::-moz-placeholder {
    margin-right: 20px;
}
input[type=number]:hover:-ms-input-placeholder {
    margin-right: 20px;
}
input[type=number]:hover::placeholder {
    margin-right: 20px;
}
```

![ezgif-7-105aff33b34e](https://user-images.githubusercontent.com/57409060/101966929-906b6500-3c11-11eb-91bc-4b061cbd15b9.gif)

Yah works fine using this combination! 👍 

![3](https://user-images.githubusercontent.com/57409060/101967009-f0faa200-3c11-11eb-92fe-604a664ffbf3.gif)

I'll code the pr tomorrow.
