### ISSUE TITLE
MSSQL 2019, Windows Server 2019

### ISSUE THREAD

**Issue by chrisvidal** [octobercms/october#5403]
- OctoberCMS Build: ##471
- PHP Version: 7.4
- Database Engine: Microsfot MSSQL 2019

From the Admnistrators menu in the backend, when trying to filter by `Super User`,

`
"SQLSTATE[42S22]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'false'. (SQL: select count(*) as aggregate from [backend_users] where is_superuser = false and [backend_users].[deleted_at] is null)" on line 664 of D:\STTC\vendor\laravel\framework\src\Illuminate\Database\Connection.php
`

**Comment by chrisvidal** [comment]
Has this been updated somehow?

**Comment by LukeTowers** [comment]
@bennothommo was this dealt with?

**Comment by bennothommo** [comment]
@LukeTowers I can't recall if this specific instance was resolved or not. I'll have to double check.

**Comment by daftspunk** [comment]
Hey @chrisvidal, this should be resolved by changing the true/false values to 0/1 inside the file `modules\backend\controllers\users\config_filter.yaml`

```
    is_superuser:
        label: backend::lang.user.superuser
        type: switch
        conditions:
            - is_superuser = 0
            - is_superuser = 1
```

I've made this code change for the next release. If this doesn't help, just ping me and we can reopen this issue. Thanks 🙏
