### ISSUE TITLE
Backend client code should match server code

### ISSUE THREAD

**Issue by multiwebinc** [octobercms/october#5419]
I am trying to create a backend form where the `publish_date` form element will be shown and its value sent to the server and used to update the model if and only if the `_publish_later` field is in the `on` state.

When I do the following in my fields.yaml,

```yaml
    _publish_later:
        label:  Publish later
        span: full
        type: switch
        default: false
    publish_date:
        label: Publish date
        mode: datetime
        type: datepicker
        hidden: true
        trigger:
            action: show
            field: _publish_later
            condition: checked
```

this does **not** show the field when `_publish_later` is turned on. In fact, looking at the page source, the form element is not even output to the page at all. I would expect it to be output, but hidden so that the trigger can make it display.

If I **remove** the `hidden: true` attribute the field is rendered, like this:

```yaml
    _publish_later:
        label:  Publish later
        span: full
        type: switch
        default: false
    publish_date:
        label: Publish date
        mode: datetime
        type: datepicker
        hidden: true
        trigger:
            action: show
            field: _publish_later
            condition: checked
```

However now the `publish_date` field's data gets saved even when the field is hidden by the trigger. I would expect it should be ignored, since the [docs](https://octobercms.com/docs/backend/forms#form-field-options) say that the `hidden` attribute "hides the field from the view and **excludes it from the saved data**".

My next idea was to instead set the field to `disabled`, and then have the trigger both show and enable it, like this:

```yaml
    _publish_later:
        label:  Publish later
        span: full
        type: switch
        default: false
    publish_date:
        label: Publish date
        mode: datetime
        type: datepicker
        disabled: true
        trigger:
            action: show|enable
            field: _publish_later
            condition: checked
```

However even though the new value of `publish_date` is submitted with the request, it is ignored when updating the model.

I have a feeling that the server-side code only looks at the disabled/hidden attributes in the yaml file and ignores whether the trigger is currently true or false. So basically the triggers only update the actual HTML/CSS attributes of the elements.

The only way I could figure out to get this seemingly simple task to work was to bind to the `'model.beforeSave'` event in the controller, which to me is rather obscure and over-complicated:

```php
    public function __construct()
    {
        MyModel::extend(function($model) {
            $model->bindEvent('model.beforeSave', function () use ($model) {
                if (request('MyModel')['_publish_later'] == '0') {
                    unset($model->publish_date);
                }
            });
        });
        parent::__construct();
    }
```

Wouldn't it be better to make the server and client-side behavior match each other, so if the trigger is set to true for the client it will be for the server as well? And wouldn't it be better for the `hidden` attribute to output the element to the HTML in a hidden state so that it can be un-hidden by the trigger and therefore have its value updated by the server?
