### ISSUE TITLE
Form trigger enable/disable/empty actions do not affect checkboxlist

### ISSUE THREAD

**Issue by Rike-cz** [octobercms/october#5420]
- OctoberCMS Build: 1.1.1
- PHP Version: 7.4

### Description:
Form trigger enable/disable/empty actions do not affect checkboxlist. Some visual manipulation expected but nothing happen.
![checkboxlist](https://user-images.githubusercontent.com/4247582/102719345-d6998600-42ed-11eb-8be3-8ba29600feef.gif)

### Steps To Reproduce:
Add to aby of your field.yaml file:
```
is_enabled:
    label: Check for enable
    type: switch
    default: true
        
list:
    label: Checkboxlist
    type: checkboxlist
    options:
        - Test1
        - Test2
        - Test3
    trigger:
        action: enable
        field: is_enabled
        condition: checked
```
