### ISSUE TITLE
Add form property to FileUpload FormWidget to configure the fields available on uploaded files

### ISSUE THREAD

**Issue by netsmertia** [octobercms/october#5440]
I need to provide some custom fields on fileupload (as image attachment) and found a solution by extending the backend forms [add options to file upload](https://octobertricks.com/tricks/add-options-to-file-model-and-backend-form).
This solution match what I thought initially but creates one more relation just to add one field. Or if I reverse this by adding a model that have custom fields and image attachment create one more issue of losing multi uploads.

I also found that we are using a fields.yaml to render form in config form and we have hard coded that config in `FileUpload.php`
```
    /**
     * Get the instantiated config Form widget
     *
     * @return void
     */
    public function getConfigFormWidget()
    {
        if ($this->configFormWidget) {
            return $this->configFormWidget;
        }

        $config = $this->makeConfig('~/modules/system/models/file/fields.yaml');
        $config->model = $this->getFileRecord() ?: $this->getRelationModel();
        $config->alias = $this->alias . $this->defaultAlias;
        $config->arrayName = $this->getFieldName();

        $widget = $this->makeWidget(Form::class, $config);
        $widget->bindToController();

        return $this->configFormWidget = $widget;
    }
```

As I am already using a separate table for storing these attachments by extending File Model, It would be much easier if this config can be passed through fileupload form widget config
```
        plans:
            label: nets.estate::lang.floor_plans
            type: fileupload
            configForm: 'my-config-fields.yaml'
            tab: Plans
            required: true
            mode: image
            imageHeight: 260
            imageWidth: 260
            thumbOptions:
                mode: crop
                offset:
                    - 0
                    - 0
                quality: 90
                sharpen: 0
                interlace: false
                extension: auto
```
