### ISSUE TITLE
Datepicker type has the default maxDate value for 2020-12-31

### ISSUE THREAD

**Issue by prhost** [octobercms/october#5456]
It is not a serious problem, I just had to adjust the `maxDate` on old projects. But I believe it is a good time to update this default value.

For those who do not know how to solve, just edit all datepicker fields, and inform `maxDate`, for example:

```yaml
published_at:
   label: Published At
   type: datepicker
   maxDate: 2025-12-31
   span : right
```

If this has already been resolved in newer versions just update the documentation.
https://octobercms.com/docs/backend/forms#widget-datepicker
