### ISSUE TITLE
Field Dependencies

### ISSUE THREAD

**Issue by xyz1123581321** [octobercms/october#5483]
Hello. I have two fields, and If I try to make them dependent on each other, 1 field doesn't update its value

```
Quantity
Packages
quantity:
   label: Quantity 
   span: auto 
   dependsOn:
       packages 
   type: text 
packages: 
   label: Packages 
   span: auto 
   dependsOn:
       quantity 
   type: text

```
When I input quantity, I need to update the number of packages (packages = quantity / items_in_a_package) When I input packages, I need to update the quantity of products (quantity = packages * items_in_a_package)

These two fields are dependent on each other, but the thing is that doesent work. Any idea?

`public function filterFields($fields, $context = null) { if($fields->packages->value != "") { $fields->quantity->value = doubleval($fields->_package->value) * doubleval($fields->packages->value); } if($fields->quantity->value != "") { $fields->packages->value = doubleval($fields->quantity->value) / doubleval($fields->_package->value); } }`
