### ISSUE TITLE
ReadOnly Sensitive Form Field

### ISSUE THREAD

**Issue by seanthepottingshed** [octobercms/october#5538]
- OctoberCMS Build: Latest
- PHP Version: 7.2
- Database Engine: mysql
- Plugins Installed: N/A

### Description
Setting a `sensitive` form field to `readOnly` doesn't stop the display of the password when clicking the view button.

### Steps To Reproduce:
And the following to `fields.yaml`:

```yaml
test_api_key:
    label: Test API key
    placeholder: Enter key
    type: sensitive
    readOnly: true
```
