### ISSUE TITLE
Repeater groups not working on Tailor blueprints

### ISSUE THREAD

**Issue by fgschafer** [octobercms/october#5678]
I can create the grups and the UI works perfectly and saves the data.  But not being able to bring the data into twig.  No error.  I attach the blueprint and also the page markup below.  I'm not able to get the groups _group property or anything else inside the repeater.  Using latest 3.1.26 version and SQLite.
```
uuid: 3e01029d-5be1-4434-969e-6c6b8226879b
handle: Servicios
type: structure
name: Servicios
drafts: false

structure:
    maxDepth: 1
showImport: false
showExport: false
customMessages: 
    buttonCreate: Nuevo Servicio


primaryNavigation:
    label: Servicios
    icon: icon-cog
    order: 109

fields:
    title:
        placeholder: Título del servicio
    content:
        label: Contenido
        type: richeditor
        column: false
        tab: Contenido General
    icono:
        label: Icono del servicio
        type: fileupload
        mode: image
        maxFiles: 1
        tab: Contenido General
    contenido_avanzado:
        label: Contenido del Servicio
        type: repeater
        tab: Contenido Avanzado
        prompt: Agregar contenido
        displayMode: builder
        groupKeyFrom: _group
        groups:
            contenido:
                icon: icon-file-text-o
                name: Contenido
                description: Contenido en general
                fields:
                    contenido:
                        label: Contenido
                        type: richeditor
                        size: huge
            caracteristicas:
                name: Características
                icon: icon-file-text-o
                description: Lista de características
                fields:
                    caracteristicas:
                        label: Características
                        type: repeater
                        propmpt: Agregar característica
                        form:
                            fields:
                                titulo:
                                    label: Título característica
                                contenido:
                                    label: Contenido característica
                                    type: textarea
            imagen:
                name: Imagen
                icon: icon-camera
                description: Bloque de Imagen
                fields:
                    imagen:
                        label: Imagen del Servicio
                        type: fileupload
                        mode: image
                        maxFiles: 1
```                        
```
url = "/servicios/:slug"
layout = "default"
title = "Single Servicio"

[section servicio]
handle = "Servicios"
entrySlug = "{{ :slug }}"
==
<?php
function onEnd(){
    $this->page->title = $this->servicio->title;  // the heading partial uses this
}
?>
==
{% partial 'heading' %}

<section class="single-servicio ptb">
    <div class="container">
        <div class="row">
            <div class="col-12">

                {{ servicio.content|raw }}
                {% if servicio.contenido_avanzado %}
                <h3>Contenido avanzado</h3>
                {% for bloque in servicio.contenido_avanzado %}
                     
                     {% if bloque._group == 'contenido' %}
                     <h2>este es el bloque contenido</h2>
                     <div class="bloque contenido">
                        {{ bloque.contenido|raw }}
                     </div>
                     {% endif %}
                     {% if bloque._group == 'caracteristicas' %}
                     {{ dump(bloque) }}
                     <h2>Caracterisitcas</h2>
                     <div class="bloque caracteristicas">
                        {% for caracteristica in bloque.caracteristicas %}
                            <p>{{ caracteristica.titulo }}</p>
                            <p>{{ caracteristica.contenido }}</p>
                        {% endfor %}
                        </div>
                     {% endif %}
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
</section>
```
