### ISSUE TITLE
Trigger based on taglist option

### ISSUE THREAD

**Issue by ssi-com-pl** [octobercms/october#5713]
I'm wondering if it's possible to display a field if the taglist has one of the options selected?

The code below doesn't work:
```
devices:
    label: Devices
    type: taglist
    options:
        mobile: mobile
        tablet: tablet
        desktop: desktop
mobile_size:
    label: Mobile size
    type: number
    trigger:
        action: show
        field: devices
        condition: value[mobile]
tablet_size:
    label: Tablet size
    type: number
    trigger:
        action: show
        field: devices
        condition: value[tablet]
```

**Comment by daftspunk** [comment]
Hi @ssi-com-pl 

Since the field results in an array, it needs to be `field: devices[]` as a reference.

For example,

```
mobile_size:
    label: Mobile size
    type: number
    trigger:
        action: show
        field: devices[]
        condition: value[mobile]
```

We've updated the documentation to make this clearer: https://github.com/octobercms/docs/commit/371dc6a061e1a320e085dcdc7bd53b1828072eec

I hope this helps!
