### ISSUE TITLE
Taglist explode error

### ISSUE THREAD

**Issue by ssi-com-pl** [octobercms/october#5742]
Hi! I get an error when using a taglist field with dynamic options:

![image](https://github.com/octobercms/october/assets/57666038/d442da2e-e4bc-4ba6-856b-3946438c9525)

Is something wrong in my code?

```
tags:
    label: 'Tags'
    type: taglist
    options: \My\Plugin\Models\Settings::customTagsOptions
    mode: string
    separator: space
    customTags: true
```

```
public static function customTagsOptions($model, $formField)
{
    $options = ['tag-1', 'tag-2','tag-3','tag4', 'tag5', 'tag6'];
    return $options;
}
```
