### ISSUE TITLE
Repeater with ExpandoModel doesn't delete the corresponding row, just clears the key value. 

### ISSUE THREAD

**Issue by Lazerproof** [octobercms/october#5746]
Hi.
I have a repeater field that works in 'relation mode'. The issue is that when I delete an item from the repeater field it doesn't remove the corresponding row in DB, but just clears the value of the key column. 

```
tabs:
    fields:
        variations:
            type: repeater
            displayMode: builder
            titleFrom: title
            groupKeyFrom: type
            groups:
                default:
                    name: Default
                    description: Default variaiton
                    fields:
                        title:
                            label: Title
                            type: text
```

```
class Product extends Model
{
    use \October\Rain\Database\Traits\Validation;

    public $hasMany = [
        'variations' => [
            ProductVariation::class,
            'key' => 'product_id',
            'delete' => true,
            'pivotSortable' => 'sort',
        ],
    ];
}
```

```
class ProductVariation extends ExpandoModel
{
    use \October\Rain\Database\Traits\Validation;
    use \October\Rain\Database\Traits\Sortable;

    public $implement = [
        \RainLab\Translate\Behaviors\TranslatableModel::class
    ];

    public $translatable = [
        'title',
    ];

    public $table = '..._product_variations';

    protected $expandoColumn = 'content';

    protected $expandoPassthru = [
        'product_id',
        'title',
        'sort',
        'created_at',
        'updated_at',
        'type'
    ];

    const SORT_ORDER = 'sort';

}
```
![image](https://github.com/octobercms/october/assets/5707348/838d81a0-eaf1-4bc2-aa09-d4289553c9a5)
