### ISSUE TITLE
The image in the preview mode in the relation controller is not updated after create new record

### ISSUE THREAD

**Issue by igor-tv** [octobercms/october#5748]
When a model has a relationship with another belongsTo model, if you create a new model through a relation controller, the thumbnails of the `fileupload` type fields are not updated.

Video demonstration:

https://github.com/octobercms/october/assets/6777469/590c54ec-453d-4b07-bda7-debfeb280890

OCMS v3.4

```
class CatalogPage extends Model
{
      // ...
      public $belongsTo = [
              'product_card_banner' => ProductCardBanner::class
      ];
      // ...
}
```

CatalogPage model's fields.yaml:
```
fields:
    is_active:
        label: 'is_active'
        type: switch
    title:
        label: 'title'
        type: text
    product_card_banner:
        label: 'product_card_banner'
        type: relation
        span: left
```

config_relation.yaml
```
product_card_banner:
    label: 'product_card_banner'
    form: $/vendor/banners/models/productcardbanner/fields.yaml
    list: $/vendor/banners/models/productcardbanner/columns.yaml
```
ProductCardBanner model's fields.yaml
```
fields:
    is_active:
        label: 'is_active'
        span: full
        type: switch
        default: 1
    title:
        label: 'title'
        span: full
        type: text
    url:
        label: 'url'
        span: full
        type: text
    image_desktop:
        label: 'image_desktop'
        mode: image
        fileTypes: 'png'
        useCaption: 0
        thumbOptions:
            mode: crop
            extension: auto
        span: full
        type: fileupload
```
