### ISSUE TITLE
Implement select For type: taglist

### ISSUE THREAD

**Issue by sqwk** [octobercms/october#5776]
When using a taglist field in relation mode, one cannot define a select: concat() like for the relation type.

```yaml
users:
    type: taglist
    mode: relation
    customTags: false
    keyFrom: id
    select: concat(first_name, ' ', last_name)
    useKey: true
```

This would be helpful when linking multiple authors/users/owners via a many to many relationship with the built in backend_users. type: relation  (checkboxes) works fine,  as does the list representation when using the relation manager, but both take up considerably more UI room than a simple taglist.
