### ISSUE TITLE
Unable to show Relation features in backend forms when nested

### ISSUE THREAD

**Issue by ccamarillo** [octobercms/october#5778]
I've been trying to use a relation.yml configuration to show the nice relationship interface, complete with sort_order drag-and-drop.  But within modal windows - inside another related modal window - inside a parent model's controller - I can't seem to get the right interface to display the related model.

The relationship structure is 
- product -> variant -> product_detail 
- product-> product_detail

<img width="1096" alt="image" src="https://github.com/octobercms/october/assets/538355/749d58f4-a9b9-455b-9e2a-557a97fbc177">

We're all good when in the parent window, in the tabs.

<img width="732" alt="image" src="https://github.com/octobercms/october/assets/538355/1c77fe15-3620-440e-9320-5b9aed046a5c">

Our relation config for the product:
```
details:
    label: 'Detail'
    structure:
        showTree: false
        showReorder: true
        dragRow: true
    view:
        list: $/xxx/xxx/models/productdetail/columns.yaml
        toolbarButtons: create|delete
    manage:
        list: $/xxx/xxx/models/productdetail/columns.yaml
        form: $/xxx/xxx/models/productdetail/fields.yaml
```        

For the variant:
```
details:
    label: 'Detail'
    structure:
        showTree: false
        showReorder: true
        dragRow: true
    view:
        list: $/xxx/xxx/models/productdetail/columns.yaml
        toolbarButtons: create|delete
    manage:
        list: $/xxx/xxx/models/productdetail/columns.yaml
        form: $/xxx/xxx/models/productdetail/fields.yaml
```

I've confirmed the sort_order column is there (works in the product -> product_detail relationship).  The relationships show correctly, just with the wrong interface.

We've run into enough that we thought you'd like to know - cheers!

Candace

**Comment by daftspunk** [comment]
Hey @ccamarillo !

We've added nested relation definitions in v3.6, it should be released very soon. Hopefully it will solve this issue, the timing is very good, if so. Here is an example:

```yaml
# Need a variant definition to go here...
variant: []

# Details through variant
variant[details]:
    label: 'Detail'
    structure:
        showTree: false
        showReorder: true
        dragRow: true
    view:
        list: $/xxx/xxx/models/productdetail/columns.yaml
        toolbarButtons: create|delete
    manage:
        list: $/xxx/xxx/models/productdetail/columns.yaml
        form: $/xxx/xxx/models/productdetail/fields.yaml

# Details through product
details:
    label: 'Detail'
    structure:
        showTree: false
        showReorder: true
        dragRow: true
    view:
        list: $/xxx/xxx/models/productdetail/columns.yaml
        toolbarButtons: create|delete
    manage:
        list: $/xxx/xxx/models/productdetail/columns.yaml
        form: $/xxx/xxx/models/productdetail/fields.yaml
```

Here's what we've added to the docs. It is designed to work in conjunction with the relation form widget with the `useController` property set to `true`. 

--- 

### Nested Definitions

The Relation Controller supports nesting relations, in other words, managing relations through relations. A nested relationship uses the standard field nesting syntax. For example, the `countries[cities]` relation definition makes the `cities` relationship available to manage through the `countries` relationship.

```yaml
countries:
    label: Country
    form: $/acme/location/models/country/fields.yaml
    list: $/acme/location/models/country/columns.yaml

countries[cities]:
    label: City
    form: $/acme/location/models/city/fields.yaml
    list: $/acme/location/models/city/columns.yaml
```

> **Tip**: Nested relation definitions are designed to work seamlessly with the [relation form widget](https://docs.octobercms.com/3.x/element/form/widget-relation.html), setting the `useController` property set to `true`.
