### ISSUE TITLE
Call to undefined method Backend\Widgets\Lists::setFormValues

### ISSUE THREAD

**Issue by wpluut** [octobercms/october#5793]
I have a model with a morphMany realtionship, called 'dates':

```
public $morphMany = [
    'dates' => [
        Date::class,
        'name'  => 'dateable',
        'order' => 'start'
    ]
];
```
    
In my fields.yaml file I render these 'dates' with a partial, like:

```
        dates:
            type: partial
            tab: Data
            context: update
```
            
 The partial only renders the relation (so nothing fancy):
 
 `<?= $this->relationRender('dates') ?>`
 
 This worked in OctoberCMS 3.5.x but the latest OctoberCMS version 3.6.11 gives the following error:
 
 `Call to undefined method Backend\Widgets\Lists::setFormValues`
 
 For now I have downgraded to the 3.5.x version. Do you have any ideas on what is wrong?
