### ISSUE TITLE
How to implement manage attaching and detaching nested relationships in OctoberCMS?

### ISSUE THREAD

**Issue by devmansurov** [octobercms/october#5796]
I looked at an [example here](https://octobercms.com/support/article/ob-21) for creating data using nested relationships, but I didn’t understand how to manage the attachment and detachment of nested relationship data.

How to create and make partials correctly in this case?

OctoberCMS version: 2.x (not 3.x)

**Comment by mrmaarek** [comment]
First of all; I would recommend you to update to the newest version.

As shown in the information you should just provide a partial type-field for example:

`models/customer/fields.yaml`

```
orders:
  label: Orders
  type: partial
  path: field_orders
```

It wil reference to the controller directory; in this case: `controllers/customers/_field_orders.htm`

`<?= $this->relationRender('orders') ?>`

Because the controller has access to the relation functionality (see `$implements`)
it will look up for the relation yaml file in: `controllers/customers/config_relation.yaml`

which will render the relation based on the configuration:

```
orders:
    label: Order
    view:
        list: $/acme/formist/models/order/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/acme/formist/models/order/fields.yaml
        list: $/acme/formist/models/order/columns.yaml
```
