### ISSUE TITLE
Tailor Permissions get grouped by name and not by parent navigation

### ISSUE THREAD

**Issue by sqwk** [octobercms/october#5804]
I have multiple tailor items named `Tag`. These are all grouped together in the permissions backend, even though they have different `uuid`, `handle` and `navigation.parent` options set.

```
name: Tag

navigation:
    label: Tags
    parent: Blog\Article
```

```
name: Tag

navigation:
    label: Tags
    parent: Foo\Bar
```

<img width="968" alt="Screenshot 2024-06-23 at 14 12 31" src="https://github.com/octobercms/october/assets/1353312/051dfae0-ca52-4ca8-a204-c6da90bf191a">

Shouldn't the permission be grouped by the name of the parent item?
