### ISSUE TITLE
Tailor Repeater field with minItems does not save

### ISSUE THREAD

**Issue by tombien** [octobercms/october#5816]
I have a blueprint with repeater with minItems defined - for example:
```
opening_hours:
    type: repeater
    minItems: 7
    maxItems: 7
    form:
        fields:
            day:
                type: text
            open_from:
                type: text
```
And it does not save when I fill pre-displayed fields.
It does not matter if minItems == maxItems or minItems < maxItems.
