### ISSUE TITLE
Backend fields select2 config

### ISSUE THREAD

**Issue by damnason** [octobercms/october#5821]
Can't configure select2 fields like:
```
fields:
    tags:
        label: 'Tags'
        type: taglist
        config:
            closeOnSelect: false
```

Can I? Is this an option?

**Comment by daftspunk** [comment]
Hi @damnason 

Unfortunately this config is not exposed in the taglist field or the select JS plugin.

Can you give us some more detail on why you would like this feature added?

**Comment by damnason** [comment]
I wanted to have the option, to keep my taglist open every time I select one item.

These are my field's options:
```
categories:
    label: Categories
    mode: relation
    separator: comma
    customTags: 0
    optionsMethod: getFilteredCategories
    useKey: false
    span: full
    dependsOn:
      - store
    type: taglist
```

It would be great to have all select2 functionality.
With "closeOnSelect: false" option, I could just select the categories like checkboxes type (no taglist). Fast and simple.

**Comment by pittss** [comment]
@damnason  Try adding the "attributes" property with the value "data-close-on-select: false".

Example:

```yaml
categories:
  type: taglist
  attributes:
    data-close-on-select: false
```

**Comment by daftspunk** [comment]
@pittss does that work? I checked the JS for the select and couldn't see the data attributes being passed to the select2 control...

**Comment by pittss** [comment]
@daftspunk  Select2 accepts these values (https://select2.org/configuration/data-attributes), and if I look at the JS, this is how it looks without the `data-close-on-select` attribute:
<img width="413" alt="1" src="https://github.com/user-attachments/assets/81669100-6df9-4d68-a0ec-d52ba80a7c24">

And this is how it looks with the `data-close-on-select` attribute:
<img width="401" alt="2" src="https://github.com/user-attachments/assets/8cade362-83b4-4f22-a46e-d463f6779bfe">


Also, in some projects, I've used the following in the dropdown:
```yaml
attributes:
  data-handler: onGetClientOptions
  data-minimum-input-length: 3
  data-process-Results: true
  data-ajax--delay: 300
```
