### ISSUE TITLE
Relation controller with dependsOn

### ISSUE THREAD

**Issue by pittss** [octobercms/october#5829]
**Hello,**

I’ve encountered strange behavior with the "relation controller / Belongs To / Morph One" when using `dependsOn`.

### Environment
Test environment: OctoberCMS 3.7.6 with the test-plugin.

### Issue
If you add `dependsOn: review` to the `content` field in `/plugins/october/test/models/post/fields.yaml`:

```yaml
    content:
        label: Content
        type: codeeditor
        size: huge
        tab: Code Editor
        # language: text
        commentAbove: Code editor field.
        dependsOn: review
```

And then navigate to a `post` record (for example, `https://localhost/admin/october/test/posts/update/1#primarytab-reviews`) and perform any operation on the `review` field (e.g., update, create, etc.), the `content` field enters an infinite loop (constantly refreshing). The only way to resolve this is to reload the page.

### Cause
It seems that if there are fields with identical names in different configurations, it causes this infinite loop. In this case, there are `content` fields in both:

- `/plugins/october/test/models/review/fields_simple.yaml`
- `/plugins/october/test/models/post/fields.yaml`

This appears to trigger the issue.
