### ISSUE TITLE
Tailor Collection Component no longer returns structured data after 4.0 update

### ISSUE THREAD

**Issue by aminusmin** [octobercms/october#5873]
After updating to OctoberCMS 4.0, previously working Tailor structure collections no longer behave as expected. Specifically:
	•	The collection component does not return any records unless explicitly queried via .where(...).get()
	•	The children attribute is missing from entries defined as structure

Before the Update (worked fine)

**Blueprint:**
```
handle: Pages\Page
type: structure
name: Page

drafts: false
multisite: sync
pagefinder: item

structure:
    maxDepth: 3
    treeExpanded: false
    showReorder: true
    showSorting: true
```

**Component in Layout:**
```
[collection pages]
handle = "Pages\Page"
==
{% for page in pages %}
    <h1>{{ page }}</h1>
{% endfor %}
```

**After the Update (no output)**

The component no longer loads the records. Dumping the component variable gives:
```
Tailor\Classes\ComponentVariable {#923 ▼
  #component: 
Tailor\Components
\
CollectionComponent
 {#924 ▶}
  #record: null
  +hasBlueprint: true
  #isRecordLoaded: false

```
However, the data can be retrieved manually like this:
`{% set pages = pages.where('is_enabled', true).get() %}`

**Missing children on structured entries**

Additionally, when the entry type is defined as structure, the children attribute is no longer present on the records returned, even though this used to be available before 4.0.

Expected Behavior
	•	The pages component variable should automatically return the structured collection as before
	•	children relationships should be present for structured entries

Environment
	•	OctoberCMS: v4.0.x
	•	PHP: 8.2

**Comment by thedoofus** [comment]
I'm having a similar issue. Previously I used the toNested() method on the collection, but this now returns null.

Blueprint
```
uuid: main_menu
handle: Menu\Main
type:  structure
name: Main Menu
drafts: false
pagefinder: false

navigation:
  icon: ph ph-align-top
  parent: Content\Page
  order: 210

extraNavigation:
    _menus_section:
        itemType: section
        label: Menus
        order: 200

structure:
  maxDepth: 3

customMessages:
  buttonCreate: New Menu Item

fields:

  page:
    type: pagefinder
    label: Page
    singleMode: true
    scope: false
```

My partial
```
[collection mainMenu]
handle = "Menu\Main"
==
{% set menu_items = mainMenu.get() %} 
This returns all entries - but not nested.

{% set menu_items = mainMenu.get().toNested() %} 
And this returns null - but works in v3.6
```
