### ISSUE TITLE
Tailor relation is not updating, when uncheking all the items

### ISSUE THREAD

**Issue by ShrikeFIN** [octobercms/october#5892]
Seems that 4.01 does not clear all the releation in Tailor, when none is selected. If I have 5 relations checked, all are updated fine in the database. When I remove all 5 (uncheck in the backend), there is still one left on the database. Tested it in 3.x and works as it should (no relations left).

Example:

```
handle: Events\Event
type: structure
name: Events
drafts: true
pagefinder: item

primaryNavigation:
    label: Events
    icon: icon-calendar-clock
    order: 95

navigation:
    icon: icon-calendar-clock
    order: 100

groups:
    regular_maincontent:
        name: Regular Post
        fields:
            content:
                tab: Edit
                label: Main content
                type: richeditor
                span: adaptive
                column: false
            event_addons:
                type: mixin
                source: Events\EventFields

    markdown_maincontent:
        name: Markdown Post
        fields:
            content:
                tab: Edit
                label: Main content
                type: markdown
                span: adaptive
                column: false
            event_addons:
                type: mixin
                source: Events\EventFields
```

```
handle: Events\EventFields
type: mixin
name: Event Fields

fields:
    event_setup:
        type: mixin
        name: Event Setup
        source: Events\EventSetup

```
```
handle: Events\EventSetup
type: mixin
name: Event Setup

fields:
    locations:
        tab: Location
        label: Location
        commentAbove: Select locations for this item belongs to
        type: entries
        source: Events\Location
        displayMode: relation
```

```
handle: Events\Location
type: structure
name: Locations

structure:
    maxDepth: 5

customMessages:
  buttonCreate: New Location

navigation:
    icon: icon-map-pin
    parent: Events\Event
    order: 150

fields:
    description:
        label: Location Description
```
