### ISSUE TITLE
Default value

### ISSUE THREAD

**Issue by Shahiem** [octobercms/october#642]
Is it possible to set a default value for a backend form field?  This is my code, but it doesn't work.

```
toolbar:
        label: BBcodes Toolbar
        tab: Editor
        type: textarea
        default: bold,italic,underline,strike,sup,sub,|,img,video,link,|,bullist,numlist,|,fontcolor,fontsize,fontfamily,|, justifyleft, justifycenter,justifyright,|, quote,code,table,removeFormat
        span: left
        comment: Enabled BBcodes. seperate it with a comma. 
```
