### ISSUE TITLE
Upload issue with IE11

### ISSUE THREAD

**Issue by alvaro-canepa** [octobercms/october#691]
The model has this relation

``` php
    public $attachMany = [
        'images' => ['System\Models\File', 'order' => 'sort_order']
    ];
```

The model fields.yaml

``` yaml
    images:
      tab: pronet.realestate::lang.global.tab.images
      type: fileupload
      mode: image
      context: update
      imageWidth: 200
      imageHeight: 200
```

Using IE 11 (I don't know if the issue affect others versions) the uploader works fine at first upload action. But, without refreshing the browser, after second click on upload button, prompt for files to upload, and after select files, the uploader doesn't receive nothing. I use the debug window (F12) to track the network requests  and nothing is send or received. 

From FF and Chrome it work fine. The problem only affect IE (like allways, someone please burn IE installations...)

Sorry if the issue description was not clear,  my english is not so good :(

thanks
