### ISSUE TITLE
Missing Partial

### ISSUE THREAD

**Issue by ghost** [octobercms/october#703]
Latest version 155 is missing the '_field_datepicker.htm' partial and is throwing Exceptions on all plugins that currently use it. This happened directly after updating and visiting ProBlog + others.

The partial '/home/pixelpix/public_html/modules/backend/widgets/form/partials/_field_datepicker.htm' is not found.

**Comment by jfoliveira** [comment]
Same error now with October build 317.
I'm trying to display a formatted date field using the example from the docs: https://octobercms.com/docs/backend/lists#column-datetime 

```yaml
created_at:
    label: Date
    type: datetime
    format: l jS \of F Y h:i:s A
```
Exception:
```
/modules/backend/Widgets/form/partials/_field_datetime.htm" not found.
```

Is this really fixed? Which setting is missing in my example?
