### ISSUE TITLE
Point directly to your plugin folder inside your `fields.yaml`

### ISSUE THREAD

**Issue by Whyounes** [octobercms/october#808]
inside the `fields.yaml` files, i have something like this:

```
fields:

  content:
    type: hint
    path: @/plugins/rafie/quicknote/models/note/partials/hint.htm
```

I think it's better to do something like:

```
fields:

  content:
    type: hint
    path: $/models/note/partials/hint.htm
```

referencing your root plugin folder is better!!
