### ISSUE TITLE
Model field definitions and default value of '0'

### ISSUE THREAD

**Issue by demagu** [octobercms/october#845]
Hello,

When creating model's field definitions for field type `text` and `number` with default value of `0` the form input field won't be rendered properly.

Example definition:

```
    total:
        label: Total (CAD)
        type: number
        default: 0
```

will render:

`<input type="text" name="Order[total]" id="Form-field-Order-total" value="" placeholder="" class="form-control" autocomplete="off" maxlength="255" pattern="\d+">`

while it obviously should render:

`<input type="text" name="Order[total]" id="Form-field-Order-total" value="0" placeholder="" class="form-control" autocomplete="off" maxlength="255" pattern="\d+">`

Thanks
