### ISSUE TITLE
Wrong SQL when using RelationsController's BelongsToMany with pivot table

### ISSUE THREAD

**Issue by shina** [octobercms/october#847]
When trying to associate a new relation with a model with a pivot, this SQL error is being showing:

"SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in where clause is ambiguous (SQL: select count(*) as aggregate from `acme_foo_foos` inner join `bar_foo` on `acme_foo_foos`.`id` = `bar_foo`.`foo_id` where `bar_foo`.`bar_id` = 1 and `id` = 1)" on line 625 of /Users/shina/projects/octobercms/vendor/laravel/framework/src/Illuminate/Database/Connection.php

I made a plugin with the minimum to reproduce this error and the steps are:

1. Create a plugin with 3 models: Bar, Baz and Foo
Where Baz is the pivot of Bar and Foo

2. Bar and Foo are "belongsToMany (with pivot)" of each other

3. Create a controller called Bars

4. use the RelationsController with the following config:
    ```yaml
foos:
        label: Foos
        emptyMessage: Empty
        list: @/plugins/acme/foo/models/foo/columns.yaml
        form: @/plugins/acme/foo/models/foo/fields.yaml
        pivot: @/plugins/acme/foo/models/baz/fields.yaml
```

5. Put the <?= $this->relationRender('foos') ?> on create.htm and update.htm templates

When trying to use the interface to make a new Bar associated with Foo, the interface asks you which Foo you want, then select one of the Foos registered, then a box asks the value of the pivot, after that it crash with the error above.

To make it easy to understand, please download this following plugin with all those steps reproduced.
https://www.wetransfer.com/downloads/f93f71cb46ca4788c9b4435aa1a4434820141223104318/5d693d
