### ISSUE TITLE
depends attribute on relation modal

### ISSUE THREAD

**Issue by chesterx** [octobercms/october#862]
Hi,

There is a bug on relation modal if a form field depends on another field. Changing the parent field triggers loading after success closes the modal.

fields.yaml
```
    country:
        label: Country
        type: dropdown
    state:
        label: State
        depends: country
        type: dropdown
```

Thank you
